/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct BKSDisplayBrightnessTransaction;

struct CGAffineTransform {
    float a;
    float b;
    float c;
    float d;
    float tx;
    float ty;
};

struct CGColor;

struct CGContext;

struct CGImage;

struct CGImageSource;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct MGNotificationTokenStruct;

struct SBBannerDismissGestureState {
    char _field1;
    char _field2;
    struct CGSize _field3;
    struct CGSize _field4;
    struct CGRect _field5;
    int _field6;
    float _field7;
    char _field8;
};

struct SBIconCoordinate {
    int row;
    int col;
};

struct SBWindowLevelRange_struct {
    float start;
    float end;
};

struct UIEdgeInsets {
    float top;
    float left;
    float bottom;
    float right;
};

struct _CARenderImage;

struct _MISProfile;

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSZone;

struct __CFArray;

struct __CFBoolean;

struct __CFDictionary;

struct __CFString;

struct __CTServerConnection;

struct __GSEvent;

struct __IOHIDEvent;

struct __MKBAssertion;

struct __SBGestureContext;

struct __SCDynamicStore;

struct __WiFiDeviceClient;

struct __WiFiManagerClient;

struct __WiFiNetwork;

struct __darwin_pthread_handler_rec;

struct _opaque_pthread_mutex_t {
    long __sig;
    char __opaque[40];
};

struct _opaque_pthread_t {
    long _field1;
    struct __darwin_pthread_handler_rec *_field2;
    char _field3[596];
};

struct tcp_connection_fallback_watch_s;

typedef struct {
    float x;
    float y;
    float scale;
    float rotate;
} CDAnonymousStruct9;

typedef struct {
    char itemIsEnabled[25];
    char timeString[64];
    int gsmSignalStrengthRaw;
    int gsmSignalStrengthBars;
    char serviceString[100];
    char serviceCrossfadeString[100];
    char serviceImages[2][100];
    char operatorDirectory[1024];
    unsigned int serviceContentType;
    int wifiSignalStrengthRaw;
    int wifiSignalStrengthBars;
    unsigned int dataNetworkType;
    int batteryCapacity;
    unsigned int batteryState;
    char batteryDetailString[150];
    int bluetoothBatteryCapacity;
    int thermalColor;
    unsigned int thermalSunlightMode:1;
    unsigned int slowActivity:1;
    unsigned int syncActivity:1;
    char activityDisplayId[256];
    unsigned int bluetoothConnected:1;
    unsigned int displayRawGSMSignal:1;
    unsigned int displayRawWifiSignal:1;
    unsigned int locationIconType:1;
    unsigned int quietModeInactive:1;
    unsigned int tetheringConnectionCount;
} CDAnonymousStruct10;

typedef struct {
    int startStyle;
    int endStyle;
    float transitionFraction;
} CDAnonymousStruct7;

typedef struct {
    int type;
    int modifier;
    unsigned int pathIndex;
    unsigned int pathIdentity;
    struct CGPoint location;
    struct CGPoint previousLocation;
    struct CGPoint unrotatedLocation;
    struct CGPoint previousUnrotatedLocation;
    float totalDistanceTraveled;
    int interfaceOrientation;
    int previousInterfaceOrientation;
    double timestamp;
} CDAnonymousStruct11;

typedef struct {
    char _field1;
    char _field2;
    char _field3;
    char _field4;
    float _field5;
    int _field6;
} CDAnonymousStruct5;

typedef struct {
    char valid;
    CDAnonymousStruct7 styleTransitionState;
} CDAnonymousStruct2;

typedef struct {
    unsigned int _field1[8];
} CDAnonymousStruct3;

typedef struct {
    unsigned int willActivate:1;
    unsigned int didActivate:1;
    unsigned int willDeactivate:1;
    unsigned int didDeactivate:1;
    unsigned int didChangeTop:1;
    unsigned int topBgStyleChange:1;
    unsigned int willTearDownWindow:1;
    unsigned int didTearDownWindow:1;
    unsigned int didRemoveFromWindow:1;
} CDAnonymousStruct6;

typedef struct {
    unsigned long _field1;
    id *_field2;
    unsigned long *_field3;
    unsigned long _field4[5];
} CDAnonymousStruct1;

typedef struct {
    int _field1;
    int _field2;
} CDAnonymousStruct4;

typedef struct {
    id _field1;
    id _field2;
    id _field3;
    id _field4;
} CDAnonymousStruct8;

