/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary;

@interface RLNDataProviderFactory : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_dataProvidersBySectionID;
}

+ (id)sharedInstance;
- (void)_notePushStoreAppsDidChange:(id)fp8;
- (void)_noteInstalledAppsDidChange:(id)fp8;
- (void)reloadDataProviders;
- (void)_reloadDataProviders:(id)fp8;
- (id)createDataProviderWithSectionID:(id)fp8;
- (void)dealloc;
- (id)init;

@end

