/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBRemoteDataProvider-Protocol.h"
#import "SBPushStoreObserver-Protocol.h"

@class BBDataProviderProxy, BBSectionInfo, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface RLNDataProvider : _ABAddressBookCopyLocalizedLabel <SBPushStoreObserver, BBRemoteDataProvider>
{
    NSString *_sectionID;
    NSMutableSet *_publisherBulletinIDs;
    BBSectionInfo *_defaultSectionInfo;
    NSString *_displayName;
    unsigned int _pushSettings;
    BBDataProviderProxy *_proxy;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void)setProxy:(id)fp8;
- (id)proxy;
- (void)pushStoreUserDeclinedDelivery;
- (void)pushStoreUserAcceptedDelivery;
- (void)_saveUpdatedSectionInfo;
- (void)pushStoreUpdatedPushSettings;
- (void)pushStoreClearedNotifications;
- (void)pushStoreNotificationsDidChange;
- (BOOL)syncsBulletinDismissal;
- (void)noteSectionInfoDidChange:(id)fp8;
- (id)sectionIdentifier;
- (id)sortDescriptors;
- (id)clearedInfoForBulletins:(id)fp8 lastClearedInfo:(id)fp12;
- (id)clearedInfoAndBulletinsForClearingAllBulletinsWithLimit:(unsigned int)fp8 lastClearedInfo:(id)fp12;
- (id)bulletinsFilteredBy:(unsigned int)fp8 count:(unsigned int)fp12 lastCleared:(id)fp16;
- (id)_allBulletinsWithLimit:(unsigned int)fp8;
- (void)_cleanupMigrationFromBrightonWithLastClearedDate:(id)fp8;
- (id)_latestBulletinInSet:(id)fp8;
- (id)_bulletinForNotification:(id)fp8;
- (id)_publisherBulletinIDForNotification:(id)fp8;
- (id)sectionDisplayName;
- (id)defaultSectionInfo;
- (void)rebuildDefaultSectionInfoForPushSettings:(unsigned int)fp8;
- (id)sectionParameters;
- (id)_sortKey;
- (BOOL)_isPushDataProvider;
- (void)invalidate;
- (void)dealloc;
- (id)initWithSectionID:(id)fp8 displayName:(id)fp12 queue:(id)fp16;

@end

