/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBActivationInfoViewController : _ABAddressBookCopyLocalizedLabel
{
    NSString *_meid;
    NSString *_imei;
    NSString *_iccid;
    float _alertHeight;
}

- (id)_formattedIMEI;
- (id)_formattedICCID;
- (void)_simStatusChanged:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (void)_updateTextView;
- (id)textView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

