/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class UIViewController;

@interface SBAlertAdapter : SBAlert
{
    UIViewController *_effectiveViewController;
}

- (id)effectiveViewController;
- (void)setDisplay:(id)fp8;
- (id)description;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (id)display;
- (void)alertWindow:(id)fp8 resizedFromContentFrame:(struct CGRect)fp12 toContentFrame:(struct CGRect)fp28;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (void)setView:(id)fp8;
- (void)dealloc;
- (id)initWithViewController:(id)fp8;

@end

