/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBAlertItemsSettings : _ABAddressBookCopyLocalizedLabel
{
    BOOL _disableBBHandlers;
    int _testItemToken;
}

+ (id)newTestItemForToken:(int)fp8;
+ (id)settingsControllerModule;
- (void)setTestItemToken:(int)fp8;
- (int)testItemToken;
- (void)setDisableBBHandlers:(BOOL)fp8;
- (BOOL)disableBBHandlers;
- (void)setDefaultValues;

@end

