/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAlertManagerObserver-Protocol.h"

@class NSMapTable, NSMutableSet, SBAlertManager;

@interface SBAlertWallpaperTunnelManager : _ABAddressBookCopyLocalizedLabel <SBAlertManagerObserver>
{
    SBAlertManager *_alertManager;
    NSMapTable *_hiderToHideeMap;
    NSMutableSet *_hiddenAlerts;
}

+ (void)registerAlertManager:(id)fp8 forScreen:(id)fp12;
+ (id)sharedInstance;
- (id)dumpTunnelState;
- (void)alertManager:(id)fp8 didDeactivateAlert:(id)fp12 top:(BOOL)fp16;
- (void)alertManager:(id)fp8 willActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)_showAlert:(id)fp8;
- (void)_hideAlert:(id)fp8;
- (void)_adjustHiddenAlerts;
- (void)_stopHidingAlertsForAlert:(id)fp8;
- (void)_hideAlerts:(id)fp8 onBehalfOfAlert:(id)fp12;
- (void)_setAlertManager:(id)fp8;
- (void)popTunnelToWallpaperForAlert:(id)fp8;
- (void)pushTunnelToWallpaperForAlert:(id)fp8;
- (void)dealloc;
- (id)init;

@end

