/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertView.h"

@interface SBAlertViewAdapter : SBAlertView
{
}

- (void)alertWindowViewControllerResizedFromContentFrame:(struct CGRect)fp8 toContentFrame:(struct CGRect)fp24;
- (void)setAlert:(id)fp8;
- (id)alert;

@end

