/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBAssertionDelegate-Protocol.h"
#import "SBVolumePressBandit-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class BBObserver, CPDistributedNotificationCenter, NSHashTable, NSMutableArray, NSMutableSet, NSTimer, SBAlertItem, SBAlertItemsSettings;

@interface SBAlertItemsController : _ABAddressBookCopyLocalizedLabel <_UISettingsKeyObserver, SBVolumePressBandit, SBAssertionDelegate, BBObserverDelegate>
{
    NSMutableArray *_lockedAlertItems;
    NSMutableArray *_unlockedAlertItems;
    NSMutableArray *_pendingAlertItems;
    NSMutableArray *_superModalAlertItems;
    NSTimer *_autoDismissTimer;
    CPDistributedNotificationCenter *_notificationCenter;
    unsigned int _notificationClientCount;
    BOOL _systemShuttingDown;
    BOOL _lockedButNotSetupYet;
    NSMutableSet *_forceAlertsToPendReasons;
    BBObserver *_bbObserver;
    NSHashTable *_observers;
    SBAlertItemsSettings *_settings;
    SBAlertItem *_testItem;
    NSMutableSet *_suppressionAssertions;
}

+ (id)sharedInstance;
- (id)lockedAlertItems;
- (void)assertionExpired:(id)fp8;
- (BOOL)captureSuppressionAssertionWithPort:(unsigned int)fp8 reason:(id)fp12;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)_notifyObservers:(id)fp(null);
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (void)_lockedButNotSetupYetChanged;
- (void)_buddyDidExit;
- (void)_notificationClientEnded:(id)fp8;
- (void)_notificationClientStarted:(id)fp8;
- (void)moveActiveAlertsToPendingWithAnimation:(BOOL)fp8;
- (void)setForceAlertsToPend:(BOOL)fp8 forReason:(id)fp12;
- (void)noteSystemShuttingDown;
- (void)notifySystemOfAlertItemActivation:(id)fp8;
- (void)_postAlertPresentedNotificationForType:(int)fp8 sender:(id)fp12 date:(id)fp16;
- (void)noteVolumeOrLockPressedOverLockedAlerts;
- (void)stopPendingAlertItemsForFullscreenAlert;
- (void)deactivateAlertItemsForFullscreenAlertActivationAndPendMiniAlerts:(BOOL)fp8;
- (BOOL)dontLockOverAlertItems;
- (BOOL)deactivateAlertForMenuClickOrSystemGestureWithAnimation:(BOOL)fp8;
- (BOOL)canDeactivateAlertForMenuClickOrSystemGesture;
- (id)visibleAlertItem;
- (BOOL)hasVisibleAlert;
- (BOOL)hasAlerts;
- (BOOL)hasAlertOfClass:(Class)fp8;
- (id)alertItemsOfClass:(Class)fp8;
- (void)autoDismissAlertItem:(id)fp8;
- (void)deactivateAlertItemsOfClass:(Class)fp8 reason:(int)fp12 animated:(BOOL)fp16;
- (void)deactivateAlertItemsOfClass:(Class)fp8 reason:(int)fp12;
- (void)deactivateAlertItemsOfClass:(Class)fp8;
- (void)deactivateAlertItem:(id)fp8;
- (void)deactivateAlertItem:(id)fp8 reason:(int)fp12 animated:(BOOL)fp16;
- (void)activatePendedAlertsIfNecessary;
- (void)_activateSuperModalAlertsIfNecessary;
- (void)deactivateAlertItem:(id)fp8 reason:(int)fp12;
- (void)activateAlertItem:(id)fp8;
- (void)resetAutoDismissTimer;
- (void)convertUnlockedAlertsToLockedAlerts;
- (id)description;
- (BOOL)hasVisibleSuperModalAlert;
- (void)dealloc;
- (id)init;

@end

