/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBAlert;

@interface SBAlertView : _ABAddressBookCopyLocalizedLabel
{
    SBAlert *_alert;
    unsigned int _shouldAnimateIn:1;
}

- (void)alertWindowViewControllerResizedFromContentFrame:(struct CGRect)fp8 toContentFrame:(struct CGRect)fp24;
- (void)setAlert:(id)fp8;
- (BOOL)shouldAddClippingViewDuringRotation;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)isSupportedInterfaceOrientation:(int)fp8;
- (void)layoutForInterfaceOrientation:(int)fp8;
- (BOOL)isAnimatingOut;
- (BOOL)shouldAnimateIn;
- (void)setShouldAnimateIn:(BOOL)fp8;
- (BOOL)isReadyToBeRemovedFromView;
- (void)alertDisplayBecameVisible;
- (void)alertDisplayWillBecomeVisible;
- (void)dismiss;
- (id)alert;
- (id)initWithFrame:(struct CGRect)fp8;

@end

