/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBDisplayProtocol-Protocol.h"

@class NSHashTable, NSMapTable, NSMutableDictionary, SBActivationContext, SBAlertManager, SBAlertView, UIScreen;

@interface SBAlert : _ABAddressBookCopyLocalizedLabel <SBDisplayProtocol>
{
    id <SBAlertDelegate> _alertDelegate;
    SBAlertView *_display;
    NSMutableDictionary *_dictionary;
    SBActivationContext *_activationContext;
    BOOL _isWallpaperTunnelActive;
    BOOL _backgroundStyleIsSet;
    int _backgroundStyle;
    NSMapTable *_displayValues;
    NSHashTable *_displayFlags;
    BOOL _orientationChangedEventsEnabled;
    float _accelerometerSampleInterval;
    BOOL _requestedDismissal;
    UIScreen *_targetScreen;
    SBAlertManager *_alertManager;
}

+ (void)test;
+ (void)registerForAlerts;
- (void)setAlertManager:(id)fp8;
- (id)alertManager;
- (void)_setRequestedDismissal:(BOOL)fp8;
- (BOOL)_requestedDismissal;
- (void)setActivationContext:(id)fp8;
- (id)activationContext;
- (BOOL)_isLockAlert;
- (void)_removeFromImpersonatedAppIfNecessary;
- (id)_impersonatesApplicationWithBundleID;
- (void)removeFromView;
- (void)alertViewIsReadyToDismiss:(id)fp8;
- (void)setDisplay:(id)fp8;
- (void)setAlertDelegate:(id)fp8;
- (id)alertDelegate;
- (BOOL)_shouldDismissSwitcherOnActivation;
- (BOOL)suppressesControlCenter;
- (BOOL)suppressesNotificationCenter;
- (BOOL)suppressesBanners;
- (void)handleAutoLock;
- (BOOL)handleHeadsetButtonPressed:(BOOL)fp8;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)hasTranslucentBackground;
- (BOOL)shouldPendAlertItemsWhileActive;
- (void)handleSlideshowHardwareButton;
- (BOOL)handleMenuButtonHeld;
- (BOOL)handleMenuButtonDoubleTap;
- (BOOL)handleMenuButtonTap;
- (void)animateDeactivation;
- (BOOL)currentlyAnimatingDeactivation;
- (void)didFinishAnimatingOut;
- (void)didFinishAnimatingIn;
- (void)didAnimateLockKeypadOut;
- (void)didAnimateLockKeypadIn;
- (id)legibilitySettings;
- (id)effectiveStatusBarStyleRequest;
- (int)effectiveStatusBarStyle;
- (id)statusBarStyleRequest;
- (int)starkStatusBarStyle;
- (int)statusBarStyle;
- (double)autoLockTime;
- (BOOL)managesOwnStatusBarAtActivation;
- (double)autoDimTime;
- (BOOL)allowsEventOnlySuspension;
- (BOOL)expectsFaceContactInLandscape;
- (BOOL)expectsFaceContact;
- (void)setExpectsFaceContact:(BOOL)fp8 inLandscape:(BOOL)fp12;
- (void)setExpectsFaceContact:(BOOL)fp8;
- (double)accelerometerSampleInterval;
- (void)setAccelerometerSampleInterval:(double)fp8;
- (BOOL)orientationChangedEventsEnabled;
- (void)setOrientationChangedEventsEnabled:(BOOL)fp8;
- (id)description;
- (void)deactivate;
- (int)interfaceOrientationForActivation;
- (void)activate;
- (int)statusBarStyleOverridesToCancel;
- (void)displayDidDisappear;
- (float)finalAlpha;
- (BOOL)showsSpringBoardStatusBar;
- (BOOL)undimsDisplay;
- (BOOL)allowsStackingOfAlert:(id)fp8;
- (void)removeObjectForKey:(id)fp8;
- (id)objectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (id)deactivationValue:(unsigned int)fp8;
- (BOOL)deactivationFlag:(unsigned int)fp8;
- (void)setDeactivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setDeactivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearDeactivationSettings;
- (id)activationValue:(unsigned int)fp8;
- (BOOL)activationFlag:(unsigned int)fp8;
- (void)setActivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setActivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearActivationSettings;
- (void)removeBackgroundStyleWithAnimationFactory:(id)fp8;
- (void)setBackgroundStyle:(int)fp8 withAnimationFactory:(id)fp12;
- (int)customBackgroundStyle;
- (BOOL)wantsCustomBackgroundStyle;
- (BOOL)isWallpaperTunnelActive;
- (void)setWallpaperTunnelActive:(BOOL)fp8;
- (BOOL)displayFlag:(unsigned int)fp8;
- (id)displayValue:(unsigned int)fp8;
- (void)setDisplaySetting:(unsigned int)fp8 value:(id)fp12;
- (void)setDisplaySetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearDisplaySettings;
- (void)dismissAlert;
- (void)clearDisplay;
- (id)display;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)didMoveToParentViewController:(id)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (BOOL)wantsFullScreenLayout;
- (id)_screen;
- (void)_setTargetScreen:(id)fp8;
- (void)dealloc;
- (id)init;
- (BOOL)isRemote;
- (BOOL)matchesRemoteAlertService:(id)fp8 options:(id)fp12;
- (id)effectiveViewController;

@end

