/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBWindow.h"

@class NSMapTable, SBAlertWindowViewController;

@interface SBAlertWindow : SBWindow
{
    SBAlertWindowViewController *_rootViewController;
    NSMapTable *_alertToDisplayMap;
}

+ (int)jailBehavior;
- (void)noteInterfaceOrientationChangingTo:(int)fp8 animated:(BOOL)fp12;
- (id)stackedAlertsIncludingActiveAlert:(BOOL)fp8;
- (int)stackedDisplayCount;
- (BOOL)hasActiveAlertsOrDisplays;
- (BOOL)deactivateAlert:(id)fp8;
- (void)displayAlert:(id)fp8;
- (BOOL)isOpaque;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithScreen:(id)fp8;
- (id)initWithScreen:(id)fp8 rootViewController:(id)fp12;

@end

