/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableSet, SBAlert, UIScreen, UIView, UIViewController;

@interface SBAlertWindowViewController : _ABAddressBookCopyLocalizedLabel
{
    UIScreen *_screen;
    UIView *_contentView;
    SBAlert *_activeAlert;
    UIViewController *_activeViewController;
    NSMutableSet *_childAlerts;
}

- (void)setActiveViewController:(id)fp8;
- (id)activeViewController;
- (void)setActiveAlert:(id)fp8;
- (id)activeAlert;
- (void)window:(id)fp8 willAnimateFromContentFrame:(struct CGRect)fp12 toContentFrame:(struct CGRect)fp28;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)wantsFullScreenLayout;
- (void)noteAlertWindow:(id)fp8 didDisplayAlert:(id)fp12;
- (BOOL)alertWindow:(id)fp8 canAnimateInAlert:(id)fp12;
- (id)stackedViewForAlert:(id)fp8;
- (id)stackedAlertsIncludingActiveAlert:(BOOL)fp8;
- (int)stackedAlertCount;
- (void)removeAlertController:(id)fp8;
- (void)addAlertController:(id)fp8;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithScreen:(id)fp8;

@end

