/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBApplicationTerminationAssertion-Protocol.h"

@class NSString, SBApplicationTerminationAssertionManager;

@interface SBApplicationTerminationAssertionImpl : _ABAddressBookCopyLocalizedLabel <SBApplicationTerminationAssertion>
{
    NSString *_displayId;
    unsigned char _reason;
    SBApplicationTerminationAssertionManager *_manager;
}

- (unsigned char)reason;
- (id)displayId;
- (id)description;
- (void)dealloc;
- (id)initWithDisplayId:(id)fp8 reason:(unsigned char)fp12 manager:(id)fp16;

@end

