/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSHashTable, NSMutableDictionary, NSMutableOrderedSet;

@interface SBAppStatusBarManager : _ABAddressBookCopyLocalizedLabel
{
    NSHashTable *_disableAlphaChangeAssertions;
    NSMutableOrderedSet *_windowLevelOverrideReasons;
    NSMutableDictionary *_windowLevelOverrideMap;
    float _defaultWindowLevel;
}

+ (id)sharedInstance;
- (void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)fp8;
- (void)_addDisableAppStatusBarAlphaChangesAssertion:(id)fp8;
- (void)_updateWindowLevel;
- (void)removeWindowLevelOverrideReason:(id)fp8;
- (void)setWindowLevel:(float)fp8 forOverrideReason:(id)fp12;
- (void)setDefaultWindowLevel:(float)fp8;
- (void)setStatusBarAlpha:(float)fp8;
- (void)hideStatusBar;
- (void)showStatusBar;
- (BOOL)isStatusBarHidden;
- (void)dealloc;
- (id)init;

@end

