/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "_SBUISwitcherPageHostInterface-Protocol.h"

@interface SBAppSwitcherPageServiceRemoteViewController : _ABAddressBookCopyLocalizedLabel <_SBUISwitcherPageHostInterface>
{
}

+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

