/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, SBAppSliderScrollView, SBStopScrollingGestureRecognizer, UITapGestureRecognizer;

@interface SBAppSliderScrollingViewController : _ABAddressBookCopyLocalizedLabel <UIScrollViewDelegate>
{
    NSMutableArray *_items;
    SBAppSliderScrollView *_scrollView;
    BOOL _dragMaster;
    BOOL _preventScroll;
    UITapGestureRecognizer *_tapGesture;
    SBStopScrollingGestureRecognizer *_stopScrollingGesture;
    int _layoutOrientation;
    id _scrollDoneBlock;
    id <SBAppSliderScrollingViewDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewWillEndDragging:(id)fp8 withVelocity:(struct CGPoint)fp12 targetContentOffset:(inout struct CGPoint *)fp20;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)_fireAndCleanupScrollCompleteBlockIfNecessary;
- (void)_setContentOffset:(struct CGPoint)fp8 animated:(BOOL)fp16;
- (void)_enableScrolling;
- (void)_disableScrolling;
- (BOOL)_isIndexVisible:(unsigned int)fp8 withSidePadding:(float)fp12;
- (void)_updateVisiblePageViews;
- (void)_layout;
- (void)_layoutIndexContainer:(unsigned int)fp8;
- (void)_generateViewIndexIfNecessary:(unsigned int)fp8;
- (struct CGRect)_naturalScrollViewFrame;
- (struct CGPoint)_centerOfIndex:(unsigned int)fp8;
- (float)_distanceBetweenCenters;
- (void)_handleStopGesture:(id)fp8;
- (void)_handleTapGesture:(id)fp8;
- (void)removeIndex:(unsigned int)fp8 duration:(double)fp12;
- (void)reloadInOrientation:(int)fp8;
- (float)_halfWidth;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)loadView;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (float)preferredHeightForOrientation:(int)fp8;
- (void)switcherWasDismissed:(BOOL)fp8;
- (struct _NSRange)visibleItems;
- (BOOL)isScrolling;
- (BOOL)_isAnyScrollContainerScrolling;
- (id)pageViewForIndex:(unsigned int)fp8;
- (unsigned int)currentPage;
- (void)_setScrollingDoneBlock:(id)fp(null);
- (BOOL)isIndexVisible:(unsigned int)fp8;
- (unsigned int)settledIndexForNormalizedOffset:(inout float *)fp8 andXVelocity:(float)fp12;
- (float)normalizedOffsetForOffset:(float)fp8 andXVelocity:(float)fp12;
- (float)normalizedOffsetOfIndex:(unsigned int)fp8;
- (float)normalizedOffset;
- (void)setNormalizedOffset:(float)fp8;
- (void)setOffsetToIndex:(unsigned int)fp8 animated:(BOOL)fp12 completion:(id)fp(null);
- (void)setOffsetToIndex:(unsigned int)fp8 animated:(BOOL)fp12;
- (void)cancelScrolling;
- (float)_maxXOffset;
- (void)dealloc;
- (id)init;

@end

