/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBFAnimationSettings, _UIScreenEdgePanRecognizerSettings;

@interface SBAppSliderSettings : _ABAddressBookCopyLocalizedLabel
{
    int _simplicityOptions;
    SBFAnimationSettings *_dosidoAnimationSettings;
    _UIScreenEdgePanRecognizerSettings *_gestureSettings;
}

+ (id)settingsControllerModule;
- (void)setGestureSettings:(id)fp8;
- (id)gestureSettings;
- (void)setDosidoAnimationSettings:(id)fp8;
- (id)dosidoAnimationSettings;
- (void)setSimplicityOptions:(int)fp8;
- (int)simplicityOptions;
- (BOOL)shouldSimplifyForOptions:(int)fp8;
- (void)setDefaultValues;

@end

