/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAppSliderIconControllerDelegate-Protocol.h"
#import "SBAppSliderScrollingViewDelegate-Protocol.h"
#import "SBVolumePressBandit-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, SBAppSliderIconController, SBAppSliderScrollingViewController, SBAppSliderSettings, SBAppSwitcherServices, SBFakeStatusBarViewCache, UIView;

@interface SBAppSliderController : _ABAddressBookCopyLocalizedLabel <SBAppSliderIconControllerDelegate, SBAppSliderScrollingViewDelegate, _UISettingsKeyObserver, SBVolumePressBandit>
{
    id <SBAppSliderControllerDelegate> _delegate;
    NSMutableArray *_appList;
    SBAppSwitcherServices *_switcherServices;
    NSMutableDictionary *_switcherServiceViewControllerMap;
    unsigned int _appListAccessCount;
    SBAppSliderScrollingViewController *_pageController;
    SBAppSliderIconController *_iconController;
    UIView *_containerView;
    UIView *_contentView;
    UIView *_pageView;
    UIView *_iconView;
    UIView *_iconParallaxView;
    UIView *_iconParallaxCorrectionView;
    NSMutableSet *_hostedApplications;
    NSMutableDictionary *_appSnapshots;
    struct _NSRange _lastVisibleRange;
    unsigned int _startAnchorIndex;
    int _startingInterfaceOrientation;
    int _layoutInterfaceOrientation;
    BOOL _interactionEnabled;
    BOOL _visible;
    int _mode;
    BOOL _deferredWorkComplete;
    unsigned int _startingIndex;
    NSString *_startingDisplayIdentifier;
    NSDictionary *_startingViews;
    int _enterSide;
    SBAppSliderSettings *_settings;
    NSObject<OS_dispatch_queue> *_snapshotQueue;
    NSMutableArray *_servicesRemovedWhileAwayFromSwitcher;
    SBFakeStatusBarViewCache *_statusBarCache;
    struct CGAffineTransform _wallpaperTransform;
}

+ (BOOL)_shouldUseSerialSnapshotQueue;
+ (BOOL)shouldProvideHomeSnapshotIfPossible;
+ (BOOL)shouldProvideSnapshotIfPossible;
- (void)setWallpaperTransform:(struct CGAffineTransform)fp8;
- (struct CGAffineTransform)wallpaperTransform;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setStartingViews:(id)fp8;
- (id)startingViews;
- (void)setStartingDisplayIdentifier:(id)fp8;
- (id)startingDisplayIdentifier;
- (id)pageController;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)sliderScrollerDidEndScrolling:(id)fp8;
- (BOOL)sliderScroller:(id)fp8 itemWantsToBeKeptInViewHierarchy:(unsigned int)fp12;
- (void)sliderScroller:(id)fp8 itemWantsToBeRemoved:(unsigned int)fp12;
- (BOOL)sliderScroller:(id)fp8 isIndexRemovable:(unsigned int)fp12;
- (void)sliderScrollerBeganPanning:(id)fp8;
- (void)sliderScroller:(id)fp8 itemTapped:(unsigned int)fp12;
- (void)sliderScroller:(id)fp8 contentOffsetChanged:(float)fp12;
- (float)sliderScrollerDistanceBetweenItemCenters:(id)fp8 forOrientation:(int)fp12;
- (struct CGSize)sliderScrollerItemSize:(id)fp8 forOrientation:(int)fp12;
- (id)sliderScroller:(id)fp8 viewForIndex:(unsigned int)fp12;
- (unsigned int)sliderScrollerItemCount:(id)fp8;
- (void)sliderIconScrollerBeganPanning:(id)fp8;
- (void)sliderIconScrollerDidEndScrolling:(id)fp8;
- (unsigned int)sliderIconScroller:(id)fp8 settledIndexForNormalizedOffset:(inout float *)fp12 andXVelocity:(float)fp16;
- (void)sliderIconScroller:(id)fp8 activate:(id)fp12;
- (void)sliderIconScroller:(id)fp8 contentOffsetChanged:(float)fp12;
- (void)_bringIconViewToFront;
- (void)_updateSnapshots;
- (unsigned int)_totalSnapshotsToKeepAround;
- (BOOL)_isSnapshotDisplayIdentifier:(id)fp8;
- (BOOL)isScrolling;
- (id)_animationSettingsForIconAlphaTransition;
- (id)_transitionAnimationFactory;
- (int)_windowInterfaceOrientation;
- (void)_disableContextHostingForApp:(id)fp8;
- (void)_quitAppAtIndex:(unsigned int)fp8;
- (void)_temporarilyHostAppForQuitting:(id)fp8;
- (void)_endAppListAccess;
- (id)_beginAppListAccess;
- (id)_displayIDAtIndex:(unsigned int)fp8;
- (void)_appActivationStateDidChange:(id)fp8;
- (void)_noteLockScreenCameraDidShow;
- (id)_iconListForAppList:(id)fp8;
- (void)_setInteractionEnabled:(BOOL)fp8;
- (id)_generateCellViewForIndex:(unsigned int)fp8;
- (id)_snapshotViewForDisplayIdentifier:(id)fp8;
- (id)_viewForService:(id)fp8;
- (void)_switcherServiceRemoved:(id)fp8;
- (void)_snapshotChangedOnDisk:(id)fp8;
- (void)_updatePageViewScale:(float)fp8;
- (void)_updatePageViewScale:(float)fp8 xTranslation:(float)fp12;
- (void)_updateForAnimationFrame:(float)fp8 withAnchor:(unsigned int)fp12;
- (float)_frameScaleValueForAnimation;
- (float)_scaleForFullscreenPageView;
- (void)_reverseAppList;
- (BOOL)_inMode:(int)fp8;
- (float)_sliderThumbnailVerticalPositionOffset;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)_getRotationContentSettings:(CDAnonymousStruct5 *)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (id)applicationList;
- (BOOL)wantsFullScreenLayout;
- (id)pageForDisplayIdentifier:(id)fp8;
- (BOOL)allowShowHide;
- (void)forceDismissAnimated:(BOOL)fp8;
- (void)animateDismissalToDisplayIdentifier:(id)fp8 withCompletion:(id)fp(null);
- (void)switcherWasDismissed:(BOOL)fp8;
- (void)switcherWillBeDismissed:(BOOL)fp8;
- (void)switcherWasPresented:(BOOL)fp8;
- (void)_layoutInOrientation:(int)fp8;
- (void)animatePresentationFromDisplayIdentifier:(id)fp8 withViews:(id)fp12 fromSide:(int)fp16 withCompletion:(id)fp(null);
- (void)_layout;
- (struct CGRect)_nominalPageViewFrame;
- (id)iconController;
- (BOOL)prefersStatusBarHidden;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

