/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAppSwitcherPageContentView-Protocol.h"

@class SBWallpaperEffectView, SBWindowContextHostManager, UIView, UIView<SBWindowContextAppearance>;

@interface SBAppSwitcherContextHostWrapperView : _ABAddressBookCopyLocalizedLabel <SBAppSwitcherPageContentView>
{
    SBWindowContextHostManager *_contextHostManager;
    UIView *_containerView;
    UIView<SBWindowContextAppearance> *_contextHostView;
    UIView *_snapshotView;
    SBWallpaperEffectView *_wallpaperEffectView;
    int _orientation;
}

- (int)orientation;
- (void)_viewDidAnimatePresentation:(id)fp8;
- (void)_viewDidAnimateDismissal:(id)fp8;
- (void)_viewDismissing:(id)fp8;
- (void)_viewPresenting:(id)fp8;
- (void)setOrientation:(int)fp8;
- (struct CGAffineTransform)_rotationTransformForOrientation:(int)fp8;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)didMoveToSuperview;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 application:(id)fp24;
- (id)initWithFrame:(struct CGRect)fp8;

@end

