/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAppSwitcherPageContentView-Protocol.h"

@class NSObject<OS_dispatch_queue>, NSString, SBApplication, SBFakeStatusBarView, SBFakeStatusBarViewCache, SBSnapshotImageInfo, SBWallpaperEffectView, UIImageView, UIView;

@interface SBAppSliderSnapshotView : _ABAddressBookCopyLocalizedLabel <SBAppSwitcherPageContentView>
{
    SBApplication *_application;
    UIView *_containerView;
    SBWallpaperEffectView *_wallpaperEffectView;
    SBSnapshotImageInfo *_snapshotImageInfo;
    UIImageView *_snapshotImage;
    struct CGSize _imageSize;
    SBFakeStatusBarViewCache *_statusBarCache;
    SBFakeStatusBarView *_statusBar;
    NSString *_statusBarCacheKey;
    BOOL _isVisible;
    BOOL _invalidated;
    BOOL _needsZoomFilter;
    BOOL _loadedImage;
    NSObject<OS_dispatch_queue> *_snapshotQueue;
    int _orientation;
}

+ (id)_fallbackDefaultBackgroundColor;
+ (id)appSliderSnapshotViewForApplication:(id)fp8 orientation:(int)fp12 loadAsync:(BOOL)fp16 withQueue:(id)fp20 statusBarCache:(id)fp24;
- (void)setInvalidated:(BOOL)fp8;
- (BOOL)invalidated;
- (void)setOrientation:(int)fp8;
- (int)orientation;
- (void)setSnapshotImageInfo:(id)fp8;
- (id)snapshotImageInfo;
- (void)setApplication:(id)fp8;
- (id)application;
- (void)_viewDismissing:(id)fp8;
- (void)_viewPresenting:(id)fp8;
- (void)_updateStatusbarTranslucency;
- (void)_updateTranslucency;
- (id)_defaultImageforImageInfo:(id)fp8;
- (id)_snapshotImageForImageInfo:(id)fp8;
- (struct CGImage *)_cgImageForSnapshotInfo:(id)fp8;
- (id)_cachedImageForImageInfos:(id)fp8 foundInfo:(out id *)fp12;
- (struct CGAffineTransform)_rotationTransformForOrientation;
- (int)_containerOrientation;
- (struct CGRect)_snapshotFrame;
- (void)_snapshotImageLoaded:(struct CGImage *)fp8 withInfo:(id)fp12;
- (void)_loadImageAsyncFromSnapshotInfo:(id)fp8;
- (BOOL)_queue_keepGoing;
- (struct CGImage *)_queue_createDecodedImageIfPossible:(struct CGImage *)fp8;
- (id)_snapshotImage;
- (id)_imageAtPath:(id)fp8 preferredScale:(float)fp12 orientation:(out int *)fp16;
- (id)_snapshotInfos;
- (id)_snapshotInfoForDefaultPNG;
- (id)_snapshotInfoForSnapshotFromInfos:(id)fp8;
- (id)_cachedSnapshotForSnapshotInfos:(id)fp8 foundInfo:(out id *)fp12;
- (id)_snapshotName;
- (void)_loadSnapshotAsync;
- (void)_loadSnapshotSync;
- (void)invalidate;
- (void)setOrientation:(int)fp8 orientationBehavior:(int)fp12;
- (void)layoutSubviews;
- (void)_layoutContainer;
- (void)respondToBecomingInvisibleIfNecessary;
- (void)prepareToBecomeVisibleIfNecessary;
- (void)_layoutStatusBar;
- (id)_statusBarCacheKeyForStyleRequest:(id)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithApplication:(id)fp8 orientation:(int)fp12 async:(BOOL)fp16 withQueue:(id)fp20 statusBarCache:(id)fp24;
- (id)initWithFrame:(struct CGRect)fp8;

@end

