/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBApplicationRestrictionObserver <NSObject>
- (void)applicationRestrictionController:(id)fp8 didUpdateVisibleTags:(id)fp12 hiddenTags:(id)fp16;
@end

