/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView, UIView<SBAppSwitcherPageContentView>;

@interface SBAppSwitcherPageView : _ABAddressBookCopyLocalizedLabel
{
    UIView *_shadowView;
    UIView *_hitTestBlocker;
    UIView<SBAppSwitcherPageContentView> *_view;
    UIView *_overlayView;
    int _orientation;
}

+ (float)_edgeBorderForOrientation:(int)fp8;
+ (struct CGSize)sizeForOrientation:(int)fp8;
+ (float)scale;
- (int)orientation;
- (id)overlay;
- (id)view;
- (void)invalidate;
- (void)setShadowEnabled:(BOOL)fp8;
- (struct CGRect)_viewFrame;
- (struct CGAffineTransform)_transformForScale;
- (struct CGAffineTransform)_transformForOrientation:(int)fp8;
- (float)shadowAlpha;
- (void)setShadowAlpha:(float)fp8;
- (void)setOrientation:(int)fp8;
- (void)setOverlay:(id)fp8;
- (void)setView:(id)fp8;
- (void)setView:(id)fp8 animated:(BOOL)fp12;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

