/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBAppSwitcherPageView;

@interface SBAppSliderItemScrollView : _ABAddressBookCopyLocalizedLabel
{
    SBAppSwitcherPageView *_item;
    int _layoutOrientation;
}

- (void)setLayoutOrientation:(int)fp8;
- (int)layoutOrientation;
- (id)item;
- (void)_enableScrolling;
- (void)_disableScrolling;
- (void)setItem:(id)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

