/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBAppSwitcherService : _ABAddressBookCopyLocalizedLabel
{
    NSString *_bundleIdentifier;
    NSString *_viewServiceClassName;
}

+ (id)switcherServiceWithName:(id)fp8 viewServiceClassName:(id)fp12;
- (void)setViewServiceClassName:(id)fp8;
- (id)viewServiceClassName;
- (void)setBundleIdentifier:(id)fp8;
- (id)bundleIdentifier;
- (id)identifier;
- (void)dealloc;

@end

