/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBApplicationRestrictionDataSource-Protocol.h"
#import "SBLSApplicationLifecycleObserver-Protocol.h"

@class BKSApplicationStateMonitor, NSCountedSet, NSDictionary, NSLock, NSMutableDictionary, NSMutableSet, NSOperationQueue, SBApplication, SBApplicationRestrictionController, SBLSApplicationWorkspaceObserver;

@interface SBApplicationController : _ABAddressBookCopyLocalizedLabel <SBApplicationRestrictionDataSource, SBLSApplicationLifecycleObserver>
{
    NSMutableDictionary *_applications;
    NSMutableDictionary *_applicationsByBundleIdentifer;
    NSMutableSet *_applicationsPlayingMutedAudioSinceLastLock;
    SBApplication *_applicationCurrentlyRecordingAudio;
    int _locationStatusBarIconType;
    NSDictionary *_backgroundDisplayDict;
    NSOperationQueue *_backgroundOperationQueue;
    NSLock *_applicationsLock;
    NSMutableDictionary *_systemAppsVisibilityOverrides;
    BOOL _visibilityOverridesAreDirty;
    BKSApplicationStateMonitor *_appStateMonitor;
    BOOL _booting;
    NSMutableSet *_appsToAutoLaunchAfterBoot;
    SBApplicationRestrictionController *_restrictionController;
    SBLSApplicationWorkspaceObserver *_lsWorkspaceObserver;
    NSCountedSet *_pendingRequestedUninstallsBundleID;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)fp8;
- (void)applicationsUninstalled:(id)fp8;
- (void)applicationsInstalled:(id)fp8;
- (id)restrictionController;
- (void)_removePendingRequestedUninstalledBundleID:(id)fp8;
- (BOOL)updateAppIconVisibilityOverridesShowing:(id *)fp8 hiding:(id *)fp12;
- (void)_setVisibilityOverridesAreDirty:(BOOL)fp8;
- (int)appVisibilityOverrideForBundleIdentifier:(id)fp8;
- (void)_reloadBackgroundIDsDict;
- (void)loadApplicationsWithBundle:(id)fp8 bundlePath:(id)fp12 isSystemApplication:(BOOL)fp16 defaultTags:(id)fp20 signerIdentity:(id)fp24 provisioningProfileValidated:(BOOL)fp28 seatbeltEnvironmentVariables:(id)fp32 entitlements:(id)fp36;
- (Class)applicationClassForInfoDictionary:(id)fp8;
- (void)loadWebclipAndIcon:(id)fp8;
- (void)loadApplicationsAndIcons:(id)fp8 reveal:(BOOL)fp12 popIn:(BOOL)fp16;
- (void)_loadApplicationsAndIcons:(id)fp8 removed:(id)fp12 applicationProxies:(id)fp16 reveal:(BOOL)fp20 popIn:(BOOL)fp24 reloadAllIcons:(BOOL)fp28;
- (void)_updateIconControllerAndModelForLoadedApplications:(id)fp8 reveal:(BOOL)fp12 popIn:(BOOL)fp16 reloadAllIcons:(BOOL)fp20;
- (void)waitForOperationsToComplete;
- (void)uninstallApplication:(id)fp8;
- (void)removeApplicationsFromModelWithBundleIdentifier:(id)fp8;
- (BOOL)loadApplication:(id)fp8;
- (id)loadApplications;
- (id)_loadApplications:(id)fp8 removed:(id)fp12 applicationProxies:(id)fp16;
- (void)_calculateApplicationDiff:(id *)fp8 removed:(id *)fp12 applicationProxies:(id)fp16;
- (id)_modifiedApplications:(id)fp8 applicationProxies:(id)fp12;
- (BOOL)_applicationHasBeenModified:(id)fp8 applicationProxy:(id)fp12;
- (void)_loadApplication:(id)fp8 proxy:(id)fp12;
- (void)_sendInstalledAppsDidChangeNotification:(id)fp8 removed:(id)fp12 modified:(id)fp16;
- (void)_preLoadApplications;
- (id)_getLSApplicationProxies;
- (id)newsstandApps;
- (id)webApplications;
- (id)clockApplication;
- (id)faceTimeApp;
- (id)mobilePhone;
- (id)setupApplication;
- (id)dataActivation;
- (id)applicationCurrentlyRecordingAudio;
- (id)iPod;
- (id)applicationWithPid:(int)fp8;
- (id)applicationWithDisplayIdentifier:(id)fp8;
- (id)applicationsWithPid:(int)fp8;
- (id)applicationsWithBundleIdentifier:(id)fp8;
- (id)allApplications;
- (id)allDisplayIdentifiers;
- (void)autoLaunchAppsIfNecessaryAfterBoot;
- (void)_deviceFirstUnlocked;
- (int)locationStatusBarIconType;
- (void)buildLocationState;
- (void)_updateLocationState;
- (void)_memoryWarningReceived;
- (void)_lockStateChanged:(id)fp8;
- (void)_unusuallyMutedAudioPlaying:(id)fp8;
- (void)_recordingStateChanged:(id)fp8;
- (void)_mediaServerConnectionDied:(id)fp8;
- (void)_registerForAVSystemControllerNotifications;
- (void)_unregisterForAVSystemControllerNotifications;
- (void)dealloc;
- (id)init;

@end

