/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary;

@interface SBApplicationTerminationAssertionManager : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_assertionsByDisplayId;
}

+ (id)sharedInstance;
- (void)_removeTerminationAssertion:(id)fp8;
- (void)_addTerminationAssertion:(id)fp8;
- (BOOL)_canAcquireTerminationAssertionForDisplayId:(id)fp8 reason:(unsigned char)fp12 error:(char *)fp16;
- (id)acquireTerminationAssertionForDisplayId:(id)fp8 withReason:(unsigned char)fp12 error:(char *)fp16;
- (id)terminationAssertionsForDisplayId:(id)fp8 withReason:(unsigned char)fp12;
- (id)terminationAssertionsForDisplayId:(id)fp8;
- (void)dealloc;
- (id)init;

@end

