/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconObserver-Protocol.h"
#import "SBLSApplicationPlaceholderLifecycleObserver-Protocol.h"

@class NSMutableDictionary, NSMutableSet, SBApplicationController, SBLSApplicationWorkspaceObserver;

@interface SBApplicationPlaceholderController : _ABAddressBookCopyLocalizedLabel <SBIconObserver, SBLSApplicationPlaceholderLifecycleObserver>
{
    SBApplicationController *_appController;
    SBLSApplicationWorkspaceObserver *_lsWorkspaceObserver;
    NSMutableDictionary *_placeholdersByBundleID;
    NSMutableSet *_pendingAdded;
    NSMutableSet *_pendingInstalled;
    NSMutableSet *_pendingCancelled;
    BOOL _hasDownloadedFromStore;
    BOOL _usingNetwork;
}

+ (id)sharedInstance;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)_postPlaceholdersDidChangeForAdded:(id)fp8 modified:(id)fp12 removed:(id)fp16;
- (void)_downloadsEnded;
- (void)_finishPlaceholder:(id)fp8;
- (void)_dropGrabbedIconIfNecessary:(id)fp8 completion:(id)fp(null);
- (void)_removeDownloadingIcons:(id)fp8 saveState:(BOOL)fp12;
- (void)_swapDownloadingIcon:(id)fp8 forApplicationIcon:(id)fp12;
- (void)_removePlaceholders:(id)fp8 forInstall:(BOOL)fp12;
- (void)_addPlaceholders:(id)fp8;
- (void)_processPendingProxies;
- (void)applicationPlaceholdersNetworkUsageChanged:(BOOL)fp8;
- (void)applicationPlaceholdersIconUpdated:(id)fp8;
- (void)applicationPlaceholdersModified:(id)fp8;
- (void)applicationPlaceholdersCancelled:(id)fp8;
- (void)applicationPlaceholdersInstalled:(id)fp8;
- (void)applicationPlaceholdersAdded:(id)fp8;
- (BOOL)isUsingNetwork;
- (BOOL)hasDownloadedStoreApplication;
- (id)placeholderForDisplayID:(id)fp8;
- (id)placeholdersByDisplayID;
- (void)dealloc;
- (id)init;

@end

