/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIPluginHost.h"

@class NSHashTable, NSMutableSet, NSString, SBAssistantWindow, SBOperationQueue, SBPasscodeLockDisableAssertion, UIViewController<SBUIPluginViewControllerInterface>;

@interface SBAssistantController : SBUIPluginHost
{
    SBOperationQueue *_operationQueue;
    NSString *_appDisplayIDBeingHosted;
    SBAssistantWindow *_assistantWindow;
    BOOL _unlockedDevice;
    BOOL _launchedInStark;
    BOOL _isHidingOtherWindows;
    int _activationEvent;
    SBPasscodeLockDisableAssertion *_disableAssertion;
    NSMutableSet *_dismissingReasons;
    int _pendingDismissViewType;
    NSHashTable *_observers;
    UIViewController<SBUIPluginViewControllerInterface> *_mainScreenViewController;
}

+ (BOOL)isAssistantRunningHidden;
+ (BOOL)isAssistantViewVisible:(int)fp8;
+ (BOOL)isAssistantVisible;
+ (BOOL)shouldEnterAssistant;
+ (BOOL)supportedAndEnabled;
+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
- (BOOL)unlockedDevice;
- (void)uiPlugin:(id)fp8 forceUpdateToInterfaceOrientation:(int)fp12 animated:(BOOL)fp16;
- (void)uiPlugin:(id)fp8 isNowRunning:(BOOL)fp12;
- (void)uiPluginUserEventOccurred:(id)fp8;
- (BOOL)uiPlugin:(id)fp8 openURL:(id)fp12;
- (BOOL)uiPlugin:(id)fp8 launchApplicationWithBundleID:(id)fp12 openURL:(id)fp16;
- (BOOL)uiPluginAttemptDeviceUnlock:(id)fp8 withPassword:(id)fp12 lockViewOwner:(id)fp16;
- (BOOL)uiPluginWantsActivation:(id)fp8 forEvent:(int)fp12 completion:(id)fp(null);
- (void)_dismissUIPlugin:(id)fp8 animated:(BOOL)fp12;
- (void)dismissPluginForEvent:(int)fp8;
- (BOOL)pluginSuppressesNotifications;
- (BOOL)pluginWantsScreenDimInterval:(double *)fp8;
- (BOOL)pluginWantsInterfaceOrientation:(int *)fp8;
- (void)preparePluginForActivationEvent:(int)fp8 afterInterval:(double)fp12;
- (BOOL)pluginWantsActivationEvent:(int)fp8 interval:(double *)fp12;
- (void)_viewController:(id)fp8 animateDisappearanceWithContext:(id)fp12;
- (void)_viewController:(id)fp8 willAnimateDisappearanceWithContext:(id)fp12;
- (void)_viewController:(id)fp8 animateAppearanceWithContext:(id)fp12;
- (void)_viewController:(id)fp8 willAnimateAppearanceWithContext:(id)fp12;
- (void)_viewController:(id)fp8 setShowsStatusBar:(BOOL)fp12;
- (void)_dismissForMainScreenAnimated:(BOOL)fp8 duration:(double)fp12 completion:(id)fp(null);
- (id)_fakeStatusBarForOrientation:(int)fp8;
- (void)_presentForMainScreenAnimated:(BOOL)fp8 completion:(id)fp(null);
- (void)_notifyObserversViewDidDisappear:(int)fp8;
- (void)_notifyObserversViewWillDisappear:(int)fp8;
- (void)_notifyObserversViewDidAppear:(int)fp8;
- (void)_notifyObserversViewWillAppear:(int)fp8;
- (void)_bioAuthenticated:(id)fp8;
- (void)_starkSiriDidDisappear:(id)fp8;
- (void)_starkSiriWillDisappear:(id)fp8;
- (void)_starkSiriDidAppear:(id)fp8;
- (void)_starkSiriWillAppear:(id)fp8;
- (void)_viewDidDisappearOnMainScreen;
- (void)_viewWillDisappearOnMainScreen;
- (void)_viewDidAppearOnMainScreen;
- (void)_viewWillAppearOnMainScreen;
- (void)_cleanupContextHosting;
- (id)_activationFlags;
- (BOOL)_isPluginLoaded;
- (void)_loadPlugin;
- (BOOL)_isDismissingAllViews;
- (double)_defaultAnimatedDismissDurationForMainScreen;
- (id)transferOwnershipOfPasscodeLockDisableAssertion;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (id)mainScreenView;
- (BOOL)activateIgnoringTouches;
- (BOOL)shouldShowLockStatusBarTime;
- (void)setUnlockedDevice:(BOOL)fp8;
- (void)dismissAssistantForAlertActivation:(id)fp8;
- (void)dismissAssistantViewIfNecessaryWithFade:(int)fp8 ofDuration:(double)fp12 completion:(id)fp(null);
- (void)dismissAssistantViewIfNecessaryWithFade:(int)fp8 ofDuration:(double)fp12;
- (void)dismissAssistantViewIfNecessaryWithFade:(int)fp8;
- (void)dismissAssistantViewIfNecessary:(int)fp8;
- (void)addActivationFlagsToDisplay:(id)fp8;
- (void)_notePluginVisibilityDidChange;
- (void)dealloc;
- (id)init;
- (BOOL)_runActivateAssistantTest:(id)fp8;
- (void)_activateSiriForPPT;
- (BOOL)isAssistantViewVisible:(int)fp8;

@end

