/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAwayListItem.h"

@class SBSCardItem, UIImage;

@interface SBAwayCardListItem : SBAwayListItem
{
    SBSCardItem *_cardItem;
    UIImage *_cardThumbnail;
    UIImage *_iconImage;
}

- (void)setIconImage:(id)fp8;
- (id)iconImage;
- (void)setCardThumbnail:(id)fp8;
- (id)cardThumbnail;
- (id)cardItem;
- (id)body;
- (id)title;
- (void)setCardItem:(id)fp8;
- (BOOL)inertWhenLocked;
- (id)sortDate;
- (void)dealloc;

@end

