/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "NSCopying-Protocol.h"
#import "SBAwayListCellButtonHandler-Protocol.h"
#import "SBUIQuietModePlayability-Protocol.h"

@class NSDate, NSString, SBUnlockActionContext;

@interface SBAwayListItem : _ABAddressBookCopyLocalizedLabel <SBAwayListCellButtonHandler, SBUIQuietModePlayability, NSCopying>
{
    NSDate *_timestamp;
    BOOL _isNewItem;
    SBUnlockActionContext *_unlockActionContext;
    NSString *_buttonLabel;
}

- (void)setButtonLabel:(id)fp8;
- (id)buttonLabel;
- (void)setIsNewItem:(BOOL)fp8;
- (BOOL)isNewItem;
- (void)setTimestamp:(id)fp8;
- (id)timestamp;
- (BOOL)overridesQuietMode;
- (BOOL)isCritical;
- (BOOL)inertWhenLocked;
- (void)dealloc;
- (BOOL)canBeClearedByNotificationCenter;
- (BOOL)wantsHighlightOnInsert;
- (void)buttonPressed;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

