/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAwayListItem.h"

@class BBBulletin, BBObserver, NSDate, NSMutableArray, NSString, UIImage;

@interface SBAwayBulletinListItem : SBAwayListItem
{
    NSMutableArray *_bulletins;
    int _personID;
    NSString *_contactInfo;
    BBObserver *_observer;
    NSDate *_sortDate;
    NSDate *_displayDate;
    NSString *_message;
    UIImage *_listItemImage;
    BBBulletin *_activeBulletin;
}

- (void)setActiveBulletin:(id)fp8;
- (id)activeBulletin;
- (BOOL)overridesQuietMode;
- (BOOL)isCritical;
- (BOOL)inertWhenLocked;
- (id)observer;
- (int)snoozeButtonindex;
- (BOOL)wantsHighlightOnInsert;
- (void)buttonPressed;
- (BOOL)canBeClearedByNotificationCenter;
- (BOOL)canSnooze;
- (BOOL)isVIP;
- (BOOL)canCoalesceWithBulletin:(id)fp8;
- (BOOL)hasSamePersonAsBulletin:(id)fp8;
- (id)attachmentText;
- (id)attachmentImageForKey:(id)fp8;
- (id)iconImage;
- (id)description;
- (unsigned int)maxMessageLines;
- (id)subtitle;
- (id)publishDate;
- (id)date;
- (BOOL)hasEventDate;
- (id)title;
- (id)message;
- (id)bulletins;
- (id)sortDate;
- (BOOL)containsBulletinWithID:(id)fp8;
- (void)modifyBulletin:(id)fp8;
- (void)removeAllBulletins;
- (void)removeBulletin:(id)fp8;
- (void)addBulletin:(id)fp8;
- (void)_updateButtonLabels;
- (void)_updateMessage;
- (BOOL)_suppressesMessageForPrivacy;
- (void)_updateImage;
- (void)_updateDisplayDate;
- (void)_updateSortDate;
- (void)_updateActiveBulletin;
- (id)sortedBulletins;
- (void)_update;
- (id)bulletinWithID:(id)fp8;
- (void)dealloc;
- (id)initWithBulletin:(id)fp8 andObserver:(id)fp12;

@end

