/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBWorkStoreObserver-Protocol.h"

@class AppLaunchStats, NSMutableDictionary, NSObject<OS_dispatch_queue>, SBWorkStore;

@interface SBBackgroundMultitaskingManager : _ABAddressBookCopyLocalizedLabel <SBWorkStoreObserver>
{
    NSMutableDictionary *_appToBackgroundTasks;
    NSMutableDictionary *_backgroundFetchTaskValueToWatchdoggableCompletion;
    NSObject<OS_dispatch_queue> *_queue;
    SBWorkStore *_pendingWorkStore;
    AppLaunchStats *_appLaunchStats;
    double _watchdogTimeout;
}

+ (BOOL)shouldFakeAdoption;
+ (id)sharedInstance;
- (void)handlePushNotificationFromApplication:(id)fp8 userInfo:(id)fp12 priority:(int)fp16 completion:(id)fp(null);
- (id)_opportunisticallyUpdateApplications:(id)fp8 trigger:(unsigned int)fp12;
- (void)_performPendingWorkForBundleID:(id)fp8;
- (BOOL)_launchAppForUpdating:(id)fp8 trigger:(unsigned int)fp12 pushNotificationUserInfo:(id)fp16 withWatchdoggableCompletion:(id)fp(null);
- (void)_startBackgroundFetchTaskForApplication:(id)fp8 trigger:(unsigned int)fp12 sequenceNumber:(int)fp16 withWatchdoggableCompletion:(id)fp(null);
- (void)queue_startBackgroundFetchTaskForApplication:(id)fp8 trigger:(unsigned int)fp12 sequenceNumber:(int)fp16 withWatchdoggableCompletion:(id)fp(null);
- (void)_backgroundTaskFinished:(id)fp8 forApplication:(id)fp12;
- (void)queue_backgroundTaskFinished:(id)fp8 forApplication:(id)fp12;
- (void)_invalidateBackgroundTasksForApplication:(id)fp8;
- (void)queue_invalidateBackgroundTasksForApplication:(id)fp8;
- (void)_watchdogCompletionForBackgroundFetchTaskValue:(id)fp8;
- (void)queue_fireWatchdoggableCompletionForBackgroundFetchTaskValue:(id)fp8;
- (void)queue_bearTrap_AppWasSuspended:(id)fp8;
- (void)_appStateDidChange:(id)fp8;
- (void)_startBackgroundFetchForNotification:(id)fp8;
- (void)_appFinishedBackgroundUpdating:(id)fp8;
- (void)queue_appFinishedBackgroundUpdating:(id)fp8 userInfo:(id)fp12;
- (void)workDidChange:(id)fp8;
- (double)watchdogTimeout;
- (void)application:(id)fp8 didSetMinimumFetchInterval:(double)fp12;
- (int)nextSequenceNumber;
- (id)init;

@end

