/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class _UIBackdropView;

@interface SBBackdropContainerView : _ABAddressBookCopyLocalizedLabel
{
    _UIBackdropView *_backdropView;
}

- (void)setBackdropView:(id)fp8;
- (id)backdropView;
- (void)layoutSubviews;
- (void)_reallyInsertSubview:(id)fp8 atIndex:(int)fp12;
- (void)insertSubview:(id)fp8 atIndex:(int)fp12;
- (void)addSubview:(id)fp8;
- (id)contentView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

