/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView<SBUIBannerView>;

@interface SBBannerViewCallbackManager : _ABAddressBookCopyLocalizedLabel
{
    UIView<SBUIBannerView> *_view;
    id <SBUIBannerSource> _source;
    BOOL _sentWillAppear;
    BOOL _sentDidAppear;
    BOOL _sentWillDismiss;
    BOOL _sentDidDismiss;
    int _dismissReason;
}

- (void)matchPreviousCallbacks:(id)fp8;
- (BOOL)hasSentAnyCallbacks;
- (void)noteDidDismissWithReason:(int)fp8;
- (void)noteWillDismissWithReason:(int)fp8;
- (void)noteDidAppear;
- (void)noteWillAppear;
- (void)dealloc;
- (id)init;
- (id)initWithBannerView:(id)fp8;

@end

