/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class BKSProcessAssertion, NSString;

@interface SBBackgroundFetchTask : _ABAddressBookCopyLocalizedLabel
{
    BKSProcessAssertion *_assertion;
    id _completionHandler;
    NSString *_bundleID;
    unsigned int _trigger;
    int _sequenceNumber;
}

- (int)sequenceNumber;
- (unsigned int)trigger;
- (id)bundleID;
- (void)setCompletionHandler:(id)fp(null);
- (id)completionHandler;
- (void)setAssertion:(id)fp8;
- (id)assertion;
- (id)description;
- (void)dealloc;
- (void)_fireCompletionHandlerWithResult:(unsigned int)fp8;
- (void)finishWithResult:(unsigned int)fp8;
- (id)initForApplication:(id)fp8 trigger:(unsigned int)fp12 sequenceNumber:(int)fp16 withCompletion:(id)fp(null);

@end

