/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableSet, NSTimer;

@interface SBBacklightController : _ABAddressBookCopyLocalizedLabel
{
    double _minimumLockIdleTime;
    NSTimer *_autoLockTimer;
    double _lastTimeIdleCausedDim;
    double _nextLockDurationAfterDim;
    unsigned int _disableAutoDimming:1;
    unsigned int _lockScreenCameraWantsIdleTimerDisabled:1;
    NSMutableSet *_idleTimerDisabledReasons;
    NSMutableSet *_spuriousScreenUndimmingAssertions;
    BOOL _isPendingScreenUnblankAfterCACommit;
    BOOL _undimmedForBulletinSinceLastUserEvent;
}

+ (BOOL)deviceSupportsBacklightRamping;
+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNeeded:(BOOL)fp8;
- (BOOL)isPendingScreenUnblankAfterCACommit;
- (void)preventIdleSleepForNumberOfSeconds:(float)fp8;
- (void)preventIdleSleep;
- (void)allowIdleSleep;
- (void)_requestedUserEventNotificationOccurred;
- (void)_userEventPresenceTimerExpired;
- (void)_userEventOccurred;
- (void)_userEventsDidIdle;
- (void)_lockScreenDimTimerFired;
- (void)_didIdle;
- (void)_autoLockTimerFired:(id)fp8;
- (void)_startFadeOutAnimationIfNecessary;
- (BOOL)_lockScreenWantsUserEventNotifications;
- (void)removeSpuriousScreenUndimmingAssertion:(id)fp8;
- (void)addSpuriousScreenUndimmingAssertion:(id)fp8;
- (void)autoLockPrefsChanged;
- (void)animateBacklightToFactor:(float)fp8 duration:(double)fp12 source:(int)fp20 completion:(id)fp(null);
- (void)setBacklightFactor:(float)fp8 source:(int)fp12;
- (void)setBacklightFactorPending:(float)fp8;
- (id)idleTimerDisabledReasons;
- (BOOL)screenIsOff;
- (void)_deferredScreenUnblankDone;
- (void)turnOnScreenFullyWithBacklightSource:(int)fp8;
- (void)setIdleTimerDisabled:(BOOL)fp8 forReason:(id)fp12;
- (void)setIdleTimerDisabled:(BOOL)fp8;
- (double)defaultLockScreenDimIntervalWhenNotificationsPresent;
- (double)defaultLockScreenDimInterval;
- (void)_resetLockScreenIdleTimerWithDuration:(double)fp8 mode:(int)fp16;
- (void)resetLockScreenIdleTimerWithDuration:(double)fp8;
- (void)resetLockScreenIdleTimer;
- (void)cancelLockScreenIdleTimer;
- (double)_currentLockScreenIdleTimerInterval;
- (void)_resetIdleTimerAndUndim:(BOOL)fp8 source:(int)fp12;
- (void)resetIdleTimerAndUndimForBulletin;
- (void)resetIdleTimerAndUndim:(BOOL)fp8;
- (void)_undimFromSource:(int)fp8;
- (double)_nextLockTimeDuration;
- (double)_nextIdleTimeDuration;
- (void)clearIdleTimer;
- (void)restoreBacklightFactorForProx;
- (void)setBacklightFactorToZeroForProx;
- (void)_cancelSetBacklightFactorToZeroAfterDelay;
- (void)_setBacklightFactorToZeroForProx;
- (void)_clearAutoLockTimer;
- (id)init;

@end

