/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBBBItemInfo : _ABAddressBookCopyLocalizedLabel
{
    id _representedObject;
}

+ (id)infoWithRepresentedObject:(id)fp8;
- (id)representedObject;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (void)invalidateCachedLayoutData;
- (float)heightForReusableViewInTableView:(id)fp8;
- (void)populateReusableView:(id)fp8;
- (Class)reusableViewClass;
- (id)identifier;
- (void)dealloc;
- (id)initWithRepresentedObject:(id)fp8;

@end

