/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBBBBulletinInfo, SBBBSectionInfo;

@interface SBBBInfoOperand : _ABAddressBookCopyLocalizedLabel
{
    SBBBSectionInfo *_section;
    SBBBBulletinInfo *_bulletin;
}

+ (id)operandWithSection:(id)fp8 bulletin:(id)fp12;
- (id)bulletin;
- (id)section;
- (id)description;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (BOOL)isSectionOperand;
- (void)dealloc;
- (id)initWithSection:(id)fp8 bulletin:(id)fp12;

@end

