/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBBSectionInfo.h"

@class SBBBWidgetBulletinInfo;

@interface SBBBWidgetSectionInfo : SBBBSectionInfo
{
    SBBBWidgetBulletinInfo *_widgetBulletinInfo;
}

- (void)setWidgetBulletinInfo:(id)fp8;
- (id)widgetBulletinInfo;
- (BOOL)isWidgetSection;
- (id)identifier;
- (void)dealloc;

@end

