/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBBBInfoOperation : _ABAddressBookCopyLocalizedLabel
{
    id _operand;
}

+ (id)operationWithOperand:(id)fp8;
- (id)operand;
- (id)description;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (void)dealloc;
- (id)initWithOperand:(id)fp8;

@end

