/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBBounceSettings : _ABAddressBookCopyLocalizedLabel
{
    BOOL _resistanceAppliesAfterBounce;
    float _gravity;
    float _velocity;
    float _elasticity;
    float _friction;
    float _resistance;
    float _multiplier;
    float _minVelocityToAssist;
    float _maxVelocityToAssist;
    float _maxVelocityAssistance;
}

- (void)setMaxVelocityAssistance:(float)fp8;
- (float)maxVelocityAssistance;
- (void)setMaxVelocityToAssist:(float)fp8;
- (float)maxVelocityToAssist;
- (void)setMinVelocityToAssist:(float)fp8;
- (float)minVelocityToAssist;
- (void)setMultiplier:(float)fp8;
- (float)multiplier;
- (void)setResistanceAppliesAfterBounce:(BOOL)fp8;
- (BOOL)resistanceAppliesAfterBounce;
- (void)setResistance:(float)fp8;
- (float)resistance;
- (void)setFriction:(float)fp8;
- (float)friction;
- (void)setElasticity:(float)fp8;
- (float)elasticity;
- (void)setVelocity:(float)fp8;
- (float)velocity;
- (void)setGravity:(float)fp8;
- (float)gravity;
- (void)setDefaultValues;

@end

