/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@class SBBookmark;

@interface SBBookmarkIcon : SBLeafIcon
{
    SBBookmark *_bookmark;
}

- (void)setBookmark:(id)fp8;
- (id)bookmark;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)webClip;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithBookmark:(id)fp8;

@end

