/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "_UIDynamicReferenceSystem-Protocol.h"

@interface SBBouncingSystem : _ABAddressBookCopyLocalizedLabel <_UIDynamicReferenceSystem>
{
    struct CGRect _bounds;
}

- (void)setBounds:(struct CGRect)fp8;
- (struct CGRect)bounds;

@end

