/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBApplicationRestrictionObserver-Protocol.h"

@class BBSystemStateProvider;

@interface SBBulletinSystemStateAdapter : _ABAddressBookCopyLocalizedLabel <SBApplicationRestrictionObserver>
{
    BBSystemStateProvider *_stateProvider;
    BOOL _quietModeEnabled;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
- (void)applicationRestrictionController:(id)fp8 didUpdateVisibleTags:(id)fp12 hiddenTags:(id)fp16;
- (void)_lostModeStateChanged;
- (void)_screenDimmed:(id)fp8;
- (void)_lockStateChanged:(id)fp8;
- (void)dealloc;
- (id)init;

@end

