/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBBulletinBusyClient-Protocol.h"

@class BBObserver, NSMutableArray, NSMutableDictionary;

@interface SBBulletinSoundController : _ABAddressBookCopyLocalizedLabel <BBObserverDelegate, SBBulletinBusyClient>
{
    BBObserver *_observer;
    NSMutableArray *_blockQueue;
    NSMutableDictionary *_playingSounds;
    BOOL _deviceIsLocked;
    BOOL _quietModeEnabled;
    unsigned int _quietModeState;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)fp8;
- (void)bulletinWindowStoppedBeingBusy;
- (void)observer:(id)fp8 noteServerConnectionStateChanged:(BOOL)fp12;
- (void)observer:(id)fp8 noteInvalidatedBulletinIDs:(id)fp12;
- (void)observer:(id)fp8 noteAlertBehaviorOverrideStateChanged:(unsigned int)fp12;
- (void)observer:(id)fp8 noteAlertBehaviorOverridesChanged:(unsigned int)fp12;
- (void)observer:(id)fp8 removeBulletin:(id)fp12;
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (void)_enqueueBlock:(id)fp(null) forBulletin:(void)fp8;
- (BOOL)_shouldHonorPlaySoundRequestForBulletin:(id)fp8;
- (void)_hardwareButtonPressed:(id)fp8;
- (unsigned int)quietModeState;
- (BOOL)quietModeEnabled;
- (void)killSounds;
- (void)killSoundForBulletin:(id)fp8;
- (BOOL)playSoundForBulletin:(id)fp8;
- (void)dealloc;
- (id)init;

@end

