/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBBulletinAlertHandler-Protocol.h"
#import "SBBulletinBusyClient-Protocol.h"

@class BBObserver, NSMapTable, NSMutableArray, NSMutableDictionary;

@interface SBBulletinModalController : _ABAddressBookCopyLocalizedLabel <BBObserverDelegate, SBBulletinAlertHandler, SBBulletinBusyClient>
{
    BBObserver *_observer;
    BOOL _deviceIsLocked;
    NSMutableArray *_incomingBulletinEventQueue;
    NSMutableDictionary *_handlersBySectionID;
    NSMapTable *_handlersByBulletinID;
    NSMapTable *_alertsByBulletinID;
    BOOL _quietModeEnabled;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)fp8;
- (void)_syncDismissalForBulletin:(id)fp8;
- (void)handleEvent:(int)fp8 withBulletin:(id)fp12 forRegistry:(id)fp16;
- (BOOL)bindBulletin:(id)fp8 forRegistry:(id)fp12;
- (void)bulletinWindowStoppedBeingBusy;
- (void)observer:(id)fp8 noteServerConnectionStateChanged:(BOOL)fp12;
- (void)observer:(id)fp8 noteAlertBehaviorOverridesChanged:(unsigned int)fp12;
- (id)observer:(id)fp8 composedAttachmentImageForType:(int)fp12 thumbnailData:(id)fp16 key:(id)fp20;
- (id)observer:(id)fp8 thumbnailSizeConstraintsForAttachmentType:(int)fp12;
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)fp8;
- (void)observer:(id)fp8 noteServerReceivedResponseForBulletin:(id)fp12;
- (void)observer:(id)fp8 noteInvalidatedBulletinIDs:(id)fp12;
- (void)observer:(id)fp8 purgeReferencesToBulletinID:(id)fp12;
- (void)observer:(id)fp8 removeBulletin:(id)fp12;
- (void)observer:(id)fp8 modifyBulletin:(id)fp12;
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (void)_executeOrPendEventBlock:(id)fp(null) forBulletin:(void)fp8;
- (void)_dequeuePendedEventsIfPossible;
- (id)attachmentImageForBulletin:(id)fp8;
- (id)init;
- (void)destroyingAlert:(id)fp8 withBulletin:(id)fp12;

@end

