/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "_SBFVibrantView-Protocol.h"

@class SBLegibilityView, UIView, _SBFVibrantSettings;

@interface SBCameraGrabberView : _ABAddressBookCopyLocalizedLabel <_SBFVibrantView>
{
    struct UIEdgeInsets _hitTestEdgeInsets;
    UIView *_colorCompositingView;
    UIView *_darkTintView;
    UIView *_lightTintView;
    UIView *_backgroundView;
    SBLegibilityView *_legibilityView;
    _SBFVibrantSettings *_vibrantSettings;
    id <SBResponderTouchDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)vibrantSettings;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)updateForChangedSettings:(id)fp8;
- (void)setStrength:(float)fp8;
- (id)_lazyLegibilityView;
- (void)setBackgroundView:(id)fp8;
- (void)setVibrantSettings:(id)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)_cameraGrabberImage;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

