/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBCarDisplaySettings : _ABAddressBookCopyLocalizedLabel
{
    int _lockOutMode;
    int _lockOutAnimationType;
}

+ (id)settingsControllerModule;
- (void)setLockOutAnimationType:(int)fp8;
- (int)lockOutAnimationType;
- (void)setLockOutMode:(int)fp8;
- (int)lockOutMode;
- (void)setDefaultValues;

@end

