/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBControlCenterSectionViewController.h"

#import "MPAudioVideoRoutingViewControllerDelegate-Protocol.h"
#import "SFAirDropDiscoveryActionSheetDelegate-Protocol.h"
#import "SFAirDropDiscoveryControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class BKSTimer, MPAudioVideoRoutingActionSheet, MPAudioVideoRoutingPopoverController, MPAudioVideoRoutingViewController, SBCCButtonLikeSectionView, SFAirDropDiscoveryController;

@interface SBCCAirStuffSectionController : SBControlCenterSectionViewController <MPAudioVideoRoutingViewControllerDelegate, UIPopoverControllerDelegate, SFAirDropDiscoveryControllerDelegate, SFAirDropDiscoveryActionSheetDelegate, UIActionSheetDelegate>
{
    SBCCButtonLikeSectionView *_airPlaySection;
    SBCCButtonLikeSectionView *_airDropSection;
    MPAudioVideoRoutingActionSheet *_airPlayActionSheet;
    MPAudioVideoRoutingViewController *_airPlayViewController;
    MPAudioVideoRoutingPopoverController *_airPlayPopoverController;
    SFAirDropDiscoveryController *_airDropDiscoveryController;
    BOOL _isVisible;
    BOOL _airPlayWasPreviouslyEnabled;
    BKSTimer *_resetTimer;
    BOOL _airPlayEnabled;
    BOOL _airDropEnabled;
}

+ (Class)viewClass;
- (BOOL)airDropEnabled;
- (BOOL)airPlayEnabled;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)discoveryController:(id)fp8 actionSheetDidDismiss:(id)fp12;
- (void)discoveryController:(id)fp8 actionSheetWillDismiss:(id)fp12;
- (void)discoveryControllerVisibilityDidChange:(id)fp8;
- (void)discoveryControllerSettingsDidChange:(id)fp8;
- (void)viewControllerRequestsDismissal:(id)fp8;
- (void)_dismissAirplayControllerAnimated:(BOOL)fp8;
- (void)_debugAirplaneStateDidChangeNotification:(id)fp8;
- (void)_debugWifiStateDidChangeNotification:(id)fp8;
- (void)_availableRoutesDidChangeNotification:(id)fp8;
- (void)_updateAirDropControlAsEnabled:(BOOL)fp8;
- (void)_updateForAirDropStateChange;
- (void)_updateAirPlayControlAsEnabled:(BOOL)fp8;
- (void)_updateForAirPlayStateChange;
- (void)_airDropTapped:(id)fp8;
- (void)_airPlayTapped:(id)fp8;
- (void)_showAirPlayView:(id)fp8;
- (void)setAirDropEnabled:(BOOL)fp8;
- (void)setAirPlayEnabled:(BOOL)fp8;
- (void)_noteSectionEnabledStateDidChange;
- (void)_updateSubsectionVisibilityAnimated:(BOOL)fp8;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)viewDidLoad;
- (id)view;
- (BOOL)enabledForOrientation:(int)fp8;
- (struct CGSize)contentSizeForOrientation:(int)fp8;
- (id)sectionIdentifier;
- (void)dealloc;
- (id)init;

@end

