/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIControlCenterButtonDelegate-Protocol.h"

@class SBUIControlCenterButton, SBUIControlCenterLabel, UIView;

@interface SBCCButtonLikeSectionView : _ABAddressBookCopyLocalizedLabel <SBUIControlCenterButtonDelegate>
{
    UIView *_darken;
    SBUIControlCenterButton *_button;
    SBUIControlCenterLabel *_label;
}

- (void)button:(id)fp8 didChangeState:(int)fp12;
- (void)buttonTapped:(id)fp8;
- (void)setSelected:(BOOL)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setEnabled:(BOOL)fp8;
- (void)layoutSubviews;
- (void)setImage:(id)fp8;
- (void)setText:(id)fp8;
- (void)setNumberOfLines:(int)fp8;
- (void)setFont:(id)fp8;
- (id)font;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

