/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBControlCenterSectionView.h"

@class NSMutableArray;

@interface SBCCButtonLayoutView : SBControlCenterSectionView
{
    NSMutableArray *_buttons;
    float _interButtonPadding;
    struct UIEdgeInsets _contentEdgeInsets;
}

- (void)setContentEdgeInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)contentEdgeInsets;
- (void)setInterButtonPadding:(float)fp8;
- (float)interButtonPadding;
- (void)layoutSubviews;
- (id)buttons;
- (void)removeButton:(id)fp8;
- (void)addButton:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

