/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBControlCenterSectionViewController.h"

#import "MPUSystemMediaControlsDelegate-Protocol.h"

@class MPUSystemMediaControlsViewController;

@interface SBCCMediaControlsSectionController : SBControlCenterSectionViewController <MPUSystemMediaControlsDelegate>
{
    MPUSystemMediaControlsViewController *_systemMediaViewController;
}

- (void)systemMediaControlsViewController:(id)fp8 didReceiveTapOnControlType:(int)fp12;
- (void)viewDidLoad;
- (struct CGSize)contentSizeForOrientation:(int)fp8;
- (id)sectionIdentifier;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

