/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBControlCenterSectionViewController.h"

#import "SBUIControlCenterButtonDelegate-Protocol.h"

@class AVFlashlight, NSMutableArray, NSObject<OS_dispatch_queue>, SBControlCenterButton;

@interface SBCCQuickLaunchSectionController : SBControlCenterSectionViewController <SBUIControlCenterButtonDelegate>
{
    SBControlCenterButton *_torchButton;
    SBControlCenterButton *_clockButton;
    SBControlCenterButton *_calculatorButton;
    SBControlCenterButton *_cameraButton;
    NSMutableArray *_buttons;
    AVFlashlight *_flashlight;
    BOOL _ccVisible;
    NSObject<OS_dispatch_queue> *_flashlightQueue;
    BOOL _flashlightOn;
}

+ (Class)viewClass;
- (BOOL)isFlashlightOn;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)_featureLockStateDidChangeNotification:(id)fp8;
- (void)_deviceBlockStateDidChangeNotification:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)_updateTorchButtonState;
- (void)_enableTorch:(BOOL)fp8;
- (void)buttonTapped:(id)fp8;
- (void)_activateAppWithBundleId:(id)fp8 url:(id)fp12;
- (id)_urlForButton:(id)fp8;
- (id)_bundleIDForButton:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)setFlashlightOn:(BOOL)fp8;
- (void)_updateFlashlightPowerState;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)noteSettingsDidUpdate:(id)fp8;
- (id)view;
- (struct CGSize)contentSizeForOrientation:(int)fp8;
- (id)sectionIdentifier;
- (void)dealloc;
- (id)init;

@end

