/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBControlCenterSectionViewController.h"

#import "RadiosPreferencesDelegate-Protocol.h"
#import "SBUIControlCenterButtonDelegate-Protocol.h"

@class BBSettingsGateway, BluetoothManager, NSMutableDictionary, RadiosPreferences;

@interface SBCCSettingsSectionController : SBControlCenterSectionViewController <SBUIControlCenterButtonDelegate, RadiosPreferencesDelegate>
{
    NSMutableDictionary *_buttonsByID;
    char _settingSupported[6];
    RadiosPreferences *_airplaneModeController;
    struct __WiFiManagerClient *_wifiManager;
    struct __WiFiDeviceClient *_wifiDevice;
    BBSettingsGateway *_settingsGateway;
    BOOL _dndEnabled;
    int _dndStatus;
    BluetoothManager *_btManager;
}

+ (Class)viewClass;
- (void)_updateOrientationLockButtonState;
- (BOOL)_getOrientationLocked;
- (void)_setOrientationLocked:(BOOL)fp8;
- (void)_tearDownOrientationLock;
- (void)_initOrientationLock;
- (void)_updateMuteButtonState;
- (BOOL)_getMuted;
- (void)_setMuted:(BOOL)fp8;
- (void)_tearDownMute;
- (void)_initMute;
- (BOOL)_getDND;
- (void)_setDNDEnabled:(BOOL)fp8 updateServer:(BOOL)fp12;
- (void)_setDNDStatus:(int)fp8;
- (void)_tearDownDND;
- (void)_initDND;
- (void)_updateBluetoothState;
- (BOOL)_getBluetooth;
- (void)_setBluetoothEnabled:(BOOL)fp8;
- (void)_tearDownBluetooth;
- (void)_initBluetooth;
- (void)_updateWifiButtonState;
- (BOOL)_getWifi;
- (void)_setWifiEnabled:(BOOL)fp8;
- (void)_tearDownWifi;
- (void)_initWifi;
- (void)airplaneModeChanged;
- (BOOL)_getAirplaneMode;
- (void)_setAirplaneModeEnabled:(BOOL)fp8;
- (void)_tearDownAirplaneMode;
- (void)_initAirplaneMode;
- (void)buttonTapped:(id)fp8;
- (id)_buttonForSetting:(int)fp8;
- (void)_addButtonForSetting:(int)fp8;
- (id)_identifierForSetting:(int)fp8;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)noteSettingsDidUpdate:(id)fp8;
- (id)view;
- (struct CGSize)contentSizeForOrientation:(int)fp8;
- (id)sectionIdentifier;
- (void)dealloc;
- (id)init;

@end

