/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconZoomSettings.h"

@interface SBCenterZoomSettings : SBIconZoomSettings
{
    float _centerRowCoordinate;
    int _distanceEffect;
    float _firstHopIncrement;
    float _hopIncrementAcceleration;
    float _dockMass;
}

+ (id)settingsControllerModule;
- (void)setDockMass:(float)fp8;
- (float)dockMass;
- (void)setHopIncrementAcceleration:(float)fp8;
- (float)hopIncrementAcceleration;
- (void)setFirstHopIncrement:(float)fp8;
- (float)firstHopIncrement;
- (void)setDistanceEffect:(int)fp8;
- (int)distanceEffect;
- (void)setCenterRowCoordinate:(float)fp8;
- (float)centerRowCoordinate;
- (void)setDefaultValues;

@end

