/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBCenterIconZoomAnimator.h"

@class UIView;

@interface SBCenterAppIconZoomAnimator : SBCenterIconZoomAnimator
{
    UIView *_appView;
    float _distantScale;
}

- (void)setDistantScale:(float)fp8;
- (float)distantScale;
- (void)_fadeAppForZoomFraction:(float)fp8;
- (void)_zoomAppForZoomFraction:(float)fp8;
- (double)_appZoomDelay;
- (double)_iconZoomDelay;
- (void)_animateToFraction:(float)fp8 afterDelay:(double)fp12 withSharedCompletion:(id)fp(null);
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)fp8;
- (void)_prepareAnimation;
- (void)_delayedForRotation;
- (void)dealloc;
- (id)initWithFolderController:(id)fp8 appView:(id)fp12;

@end

