/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "_SBFVibrantView-Protocol.h"

@class UIColor, UIView, _SBFVibrantSettings;

@interface SBChevronView : _ABAddressBookCopyLocalizedLabel <_SBFVibrantView>
{
    UIView *_leftGrabberView;
    UIView *_rightGrabberView;
    double _animationDuration;
    int _state;
    UIColor *_color;
    _SBFVibrantSettings *_vibrantSettings;
    UIView *_colorCompositingView;
    UIView *_darkTintView;
    UIView *_lightTintView;
    UIView *_backgroundView;
    UIView *_alphaContainerView;
}

- (int)state;
- (id)vibrantSettings;
- (id)color;
- (void)setBackgroundView:(id)fp8;
- (void)setVibrantSettings:(id)fp8;
- (id)description;
- (void)setState:(int)fp8;
- (void)setState:(int)fp8 animated:(BOOL)fp12;
- (BOOL)_setState:(int)fp8;
- (void)layoutSubviews;
- (void)_layoutGrabberView:(id)fp8 forState:(int)fp12;
- (struct CGRect)_frameForGrabberView:(id)fp8 forState:(int)fp12;
- (struct CGAffineTransform)_transformForGrabberView:(id)fp8 forState:(int)fp12;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setColor:(id)fp8;
- (void)setAnimationDuration:(double)fp8;
- (double)animationDuration;
- (void)dealloc;
- (id)initWithColor:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

