/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBIconBlurryBackgroundView, SBIconColorSettings, UIImageView, UIView;

@interface SBCloseBoxView : _ABAddressBookCopyLocalizedLabel
{
    SBIconBlurryBackgroundView *_backgroundView;
    UIView *_whiteTintView;
    UIImageView *_xColorBurnView;
    UIImageView *_xPlusDView;
    SBIconColorSettings *_colorSettings;
    struct CGPoint _wallpaperRelativeCenter;
}

- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setSuppressesBlurryBackgroundChanges:(BOOL)fp8;
- (void)setLegibilityStyle:(int)fp8;
- (void)setWallpaperRelativeCenter:(struct CGPoint)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

