/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIControlCenterControl-Protocol.h"

@interface SBControlCenterKnockoutView : _ABAddressBookCopyLocalizedLabel <SBUIControlCenterControl>
{
}

- (void)controlConfigurationDidChangeForState:(int)fp8;
- (void)controlAppearanceDidChangeForState:(int)fp8;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

