/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBControlCenterViewControllerDelegate-Protocol.h"

@class NSHashTable, NSMutableSet, SBApplication, SBChevronView, SBControlCenterRootView, SBControlCenterViewController, SBControlCenterWindow, UIView, _UIBackdropView;

@interface SBControlCenterController : _ABAddressBookCopyLocalizedLabel <SBControlCenterViewControllerDelegate>
{
    SBControlCenterWindow *_window;
    SBControlCenterRootView *_rootView;
    SBControlCenterViewController *_viewController;
    UIView *_fullScreenGrabberContainer;
    _UIBackdropView *_fullScreenGrabberBackdrop;
    SBChevronView *_fullScreenChevron;
    NSMutableSet *_preventDismissalOnLockReasons;
    BOOL _uiLocked;
    NSHashTable *_observers;
    int _orientation;
    BOOL _animatingInitialPresentation;
    BOOL _gotFirstBackdropUpdate;
    BOOL _inGrabberOnlyMode;
    BOOL _presented;
    BOOL _transitioning;
    BOOL _fullyRevealed;
    SBApplication *_coveredApplication;
}

+ (void)notifyControlCenterControl:(id)fp8 didActivate:(BOOL)fp12;
+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreatingIfNeeded:(BOOL)fp8;
- (void)setFullyRevealed:(BOOL)fp8;
- (BOOL)isFullyRevealed;
- (BOOL)isTransitioning;
- (BOOL)isPresented;
- (id)coveredApplication;
- (void)setInGrabberOnlyMode:(BOOL)fp8;
- (BOOL)inGrabberOnlyMode;
- (BOOL)isUILocked;
- (void)controlCenterViewController:(id)fp8 backdropViewDidUpdate:(id)fp12;
- (void)controlCenterViewController:(id)fp8 handlePan:(id)fp12;
- (void)controlCenterViewController:(id)fp8 handleTap:(id)fp12;
- (BOOL)controlCenterViewController:(id)fp8 canHandleGestureRecognizer:(id)fp12;
- (void)controlCenterViewControllerWantsDismissal:(id)fp8;
- (void)_finishPresenting:(BOOL)fp8 completion:(id)fp(null);
- (void)_dismissWithDuration:(double)fp8 additionalAnimations:(id)fp(null) completion:(void)fp16;
- (void)dismissAnimated:(BOOL)fp8 withAdditionalAnimations:(id)fp(null) completion:(void)fp12;
- (void)dismissAnimated:(BOOL)fp8 completion:(id)fp(null);
- (void)dismissAnimated:(BOOL)fp8;
- (void)_presentWithDuration:(double)fp8 completion:(id)fp(null);
- (void)presentAnimated:(BOOL)fp8;
- (void)presentAnimated:(BOOL)fp8 completion:(id)fp(null);
- (void)hideGrabberAnimated:(BOOL)fp8 completion:(id)fp(null);
- (void)hideGrabberAnimated:(BOOL)fp8;
- (void)showGrabberAnimated:(BOOL)fp8;
- (void)cancelTransition;
- (void)endTransitionWithVelocity:(struct CGPoint)fp8 completion:(id)fp(null);
- (id)_createDynamicAnimationForShow:(BOOL)fp8 currentValue:(double)fp12 velocity:(double)fp20 unitSize:(double)fp28;
- (void)updateTransitionWithTouchLocation:(struct CGPoint)fp8 velocity:(struct CGPoint)fp16;
- (void)beginTransitionWithTouchLocation:(struct CGPoint)fp8;
- (void)_endPresentation;
- (void)_beginPresentation;
- (BOOL)allowHideTransition;
- (BOOL)allowShowTransition;
- (BOOL)_allowsShowTransition;
- (void)_setNCGrabberHidden:(BOOL)fp8;
- (void)_updateGrabberVisibility;
- (void)_updateRevealPercentage:(float)fp8;
- (void)_revealSlidingViewToHeight:(float)fp8;
- (float)_controlCenterHeightForTouchLocation:(struct CGPoint)fp8;
- (float)_yValueForClosed;
- (float)_yValueForOpen;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)wantsFullScreenLayout;
- (id)_window;
- (void)preventDismissalOnLock:(BOOL)fp8 forReason:(id)fp12;
- (void)_dismissOnLock;
- (void)_uiRelockedNotification:(id)fp8;
- (void)_lockStateChangedNotification:(id)fp8;
- (BOOL)isGrabberVisible;
- (BOOL)isVisible;
- (void)loadView;
- (BOOL)handleMenuButtonTap;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)_enumerateObservers:(id)fp(null);
- (void)setCoveredApplication:(id)fp8;
- (void)setUILocked:(BOOL)fp8;
- (BOOL)isAvailableWhileLocked;
- (void)setTransitioning:(BOOL)fp8;
- (void)setPresented:(BOOL)fp8;
- (void)dealloc;
- (id)init;

@end

