/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSNumber, NSString;

@interface SBControlCenterButton : _ABAddressBookCopyLocalizedLabel
{
    NSString *_identifier;
    NSNumber *_sortKey;
}

- (void)setSortKey:(id)fp8;
- (id)sortKey;
- (void)setIdentifier:(id)fp8;
- (id)identifier;
- (void)dealloc;

@end

