/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBControlCenterSectionViewControllerDelegate <NSObject>
- (void)sectionWantsControlCenterDismissal:(id)fp8;
- (void)section:(id)fp8 updateStatusText:(id)fp12 reason:(id)fp16;
- (void)noteSectionEnabledStateDidChange:(id)fp8;
@end

