/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBControlCenterObserver-Protocol.h"

@class SBChevronView, SBControlCenterContentContainerView, UIView;

@interface SBControlCenterContainerView : _ABAddressBookCopyLocalizedLabel <SBControlCenterObserver>
{
    UIView *_darkeningView;
    float _revealPercentage;
    SBChevronView *_chevronToTrack;
    SBControlCenterContentContainerView *_contentContainerView;
}

- (id)contentContainerView;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillFinishTransitionOpen:(BOOL)fp8 withDuration:(double)fp12;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)updateBackgroundSettings:(id)fp8;
- (void)setRevealPercentage:(float)fp8;
- (float)revealPercentage;
- (id)_contentChevronView;
- (id)_currentBGColor;
- (void)_updateContentFrame;
- (void)_updateDarkeningFrame;
- (void)trackChevronView:(id)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

