/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBConferenceManager : _ABAddressBookCopyLocalizedLabel
{
    BOOL _hasFaceTimeCapability;
    struct MGNotificationTokenStruct *_faceTimeCapabilityUpdateToken;
}

+ (void)initialize;
+ (id)sharedInstance;
- (void)_faceTimeAppActivationStateChanged:(id)fp8;
- (void)_updateStatusBar;
- (void)updateStatusBar;
- (void)_faceTimeCapabilityChanged:(id)fp8;
- (id)currentCallStatusDisplayString;
- (id)currentCallRemoteUserId;
- (void)endFaceTime;
- (void)_faceTimeStateChanged:(id)fp8;
- (void)invitedToIMAVChat:(id)fp8;
- (void)dealloc;
- (BOOL)canStartFaceTime;
- (BOOL)inFaceTime;
- (BOOL)activeFaceTimeCallExists;
- (BOOL)faceTimeInvitationExists;
- (BOOL)faceTimeIsAvailable;
- (BOOL)hasFaceTimeCapability;
- (id)_faceTimeApp;
- (id)init;

@end

