/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBScaleZoomSettings.h"

@class SBFAnimationSettings;

@interface SBCrossfadeZoomSettings : SBScaleZoomSettings
{
    BOOL _morphWithZoom;
    SBFAnimationSettings *_morphSettings;
}

+ (id)settingsControllerModule;
- (void)setMorphSettings:(id)fp8;
- (id)morphSettings;
- (void)setMorphWithZoom:(BOOL)fp8;
- (BOOL)morphWithZoom;
- (id)effectiveMorphAnimationSettings;
- (void)setDefaultValues;

@end

