/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBScaleIconZoomAnimator.h"

@class UIView;

@interface SBCrossfadeIconZoomAnimator : SBScaleIconZoomAnimator
{
    UIView *_crossfadeView;
    BOOL _performsTrueCrossfade;
    BOOL _masksCorners;
}

- (void)setMasksCorners:(BOOL)fp8;
- (BOOL)masksCorners;
- (void)setPerformsTrueCrossfade:(BOOL)fp8;
- (BOOL)performsTrueCrossfade;
- (struct CGPoint)_zoomedIconCenter;
- (struct CGRect)_zoomedFrame;
- (void)_animateToFraction:(float)fp8 afterDelay:(double)fp12 withSharedCompletion:(id)fp(null);
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)fp8;
- (void)_prepareAnimation;
- (void)_delayedForRotation;
- (void)dealloc;
- (id)initWithFolderController:(id)fp8 crossfadeView:(id)fp12 icon:(id)fp16;
- (void)_assertCrossfadeViewSizeIfNecessary;

@end

