/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImage;

@interface SBDarkeningImageView : _ABAddressBookCopyLocalizedLabel
{
    UIImage *_baseImage;
    float _brightness;
    id <SBDarkeningImageViewDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)description;
- (void)setImage:(id)fp8 brightness:(float)fp12;
- (void)setBrightness:(float)fp8;
- (float)brightness;
- (void)setImage:(id)fp8;
- (id)image;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

