/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBFLockScreenDateFormatter-Protocol.h"

@class NSDate, NSDateFormatter, NSNumberFormatter;

@interface SBDateLabelStringFormatCache : _ABAddressBookCopyLocalizedLabel <SBFLockScreenDateFormatter>
{
    NSDateFormatter *_dayOfWeekFormatter;
    NSDateFormatter *_dayOfWeekWithTimeFormatter;
    NSDateFormatter *_dayMonthYearFormatter;
    NSDateFormatter *_shortDayMonthFormatter;
    NSDateFormatter *_shortDayMonthTimeFormatter;
    NSDateFormatter *_abbrevDayMonthFormatter;
    NSDateFormatter *_abbrevDayMonthTimeFormatter;
    NSDateFormatter *_timeFormatter;
    NSDateFormatter *_relativeDateTimeFormatter;
    NSDateFormatter *_relativeDateFormatter;
    NSDateFormatter *_dayOfWeekMonthDayFormatter;
    NSDateFormatter *_timeNoAMPMFormatter;
    NSNumberFormatter *_decimalFormatter;
    NSNumberFormatter *_timerNumberFormatter;
    NSDateFormatter *_abbreviatedTimerFormatter;
    NSDateFormatter *_alarmSnoozeFormatter;
    NSDate *_timerReferenceDate;
    NSDate *_alarmReferenceDate;
}

+ (id)sharedInstance;
+ (void)load;
- (id)formatAlarmSnoozeDuration:(double)fp8;
- (id)formatAbbreviatedTimerDuration:(double)fp8;
- (id)formatTimerDuration:(double)fp8;
- (id)formatDateAsRelativeDateStyle:(id)fp8;
- (BOOL)_shouldShowHoursForTimerDuration:(double)fp8;
- (id)formatDateAsTimeNoAMPM:(id)fp8;
- (id)formatDateAsDayOfWeekMonthDayStyle:(id)fp8;
- (id)formatDateAsRelativeDateAndTimeStyle:(id)fp8;
- (id)formatDateAsTimeStyle:(id)fp8;
- (id)formatDateAsAbbreviatedDayMonthWithTimeStyle:(id)fp8;
- (id)formatDateAsAbbreviatedDayMonthStyle:(id)fp8;
- (id)formatDateAsShortDayMonthWithTimeStyle:(id)fp8;
- (id)formatDateAsDayMonthYearStyle:(id)fp8;
- (id)formatDateAsAbbreviatedDayOfWeekWithTime:(id)fp8;
- (id)formatDateAsDayOfWeek:(id)fp8;
- (id)formatNumberAsDecimal:(id)fp8;
- (void)resetFormatters:(id)fp8;
- (void)resetFormattersIfNecessary;
- (void)dealloc;
- (id)init;

@end

