/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSAttributedString, UIImage;

@interface SBDefaultBannerTextView : _ABAddressBookCopyLocalizedLabel
{
    NSAttributedString *_primaryTextAttributedString;
    NSAttributedString *_primaryTextAttributedStringComponent;
    UIImage *_primaryTextAccessoryImageComponent;
    NSAttributedString *_secondaryTextAttributedString;
    BOOL _secondaryTextItalicized;
    NSAttributedString *_relevanceDateAttributedString;
}

- (void)drawRect:(struct CGRect)fp8;
- (id)_primaryTextAttributedString;
- (void)_invalidatePrimaryTextAttributedString;
- (BOOL)textWillWrapForWidth:(float)fp8;
- (void)setRelevanceDateText:(id)fp8;
- (id)relevanceDateText;
- (void)setSecondaryText:(id)fp8 italicized:(BOOL)fp12;
- (void)setSecondaryText:(id)fp8;
- (id)secondaryText;
- (void)setPrimaryTextAccessoryImage:(id)fp8;
- (id)primaryTextAccessoryImage;
- (void)setPrimaryText:(id)fp8;
- (id)primaryText;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

