/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBWallpaperObserver-Protocol.h"

@class SBDockIconListView, SBHighlightView, UIImageView, _SBDockBackgroundView;

@interface SBDockView : _ABAddressBookCopyLocalizedLabel <SBWallpaperObserver>
{
    SBDockIconListView *_iconListView;
    SBHighlightView *_highlightView;
    _SBDockBackgroundView *_backgroundView;
    UIImageView *_backgroundImageView;
}

+ (float)defaultHeight;
- (void)wallpaperDidChangeForVariant:(int)fp8;
- (id)_newBackgroundImage;
- (void)setVerticalBackgroundStretch:(float)fp8;
- (void)setBackgroundAlpha:(float)fp8;
- (float)heightForOrientation:(int)fp8;
- (void)layoutSubviews;
- (id)dockListView;
- (void)dealloc;
- (id)initWithDockListView:(id)fp8 forSnapshot:(BOOL)fp12;

@end

