/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRootIconListView.h"

@interface SBDockIconListView : SBRootIconListView
{
}

+ (unsigned int)iconRowsForInterfaceOrientation:(int)fp8;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)fp8;
+ (float)defaultHeight;
- (unsigned int)columnAtPoint:(struct CGPoint)fp8;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)fp8;
- (float)_additionalSideInsetToCenterIcons;
- (unsigned int)rowAtPoint:(struct CGPoint)fp8;
- (id)iconAtPoint:(struct CGPoint)fp8 index:(unsigned int *)fp16 proposedOrder:(int *)fp20 grabbedIcon:(id)fp24;
- (float)sideIconInset;
- (float)topIconInset;
- (unsigned int)iconsInRowForSpacingCalculation;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (int)iconLocation;
- (id)initWithModel:(id)fp8 orientation:(int)fp12 viewMap:(id)fp16;

@end

