/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBFAnimationSettings;

@interface SBFadeAnimationSettings : _ABAddressBookCopyLocalizedLabel
{
    float _backlightFadeDuration;
    SBFAnimationSettings *_dateInSettings;
    SBFAnimationSettings *_overlayInSettings;
    SBFAnimationSettings *_contentInSettings;
    SBFAnimationSettings *_wallpaperInSettings;
    SBFAnimationSettings *_dateOutSettings;
    SBFAnimationSettings *_overlayOutSettings;
    SBFAnimationSettings *_wallpaperOutSettings;
    struct CGRect _wallpaperInContentsRect;
    struct CGRect _wallpaperOutContentsRect;
}

+ (id)settingsControllerModule;
- (void)setWallpaperOutContentsRect:(struct CGRect)fp8;
- (struct CGRect)wallpaperOutContentsRect;
- (void)setWallpaperOutSettings:(id)fp8;
- (id)wallpaperOutSettings;
- (void)setOverlayOutSettings:(id)fp8;
- (id)overlayOutSettings;
- (void)setDateOutSettings:(id)fp8;
- (id)dateOutSettings;
- (void)setWallpaperInContentsRect:(struct CGRect)fp8;
- (struct CGRect)wallpaperInContentsRect;
- (void)setWallpaperInSettings:(id)fp8;
- (id)wallpaperInSettings;
- (void)setContentInSettings:(id)fp8;
- (id)contentInSettings;
- (void)setOverlayInSettings:(id)fp8;
- (id)overlayInSettings;
- (void)setDateInSettings:(id)fp8;
- (id)dateInSettings;
- (void)setBacklightFadeDuration:(float)fp8;
- (float)backlightFadeDuration;
- (void)setDefaultValues;

@end

