/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBFAnimationFactorySettings : _ABAddressBookCopyLocalizedLabel
{
    BOOL _slowAnimations;
    float _slowDownFactor;
    float _springMassFactor;
    float _springStiffnessFactor;
    float _springDampingFactor;
}

+ (id)settingsControllerModule;
- (void)setSpringDampingFactor:(float)fp8;
- (float)springDampingFactor;
- (void)setSpringStiffnessFactor:(float)fp8;
- (float)springStiffnessFactor;
- (void)setSpringMassFactor:(float)fp8;
- (float)springMassFactor;
- (void)setSlowDownFactor:(float)fp8;
- (float)slowDownFactor;
- (void)setSlowAnimations:(BOOL)fp8;
- (BOOL)slowAnimations;
- (void)setValue:(id)fp8 forKey:(id)fp12;
- (id)valueForKey:(id)fp8;
- (void)setDefaultValues;

@end

