/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBFileLogger : _ABAddressBookCopyLocalizedLabel
{
    id <SBFileLoggerDelegate> _delegate;
    int _logLevel;
}

- (int)logLevel;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)willBeginLoggingToPath:(id)fp8;
- (id)consoleFormat:(id)fp8 withArguments:(void *)fp12;
- (id)fileFormat:(id)fp8 withArguments:(void *)fp12;
- (void)reloadFromDefaults;
- (int)maxLogSize;
- (int)maxLogCount;
- (BOOL)includeConsole;
- (id)logPath;
- (id)name;
- (BOOL)isEnabled;
- (void)dealloc;
- (id)init;

@end

