/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconFadeAnimator.h"

@class SBFolderController;

@interface SBFolderIconFadeAnimator : SBIconFadeAnimator
{
    SBFolderController *_innerFolderController;
}

- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)dealloc;
- (id)initWithFolderController:(id)fp8 innerController:(id)fp12;

@end

