/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconObserver-Protocol.h"

@protocol SBFolderIconObserver <SBIconObserver>
- (void)folderIcon:(id)fp8 didUpdateGridImage:(id)fp12 forListIndex:(unsigned int)fp16 forContainedIconImageUpdate:(id)fp20;
@end

