/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

#import "SBFolderObserver-Protocol.h"
#import "SBIconIndexNodeObserver-Protocol.h"
#import "SBIconObserver-Protocol.h"

@class NSHashTable, NSMutableArray, NSMutableSet, SBFolder;

@interface SBFolderIcon : SBIcon <SBFolderObserver, SBIconObserver, SBIconIndexNodeObserver>
{
    NSMutableArray *_cachedMiniGrids;
    SBFolder *_folder;
    NSHashTable *_nodeObservers;
    NSMutableSet *_finishedDownloadIdentifiers;
    int _progressState;
    float _progressPercent;
}

+ (Class)_iconGridImageClass;
+ (unsigned int)_maxIconsInGridImage;
- (BOOL)hasFolderIconView;
- (id)folder;
- (BOOL)isFolderIcon;
- (void)folder:(id)fp8 didRemoveLists:(id)fp12 atIndexes:(id)fp16;
- (void)folder:(id)fp8 didAddList:(id)fp12;
- (void)node:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)node:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
- (id)nodeDescriptionWithPrefix:(id)fp8;
- (void)removeNodeObserver:(id)fp8;
- (void)addNodeObserver:(id)fp8;
- (id)nodesAlongIndexPath:(id)fp8 consumedIndexes:(unsigned int)fp12;
- (id)indexPathsForContainedNodeIdentifier:(id)fp8 prefixPath:(id)fp12;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)fp8;
- (id)nodeIdentifier;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)iconImageDidUpdate:(id)fp8;
- (id)miniGridCellImageForIcon:(id)fp8;
- (id)gridImages;
- (void)purgeCachedImages;
- (id)_miniIconGridForPage:(int)fp8;
- (unsigned int)gridCellIndexForIconIndex:(unsigned int)fp8;
- (unsigned int)listIndexForContainedIcon:(id)fp8;
- (void)_containedIconImageChanged:(id)fp8;
- (void)noteContainedIcon:(id)fp8 replacedIcon:(id)fp12;
- (void)noteContainedIconsAdded:(id)fp8 removed:(id)fp12;
- (void)_adjustForIconsAdded:(id)fp8 removed:(id)fp12;
- (float)progressPercent;
- (BOOL)progressIsPaused;
- (int)progressState;
- (void)_updateProgress;
- (void)_appPlaceholdersDidChange:(id)fp8;
- (void)_updateBadgeValue;
- (void)updateLabel;
- (void)launchFromLocation:(int)fp8;
- (id)description;
- (void)localeChanged;
- (BOOL)matchesRepresentation:(id)fp8;
- (id)representation;
- (id)displayName;
- (id)getGenericIconImage:(int)fp8;
- (id)generateIconImage:(int)fp8;
- (void)dealloc;
- (id)initWithFolder:(id)fp8;
- (Class)iconImageViewClassForLocation:(int)fp8;
- (Class)iconViewClassForLocation:(int)fp8;

@end

