/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBScaleZoomSettings.h"

@class SBFAnimationSettings;

@interface SBFolderZoomSettings : SBScaleZoomSettings
{
    SBFAnimationSettings *_innerFolderFadeSettings;
}

+ (id)settingsControllerModule;
- (void)setInnerFolderFadeSettings:(id)fp8;
- (id)innerFolderFadeSettings;
- (void)setDefaultValues;

@end

