/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class _UILegibilitySettings, _UILegibilityView;

@interface SBFolderTitleTextField : _ABAddressBookCopyLocalizedLabel
{
    BOOL _showingEditUI;
    _UILegibilityView *_legibilityView;
    BOOL _allowsEditing;
    _UILegibilitySettings *_legibilitySettings;
}

- (id)legibilitySettings;
- (void)setAllowsEditing:(BOOL)fp8;
- (BOOL)allowsEditing;
- (id)_clearButtonImage;
- (id)_backgroundImage;
- (void)_updateLegibility;
- (void)setLegibilitySettings:(id)fp8;
- (struct CGRect)clearButtonRectForBounds:(struct CGRect)fp8;
- (struct CGRect)editingRectForBounds:(struct CGRect)fp8;
- (struct CGRect)textRectForBounds:(struct CGRect)fp8;
- (struct CGRect)_textRectForBounds:(struct CGRect)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (float)fontSize;
- (void)setFontSize:(float)fp8;
- (void)layoutSubviews;
- (void)setText:(id)fp8;
- (void)_updateLegibilityView;
- (void)setShowsEditUI:(BOOL)fp8 animated:(BOOL)fp12;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

