/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconListPageControlDelegate-Protocol.h"
#import "SBIconScrollViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSMutableArray, SBFolder, SBFolderTitleTextField, SBIconListPageControl, SBIconListView, SBIconScrollView, SBIconViewMap, UIView, _UILegibilitySettings;

@interface SBFolderView : _ABAddressBookCopyLocalizedLabel <SBIconScrollViewDelegate, SBIconListPageControlDelegate, UITextFieldDelegate>
{
    NSMutableArray *_iconListViews;
    SBIconListView *_rotatingIconList;
    int _minVisibleListViewIndex;
    int _maxVisibleListViewIndex;
    int _minAnimatingListViewIndex;
    int _maxAnimatingListViewIndex;
    int _disableUpdatingCurrentIconListCount;
    int _firstDisplayedColumnOnCurrentList;
    BOOL _animatedScrolling;
    BOOL _scalingViewIsBorrowed;
    SBIconViewMap *_viewMap;
    NSMutableArray *_scrollFrames;
    unsigned int _scrollFrameCount;
    BOOL _isN90;
    SBIconListPageControl *_pageControl;
    SBIconScrollView *_scrollView;
    SBFolderTitleTextField *_titleTextField;
    UIView *_scalingView;
    BOOL _isEditing;
    BOOL _isScrolling;
    int _currentPageIndex;
    float _statusBarHeight;
    id <SBFolderViewDelegate> _delegate;
    SBFolder *_folder;
    int _orientation;
    _UILegibilitySettings *_legibilitySettings;
}

- (id)legibilitySettings;
- (int)orientation;
- (void)setFolder:(id)fp8;
- (id)folder;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (float)statusBarHeight;
- (int)currentPageIndex;
- (BOOL)isEditing;
- (void)willMoveToWindow:(id)fp8;
- (void)setLegibilitySettings:(id)fp8;
- (void)textFieldDidEndEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (void)_setFolderName:(id)fp8;
- (void)pageControl:(id)fp8 didRecieveTouchInDirection:(int)fp12;
- (void)iconScrollView:(id)fp8 willSetContentOffset:(inout struct CGPoint *)fp12;
- (void)iconScrollViewDidCancelTouchTracking:(id)fp8;
- (void)iconScrollViewWillCancelTouchTracking:(id)fp8;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8;
- (void)cleanupAfterClosing;
- (void)prepareToOpen;
- (BOOL)_scrollViewThinksItsScrolling;
- (void)_purgeListViews;
- (void)noteUserIsInteractingWithIcons;
- (void)noteUserHasGrabbedIcon:(BOOL)fp8;
- (void)updateIconListIndexAndVisibility:(BOOL)fp8;
- (int)lowestVisibleIconListIndexAndColumn:(int *)fp8 columnsOnScreen:(int *)fp12 totalLists:(unsigned int)fp16 columnsPerList:(unsigned int)fp20;
- (void)updateIconListIndexAndVisibility;
- (void)_updateEditingStateAnimated:(BOOL)fp8;
- (void)layoutIconLists:(double)fp8 domino:(BOOL)fp16 forceRelayout:(BOOL)fp20;
- (void)updateIconListViews;
- (void)resetIconListViews;
- (void)tearDownListViews;
- (id)currentIconListView;
- (id)iconListViewForTouch:(id)fp8;
- (id)iconListViewAtPoint:(struct CGPoint)fp8;
- (id)iconListViewAtIndex:(unsigned int)fp8;
- (int)_pageIndexForOffset:(float)fp8;
- (void)_updateIconListFrames;
- (void)_updateIconListViews;
- (void)_resetIconListViews;
- (void)_addIconListViewsForModels:(id)fp8;
- (id)_createIconListViewForList:(id)fp8;
- (id)_iconListViewForList:(id)fp8;
- (id)_iconListViewAtIndex:(unsigned int)fp8;
- (id)_currentIconListView;
- (void)_removeIconListView:(id)fp8;
- (void)_addIconListView:(id)fp8;
- (void)_enableUserInteractionAfterSignificantAnimation;
- (void)_disableUserInteractionBeforeSignificantAnimation;
- (float)_titleFontSize;
- (BOOL)_showsTitle;
- (void)_popDisableUpdateCurrentIconListCount;
- (void)_pushDisableUpdateCurrentIconListCount;
- (BOOL)_shouldDisableUpdatingCurrentIconList;
- (BOOL)_isValidPageIndex:(int)fp8;
- (float)_scrollOffsetForPageAtIndex:(int)fp8;
- (float)_scrollOffsetForFirstListView;
- (float)_pageWidth;
- (BOOL)_hasMinusPages;
- (unsigned int)_minusPageCount;
- (float)_offsetToCenterPageControlInSpaceForPageControl;
- (struct CGRect)_frameForScalingView;
- (void)_layoutSubviews;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)layoutSubviews;
- (void)setNeedsLayout;
- (void)fadeContentForMinificationFraction:(float)fp8;
- (void)fadeContentForMagnificationFraction:(float)fp8;
- (void)didAnimate;
- (void)willAnimate;
- (id)viewMap;
- (BOOL)locationCountsAsInsideFolder:(struct CGPoint)fp8;
- (void)returnScalingView;
- (id)borrowScalingView;
- (struct CGRect)scalingViewFrame;
- (BOOL)setCurrentPageIndex:(int)fp8 animated:(BOOL)fp12;
- (BOOL)doesPageContainIconListView:(int)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (id)iconListViews;
- (void)setStatusBarHeight:(float)fp8;
- (void)setOrientation:(int)fp8;
- (void)_setCurrentPageIndex:(int)fp8 deferringPageControlUpdate:(BOOL)fp12;
- (void)_setCurrentPageIndex:(int)fp8;
- (void)_setAnimatedScrolling:(BOOL)fp8;
- (void)setScrolling:(BOOL)fp8;
- (BOOL)isScrolling;
- (id)scrollView;
- (void)dealloc;
- (id)initWithFolder:(id)fp8 orientation:(int)fp12 viewMap:(id)fp16;
- (id)initWithFolder:(id)fp8 orientation:(int)fp12;

@end

