/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBWallpaperObserver-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class SBFolderSettings, SBWallpaperEffectView, UIImageView;

@interface SBFolderBackgroundView : _ABAddressBookCopyLocalizedLabel <_UISettingsKeyObserver, SBWallpaperObserver>
{
    SBWallpaperEffectView *_backdropView;
    UIImageView *_backgroundImageView;
    SBFolderSettings *_folderSettings;
}

+ (float)cornerRadiusToInsetContent;
+ (struct CGSize)folderBackgroundSize;
- (void)wallpaperDidChangeForVariant:(int)fp8;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (void)_configureBackground;
- (void)adjustCornerRadiusForMagnificationFraction:(float)fp8;
- (void)didAnimate;
- (void)willAnimate;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

