/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBFWallpaperViewInternalObserver <NSObject>
- (void)wallpaperViewDidChangeWantsRasterization:(id)fp8;
- (void)wallpaperView:(id)fp8 didChangeZoomFactor:(float)fp12;
- (void)wallpaperViewDidInvalidateGeometry:(id)fp8;
- (void)wallpaperViewDidInvalidateBlurs:(id)fp8;
@end

