/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, UIImage, UIImageView, UIView, _UIBackdropView;

@interface SBHUDView : _ABAddressBookCopyLocalizedLabel
{
    int _level;
    NSString *_title;
    NSString *_subtitle;
    UIImage *_image;
    BOOL _showsProgress;
    float _progress;
    UIView *_blockView;
    _UIBackdropView *_backdropView;
    UIImageView *_backdropMaskImageView;
}

+ (float)progressIndicatorStep;
+ (int)numberOfProgressIndicatorSteps;
- (float)progress;
- (BOOL)showsProgress;
- (void)setLevel:(int)fp8;
- (int)level;
- (void)layoutSubviews;
- (void)_updateBlockView;
- (id)_blockColorForValue:(float)fp8;
- (void)_updateBlockView:(id)fp8 value:(float)fp12 blockSize:(struct CGSize)fp16 point:(struct CGPoint)fp24;
- (void)setProgress:(float)fp8;
- (void)setShowsProgress:(BOOL)fp8;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setSubtitle:(id)fp8;
- (id)subtitle;
- (void)setTitle:(id)fp8;
- (id)title;
- (BOOL)displaysLabel;
- (void)_updateBackdropMask;
- (void)dismissWithCompletion:(id)fp(null);
- (void)cancelDismissal;
- (void)dealloc;
- (id)initWithHUDViewLevel:(int)fp8;

@end

