/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBIconListModelObserver <NSObject>
- (void)iconList:(id)fp8 didRemoveIcon:(id)fp12;
- (void)iconList:(id)fp8 didReplaceIcon:(id)fp12 withIcon:(id)fp16;
- (void)iconList:(id)fp8 didAddIcon:(id)fp12;
@end

