/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBInteractionPassThroughView.h"

@class SBIconImageView, UIView, _SBAnimatableCorneredView;

@interface SBIconImageCrossfadeView : SBInteractionPassThroughView
{
    _SBAnimatableCorneredView *_containerView;
    SBIconImageView *_imageView;
    UIView *_crossfadeView;
    float _crossfadeFraction;
    float _containerScaleX;
    float _containerScaleY;
    BOOL _masksCorners;
    BOOL _performsTrueCrossfade;
    struct CGPoint _stretchAnchorPoint;
}

- (struct CGPoint)stretchAnchorPoint;
- (void)setPerformsTrueCrossfade:(BOOL)fp8;
- (BOOL)performsTrueCrossfade;
- (BOOL)masksCorners;
- (void)_updateCornerMask;
- (void)cleanup;
- (void)setMorphFraction:(float)fp8;
- (void)setFadeFraction:(float)fp8;
- (void)setStretchAnchorPoint:(struct CGPoint)fp8;
- (void)setMasksCorners:(BOOL)fp8;
- (void)layoutSubviews;
- (void)prepareGeometry;
- (void)dealloc;
- (id)initWithImageView:(id)fp8 crossfadeView:(id)fp12;

@end

