/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "NSCopying-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@class NSString, UIFont;

@interface SBIconLabelImageParameters : _ABAddressBookCopyLocalizedLabel <NSCopying, NSMutableCopying>
{
    UIFont *_font;
    NSString *_text;
    BOOL _containsNonLatinLikeCharacters;
    BOOL _containsEmoji;
    BOOL _canEllipsize;
    struct CGSize _maxSize;
    int _style;
}

- (int)style;
- (BOOL)containsEmoji;
- (BOOL)containsNonLatinLikeCharacters;
- (BOOL)canEllipsize;
- (id)font;
- (struct CGSize)maxSize;
- (id)text;
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (BOOL)colorspaceIsGrayscale;
- (void)dealloc;
- (id)initWithParameters:(id)fp8;

@end

