/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBCountedMapValue-Protocol.h"

@class NSString;

@interface SBIconAccessoryImage : _ABAddressBookCopyLocalizedLabel <SBCountedMapValue>
{
    NSString *_countedMapKey;
}

- (void)setCountedMapKey:(id)fp8;
- (id)countedMapKey;
- (void)dealloc;
- (id)initWithImage:(id)fp8;

@end

