/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class _UILegibilityImageSet;

@interface SBIconListPageControl : _ABAddressBookCopyLocalizedLabel
{
    id _delegate;
    _UILegibilityImageSet *_pageIndicatorImageSet;
    _UILegibilityImageSet *_enabledPageIndicatorImageSet;
}

- (void)setEnabledPageIndicatorImageSet:(id)fp8;
- (id)enabledPageIndicatorImageSet;
- (void)setPageIndicatorImageSet:(id)fp8;
- (id)pageIndicatorImageSet;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)_transitionIndicator:(id)fp8 toEnabled:(BOOL)fp12 index:(int)fp16;
- (id)_indicatorViewEnabled:(BOOL)fp8 index:(int)fp12;
- (void)_setIndicatorImage:(id)fp8 toEnabled:(BOOL)fp12;
- (void)setLegibilitySettings:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (float)defaultHeight;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

