/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBIconColorSettings : _ABAddressBookCopyLocalizedLabel
{
    BOOL _blurryFolderIcons;
    BOOL _blurryCloseBoxes;
    BOOL _suppressJitter;
    BOOL _closeBoxesEverywhere;
    float _maxSaturationBoost;
    float _maxSaturation;
    float _maxBrightnessBoost;
    float _maxBrightness;
    float _colorAlpha;
    float _whiteAlpha;
}

+ (id)settingsControllerModule;
- (void)setCloseBoxesEverywhere:(BOOL)fp8;
- (BOOL)closeBoxesEverywhere;
- (void)setSuppressJitter:(BOOL)fp8;
- (BOOL)suppressJitter;
- (void)setWhiteAlpha:(float)fp8;
- (float)whiteAlpha;
- (void)setColorAlpha:(float)fp8;
- (float)colorAlpha;
- (void)setMaxBrightness:(float)fp8;
- (float)maxBrightness;
- (void)setMaxBrightnessBoost:(float)fp8;
- (float)maxBrightnessBoost;
- (void)setMaxSaturation:(float)fp8;
- (float)maxSaturation;
- (void)setMaxSaturationBoost:(float)fp8;
- (float)maxSaturationBoost;
- (void)setBlurryCloseBoxes:(BOOL)fp8;
- (BOOL)blurryCloseBoxes;
- (void)setBlurryFolderIcons:(BOOL)fp8;
- (BOOL)blurryFolderIcons;
- (void)setDefaultValues;

@end

