/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class CADisplayLink, UIImage, _SBIconProgressFractionTransition, _SBIconProgressPausedTransition, _SBIconProgressStateTransition;

@interface SBIconProgressView : _ABAddressBookCopyLocalizedLabel
{
    _SBIconProgressStateTransition *_activeStateTransition;
    _SBIconProgressPausedTransition *_activePausedTransition;
    _SBIconProgressFractionTransition *_activeFractionTransition;
    int _modelState;
    BOOL _modelPaused;
    float _modelFraction;
    CADisplayLink *_displayLink;
    double _lastUpdate;
    UIImage *_maskImage;
    BOOL _canAnimate;
    BOOL _displayingPaused;
    id <SBIconProgressViewDelegate> _delegate;
    UIImage *_overlayImage;
    float _backgroundAlpha;
    float _foregroundAlpha;
    float _circleRadiusFraction;
    float _pauseRadiusFraction;
    int _displayedState;
    float _displayedFraction;
}

- (void)setDisplayedFraction:(float)fp8;
- (float)displayedFraction;
- (void)setDisplayingPaused:(BOOL)fp8;
- (BOOL)displayingPaused;
- (void)setDisplayedState:(int)fp8;
- (int)displayedState;
- (void)setPauseRadiusFraction:(float)fp8;
- (float)pauseRadiusFraction;
- (void)setCircleRadiusFraction:(float)fp8;
- (float)circleRadiusFraction;
- (void)setForegroundAlpha:(float)fp8;
- (float)foregroundAlpha;
- (void)setBackgroundAlpha:(float)fp8;
- (float)backgroundAlpha;
- (BOOL)canAnimate;
- (id)overlayImage;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (struct CGRect)circleBoundingRect;
- (id)_maskImage;
- (void)_drawPauseUIWithCenter:(struct CGPoint)fp8;
- (void)_drawIncomingCircleWithCenter:(struct CGPoint)fp8;
- (void)_drawOutgoingCircleWithCenter:(struct CGPoint)fp8;
- (void)_drawPieWithCenter:(struct CGPoint)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)_clearDisplayLink;
- (void)_ensureDisplayLink;
- (void)_onDisplayLink:(id)fp8;
- (void)_clearTransitionIfComplete:(id *)fp8;
- (void)_updateFractionTransitionAnimated:(BOOL)fp8;
- (void)_updateStateTransitionAnimated:(BOOL)fp8;
- (void)_updatePausedTransitionAnimated:(BOOL)fp8;
- (void)_updateTransitionsAnimated:(BOOL)fp8;
- (BOOL)_hasActiveTransitions;
- (void)setOverlayImage:(id)fp8;
- (void)setCanAnimate:(BOOL)fp8;
- (void)setState:(int)fp8 paused:(BOOL)fp12 fractionLoaded:(float)fp16 animated:(BOOL)fp20;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

