/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBFAnimationSettings;

@interface SBIconAnimationSettings : _ABAddressBookCopyLocalizedLabel
{
    SBFAnimationSettings *_centralAnimationSettings;
}

+ (id)settingsControllerModule;
- (void)setCentralAnimationSettings:(id)fp8;
- (id)centralAnimationSettings;
- (void)setDefaultValues;

@end

