/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBCountedMapValue-Protocol.h"

@class SBIconLabelImageParameters;

@interface SBIconLabelLegibilityImage : _ABAddressBookCopyLocalizedLabel <SBCountedMapValue>
{
    SBIconLabelImageParameters *_parameters;
}

+ (void)checkinLegibilityImage:(id)fp8;
+ (id)checkoutLegibilityImageWithLabelImage:(id)fp8 parameters:(id)fp12;
+ (struct CGRect)_legibilityImageRectForLabelImage:(id)fp8 style:(int)fp12;
+ (float)_strengthForLegibilityStyle:(int)fp8;
+ (id)_legibilityImageForIconLabelImage:(id)fp8 parameters:(id)fp12;
+ (id)_legibilityImagePool;
+ (id)_legibilityImageCountedMap;
+ (struct CGSize)_maxLegibilityImageSizeForLabelSize:(struct CGSize)fp8;
- (id)parameters;
- (id)countedMapKey;
- (void)dealloc;
- (id)_initWithCGImage:(struct CGImage *)fp8 scale:(float)fp12 orientation:(int)fp16 parameters:(id)fp20;

@end

