/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSimplePreferenceFileLogger.h"

@interface SBIconLogger : SBSimplePreferenceFileLogger
{
}

+ (BOOL)isIconLoggingEnabled;
- (void)reloadFromDefaults;
- (id)consoleFormat:(id)fp8 withArguments:(void *)fp12;
- (id)logPreferenceName;
- (int)maxLogCount;
- (id)name;

@end

