/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconIndexNode-Protocol.h"

@class NSHashTable, UIImage;

@interface SBIcon : _ABAddressBookCopyLocalizedLabel <SBIconIndexNode>
{
    NSHashTable *_observers;
    id _badgeNumberOrString;
    unsigned int _uninstalled:1;
    UIImage *_cachedIconImages[14];
}

+ (id)memoryMappedIconImageOfSize:(struct CGSize)fp8 scale:(float)fp16 withDrawing:(id)fp(null);
+ (id)memoryMappedIconImageForIconImage:(id)fp8;
+ (id)_iconImageOfSize:(struct CGSize)fp8 scale:(float)fp16 failGracefully:(BOOL)fp20 drawing:(id)fp(null);
+ (id)_iconImagesMemoryPool;
- (BOOL)canReceiveGrabbedIcon;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;
- (id)uninstallAlertTitle;
- (BOOL)isUninstalled;
- (void)setUninstalled;
- (void)completeUninstall;
- (BOOL)allowsUninstall;
- (BOOL)progressIsPaused;
- (float)progressPercent;
- (int)progressState;
- (void)launchFromLocation:(int)fp8;
- (id)automationID;
- (BOOL)isRecentlyUpdated;
- (void)setBadge:(id)fp8;
- (void)noteBadgeDidChange;
- (int)accessoryTypeForLocation:(int)fp8;
- (id)accessoryTextForLocation:(int)fp8;
- (id)badgeNumberOrString;
- (int)badgeValue;
- (void)reloadIconImagePurgingImageCache:(BOOL)fp8;
- (void)reloadIconImage;
- (void)purgeCachedImages;
- (id)gridCellImage;
- (id)getGenericIconImage:(int)fp8;
- (id)getUnmaskedIconImage:(int)fp8;
- (id)getIconImage:(int)fp8;
- (id)getStandardIconImageForLocation:(int)fp8;
- (BOOL)shouldCacheImageForFormat:(int)fp8;
- (id)generateIconImage:(int)fp8;
- (BOOL)launchEnabled;
- (id)tags;
- (BOOL)matchesEntity:(id)fp8;
- (int)localizedCompareDisplayNames:(id)fp8;
- (BOOL)canEllipsizeLabel;
- (id)displayName;
- (void)localeChanged;
- (BOOL)matchesRepresentation:(id)fp8;
- (id)representation;
- (void)dealloc;
- (id)init;
- (int)iconFormatForLocation:(int)fp8;
- (BOOL)shouldWarmUp;
- (BOOL)hasCachedImageForLocation:(int)fp8;
- (id)nodeDescriptionWithPrefix:(id)fp8;
- (void)removeNodeObserver:(id)fp8;
- (void)addNodeObserver:(id)fp8;
- (id)nodesAlongIndexPath:(id)fp8 consumedIndexes:(unsigned int)fp12;
- (id)indexPathsForContainedNodeIdentifier:(id)fp8 prefixPath:(id)fp12;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)fp8;
- (id)nodeIdentifier;
- (BOOL)hasObserver:(id)fp8;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (id)description;
- (id)application;
- (BOOL)isApplicationIcon;
- (BOOL)isBookmarkIcon;
- (id)appPlaceholder;
- (BOOL)isDownloadingIcon;
- (BOOL)isUserInstalledApplicationIcon;
- (BOOL)isWebApplicationIcon;
- (BOOL)hasFolderIconView;
- (id)folder;
- (BOOL)isFolderIcon;
- (id)applicationBundleID;
- (id)webClip;
- (id)leafIdentifier;
- (BOOL)isLeafIcon;
- (Class)iconImageViewClassForLocation:(int)fp8;
- (Class)iconViewClassForLocation:(int)fp8;
- (void)_notifyLaunchEnabledDidChange;
- (void)_notifyAccessoriesDidUpdate;
- (void)_notifyImageDidUpdate;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)isNewsstandApplicationIcon;
- (BOOL)isNewsstandIcon;
- (BOOL)isEmptyPlaceholder;
- (BOOL)isGrabbedIconPlaceholder;
- (BOOL)isPlaceholder;

@end

