/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, NSString, SBFolderController, SBIconAnimationSettings, UIWindow;

@interface SBIconAnimator : _ABAddressBookCopyLocalizedLabel
{
    float _fraction;
    BOOL _startedAnimation;
    BOOL _startAnimationAfterRotationEnds;
    BOOL _windowIsRotating;
    UIWindow *_animationWindow;
    NSMutableArray *_pendedAnimationContexts;
    NSString *_instanceIdentifier;
    BOOL _invalidated;
    id <SBIconAnimatorDelegate> _delegate;
    SBIconAnimationSettings *_settings;
    SBFolderController *_folderController;
}

- (id)animationWindow;
- (id)folderController;
- (BOOL)invalidated;
- (void)setSettings:(id)fp8;
- (id)settings;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)_windowFinishedRotating;
- (void)_invalidateCompletions;
- (id)_centralAnimationFactory;
- (void)_animateToFraction:(float)fp8 afterDelay:(double)fp12 withSharedCompletion:(id)fp(null);
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)fp8;
- (void)_prepareAnimation;
- (BOOL)_isDelayedForRotation;
- (void)_animateToFractionFromContext:(id)fp8;
- (void)_animateToFractionFromPendingContexts;
- (void)cleanup;
- (void)animateToFraction:(float)fp8 afterDelay:(double)fp12 withCompletion:(id)fp(null);
- (void)setFraction:(float)fp8;
- (void)prepare;
- (id)centralAnimationFactory;
- (id)referenceView;
- (void)setInvalidated:(BOOL)fp8;
- (void)dealloc;
- (id)initWithFolderController:(id)fp8;

@end

