/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIScrollViewDelegate-Protocol.h"

@protocol SBIconScrollViewDelegate <UIScrollViewDelegate>
- (void)iconScrollView:(id)fp8 willSetContentOffset:(inout struct CGPoint *)fp12;
- (void)iconScrollViewDidCancelTouchTracking:(id)fp8;
- (void)iconScrollViewWillCancelTouchTracking:(id)fp8;
@end

