/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBLeafIconDataSource <NSObject>
- (BOOL)icon:(id)fp8 launchFromLocation:(int)fp12;
- (BOOL)iconAllowsLaunch:(id)fp8;
- (BOOL)iconCompleteUninstall:(id)fp8;
- (BOOL)iconAllowsUninstall:(id)fp8;
- (BOOL)iconIsRecentlyUpdated:(id)fp8;
- (int)iconAccessoryType:(id)fp8;
- (id)iconFormattedAccessoryString:(id)fp8;
- (id)iconBadgeNumberOrString:(id)fp8;
- (BOOL)iconProgressIsPaused:(id)fp8;
- (float)iconProgressPercent:(id)fp8;
- (int)iconProgressState:(id)fp8;
- (BOOL)iconAppearsInNewsstand:(id)fp8;
- (BOOL)iconCanEllipsizeLabel:(id)fp8;
- (id)iconDisplayName:(id)fp8;
- (id)icon:(id)fp8 defaultImageWithFormat:(int)fp12;
- (id)icon:(id)fp8 imageWithFormat:(int)fp12;
- (unsigned int)iconPriority:(id)fp8;
@end

