/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

#import "NSCopying-Protocol.h"

@class NSMutableSet, NSString;

@interface SBLeafIcon : SBIcon <NSCopying>
{
    NSString *_leafIdentifier;
    NSString *_applicationBundleID;
    NSMutableSet *_dataSources;
    id <SBLeafIconDataSource> _activeDataSource;
    id <SBLeafIconDataSource> _dataSourceAtUninstallation;
}

- (id)nodeIdentifier;
- (void)launchFromLocation:(int)fp8;
- (BOOL)launchEnabled;
- (void)completeUninstall;
- (void)setUninstalled;
- (BOOL)allowsUninstall;
- (BOOL)isRecentlyUpdated;
- (int)accessoryTypeForLocation:(int)fp8;
- (id)accessoryTextForLocation:(int)fp8;
- (id)badgeNumberOrString;
- (BOOL)progressIsPaused;
- (float)progressPercent;
- (int)progressState;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)canEllipsizeLabel;
- (id)displayName;
- (id)getGenericIconImage:(int)fp8;
- (id)generateIconImage:(int)fp8;
- (void)_noteDataSourceDidInvalidateNotification:(id)fp8;
- (void)_noteActiveDataSourceDidGenerateImageNotification:(id)fp8;
- (void)_noteActiveDataSourceDidChangeNotification:(id)fp8;
- (void)_noteActiveDataSourceDidGenerateIconFormat:(int)fp8;
- (void)_noteActiveDataSourceDidChangeAndReloadIcon:(BOOL)fp8;
- (id)activeDataSource;
- (void)removeIconDataSourcesOfClass:(Class)fp8;
- (void)removeIconDataSource:(id)fp8;
- (void)addIconDataSource:(id)fp8;
- (void)_updateActiveDataSource;
- (BOOL)matchesRepresentation:(id)fp8;
- (id)representation;
- (id)applicationBundleID;
- (id)leafIdentifier;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithLeafIdentifier:(id)fp8 applicationBundleID:(id)fp12;
- (id)init;

@end

