/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImage;

@interface SBLegibilityView : _ABAddressBookCopyLocalizedLabel
{
    int _tintColor;
    UIImage *_tintImage;
    struct UIEdgeInsets _hitTestEdgeInsets;
}

- (void)setTintImage:(id)fp8;
- (id)tintImage;
- (void)setTintColor:(int)fp8;
- (int)tintColor;
- (void)setHitTestEdgeInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)hitTestEdgeInsets;
- (id)_tintColorForSettings:(id)fp8;
- (void)setSettings:(id)fp8 image:(id)fp12 shadowImage:(id)fp16;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)dealloc;
- (id)initWithSettings:(id)fp8 strength:(float)fp12 image:(id)fp16 tintColor:(int)fp20;

@end

