/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconImageView.h"

#import "SBControlCenterObserver-Protocol.h"

@interface SBLiveIconImageView : SBIconImageView <SBControlCenterObserver>
{
    unsigned int _pauseCauses;
}

+ (void)_displayDidDeactivate:(id)fp8;
+ (void)_displayWillActivate:(id)fp8;
+ (void)initialize;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)_activeDisplayChanged:(id)fp8;
- (void)didMoveToWindow;
- (id)snapshot;
- (void)prepareForReuse;
- (void)updateImageAnimated:(BOOL)fp8;
- (void)updateAnimatingState;
- (void)setPaused:(BOOL)fp8;
- (BOOL)isAnimationAllowed;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

