/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "_UISettingsKeyObserver-Protocol.h"

@class NSMutableDictionary, SBLockScreenPlugin, SBLockScreenPluginLoader, SBLockScreenPluginTransitionFactory, SBLockScreenTestPluginSettings, SBLockScreenViewController, UIWindow;

@interface SBLockScreenPluginController : _ABAddressBookCopyLocalizedLabel <_UISettingsKeyObserver>
{
    SBLockScreenPluginLoader *_pluginLoader;
    NSMutableDictionary *_plugins;
    SBLockScreenPlugin *_activePlugin;
    SBLockScreenPlugin *_displayedPlugin;
    SBLockScreenPluginTransitionFactory *_transitionFactory;
    id <SBLockScreenPluginControllerDelegate> _delegate;
    SBLockScreenViewController *_lockScreenViewController;
    BOOL _pluginControllerReceivedViewWillDisappear;
    BOOL _pluginControllerReceivedViewDidDisappear;
    UIWindow *_previousWindow;
    SBLockScreenTestPluginSettings *_testSettings;
    BOOL _lockScreenHasNotifications;
    BOOL _allowDisplayOfPlugins;
    float _fadeDuration;
}

- (void)setFadeDuration:(float)fp8;
- (float)fadeDuration;
- (void)setAllowDisplayOfPlugins:(BOOL)fp8;
- (BOOL)allowDisplayOfPlugins;
- (BOOL)lockScreenHasNotifications;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setPluginLoader:(id)fp8;
- (id)pluginLoader;
- (void)setLockScreenViewController:(id)fp8;
- (id)lockScreenViewController;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (BOOL)_pluginHidesNotificationList:(id)fp8;
- (void)_updateNotificationListForNewlyActivatedPlugin;
- (void)_transitionFromNotificationListToExclusionaryPlugin;
- (void)_transitionFromExclusionaryPluginToNotificationList;
- (void)setLockScreenHasNotifications:(BOOL)fp8;
- (void)_notifyDisplayedPluginRemovedFromWindow;
- (void)_notifyDisplayedPluginAddedToWindow;
- (void)_lockScreenDidMoveToWindow;
- (void)_lockScreenWillMoveToWindow;
- (void)_disablePluginsPassingTest:(id)fp(null) withReason:(void)fp8;
- (void)_removeActivePlugin;
- (void)_removeDisplayedPlugin;
- (void)_handleUIRelock;
- (void)handleUIUnlock;
- (id)_pluginForName:(id)fp8 controller:(id)fp12;
- (void)_loadLockScreenPluginWithName:(id)fp8 activationContext:(id)fp12;
- (void)_handleApplicationExit:(id)fp8;
- (void)disableLockScreenBundleWithName:(id)fp8 deactivationContext:(id)fp12;
- (void)_handlePluginDisable:(id)fp8;
- (id)_transitionContextWithOldPlugin:(id)fp8 newPlugin:(id)fp12;
- (void)_updateCallPluginPresentationStyle;
- (void)_setEffectivePresentationStyleForDisplayedPluginIfNecessary;
- (void)_setDisplayedPlugin:(id)fp8;
- (void)_setActivePlugin:(id)fp8;
- (BOOL)isPhonePluginVisible;
- (BOOL)isPhonePluginActive;
- (void)_refreshLockScreenPlugin;
- (void)reset;
- (void)enableLockScreenBundleWithName:(id)fp8 activationContext:(id)fp12;
- (id)_pluginView;
- (id)_lockScreenView;
- (BOOL)handleHeadsetButtonPressed:(BOOL)fp8;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)handleMenuButtonHeld;
- (BOOL)wantsMenuButtonHeldEvent;
- (BOOL)handleMenuButtonDoubleTap;
- (BOOL)handleMenuButtonTap;
- (BOOL)sendEventToPlugin:(id)fp(null);
- (id)_highestPriorityPluginIgnoringViewDisplay:(BOOL)fp8;
- (BOOL)pluginControllerShouldAnimateOthersResumption;
- (struct CGRect)defaultContentRegionForPluginController:(id)fp8 withOrientation:(int)fp12;
- (BOOL)activePluginHidesNotificationList;
- (id)activePluginBundleName;
- (id)displayedPlugin;
- (id)activePlugin;
- (BOOL)isPluginVisible;
- (void)dealloc;
- (void)_addObservers;
- (id)initWithLockScreenViewController:(id)fp8;

@end

