/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBBounceSettings, SBFAnimationSettings, SBLockScreenPasscodeSettings, SBSlideToUnlockFailureRecognizerSettings;

@interface SBLockScreenSettings : _ABAddressBookCopyLocalizedLabel
{
    BOOL _alwaysPutPluginsBelowScrollView;
    SBBounceSettings *_verticalBounceSettings;
    SBBounceSettings *_horizontalBounceSettings;
    SBLockScreenPasscodeSettings *_passcodeSettings;
    SBSlideToUnlockFailureRecognizerSettings *_slideToUnlockFailureRecognizerSettings;
    SBFAnimationSettings *_unlockToPhoneWallpaperOutSettings;
    SBFAnimationSettings *_unlockToPhoneWallpaperInSettings;
    SBFAnimationSettings *_unlockWallpaperOutSettings;
    SBFAnimationSettings *_unlockWallpaperInSettings;
    float _lockToUnlockSlideCompletionPercentage;
    float _lockToUnlockSlideCompletionPercentageIPad;
    float _unlockSlideForIdleTimerDisabledPercentage;
    float _unlockSlideForIdleTimerDisabledPercentageIPad;
    float _notificationScrollForIdleTimerDisabledOffset;
    float _notificationScrollForIdleTimerDisabledOffsetIPad;
    float _unlockSwipeWallpaperAlpha;
}

+ (id)settingsControllerModule;
- (void)setAlwaysPutPluginsBelowScrollView:(BOOL)fp8;
- (BOOL)alwaysPutPluginsBelowScrollView;
- (void)setUnlockSwipeWallpaperAlpha:(float)fp8;
- (float)unlockSwipeWallpaperAlpha;
- (void)setNotificationScrollForIdleTimerDisabledOffsetIPad:(float)fp8;
- (float)notificationScrollForIdleTimerDisabledOffsetIPad;
- (void)setNotificationScrollForIdleTimerDisabledOffset:(float)fp8;
- (float)notificationScrollForIdleTimerDisabledOffset;
- (void)setUnlockSlideForIdleTimerDisabledPercentageIPad:(float)fp8;
- (float)unlockSlideForIdleTimerDisabledPercentageIPad;
- (void)setUnlockSlideForIdleTimerDisabledPercentage:(float)fp8;
- (float)unlockSlideForIdleTimerDisabledPercentage;
- (void)setLockToUnlockSlideCompletionPercentageIPad:(float)fp8;
- (float)lockToUnlockSlideCompletionPercentageIPad;
- (void)setLockToUnlockSlideCompletionPercentage:(float)fp8;
- (float)lockToUnlockSlideCompletionPercentage;
- (void)setUnlockWallpaperInSettings:(id)fp8;
- (id)unlockWallpaperInSettings;
- (void)setUnlockWallpaperOutSettings:(id)fp8;
- (id)unlockWallpaperOutSettings;
- (void)setUnlockToPhoneWallpaperInSettings:(id)fp8;
- (id)unlockToPhoneWallpaperInSettings;
- (void)setUnlockToPhoneWallpaperOutSettings:(id)fp8;
- (id)unlockToPhoneWallpaperOutSettings;
- (void)setSlideToUnlockFailureRecognizerSettings:(id)fp8;
- (id)slideToUnlockFailureRecognizerSettings;
- (void)setPasscodeSettings:(id)fp8;
- (id)passcodeSettings;
- (void)setHorizontalBounceSettings:(id)fp8;
- (id)horizontalBounceSettings;
- (void)setVerticalBounceSettings:(id)fp8;
- (id)verticalBounceSettings;
- (void)setDefaultValues;

@end

