/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBDisableAppStatusBarAlphaChangesAssertion;

@interface SBLockToAppStatusBarAnimator : _ABAddressBookCopyLocalizedLabel
{
    SBDisableAppStatusBarAlphaChangesAssertion *_disableStatusBarAlphaChangeAssertion;
}

- (void)animateStatusBarFromLockToHome;

@end

