/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockScreenBulletinCell.h"

#import "SBDateLabelDelegate-Protocol.h"

@class SBSnoozedAlarmDateLabel;

@interface SBLockScreenSnoozedAlarmCell : SBLockScreenBulletinCell <SBDateLabelDelegate>
{
    SBSnoozedAlarmDateLabel *_countdownLabel;
}

+ (BOOL)wantsUnlockActionText;
+ (float)rowHeight;
- (void)dateLabelDidChange:(id)fp8;
- (void)setContentAlpha:(float)fp8;
- (void)setFireDate:(id)fp8;
- (void)layoutSubviews;
- (void)dealloc;

@end

