/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBLockScreenBatteryFillView, UIView, _UIBackdropView, _UILegibilityLabel, _UILegibilitySettings;

@interface SBLockScreenBatteryChargingView : _ABAddressBookCopyLocalizedLabel
{
    UIView *_batteryContainerView;
    _UIBackdropView *_batteryBlurView;
    SBLockScreenBatteryFillView *_batteryFillView;
    _UILegibilityLabel *_chargePercentLabel;
    _UILegibilitySettings *_legibilitySettings;
}

- (id)legibilitySettings;
- (float)_chargingTextBaselineOffset;
- (id)_chargePercentFont;
- (void)layoutSubviews;
- (struct CGPoint)_batteryOrigin;
- (void)setBatteryVisible:(BOOL)fp8;
- (BOOL)batteryVisible;
- (void)_setChargeString:(id)fp8;
- (void)setChargePercentage:(int)fp8 detailed:(BOOL)fp12;
- (void)setLegibilitySettings:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

