/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBNotificationCell.h"

@class SBLockScreenNotificationScrollView, SBUnlockActionContext, UILabel, UIView;

@interface SBLockScreenNotificationCell : SBNotificationCell
{
    BOOL _isTopCell;
    BOOL _drawsSeparators;
    float _currentContentAlpha;
    UIView *_topSeparatorView;
    UIView *_bottomSeparatorView;
    id <SBAwayListCellButtonHandler> _actionButtonHandler;
    SBLockScreenNotificationScrollView *_contentScrollView;
    SBUnlockActionContext *_unlockActionContext;
    UILabel *_unlockTextLabel;
    id <UIScrollViewDelegate> _delegate;
    BOOL _resetsScrollOnPluginWillDisable;
    float _contentScrollViewWidth;
}

+ (float)primaryPaddingLeft;
+ (BOOL)wantsUnlockActionText;
+ (float)rowHeightForTitle:(id)fp8 subtitle:(id)fp12 body:(id)fp16 maxLines:(unsigned int)fp20 attachmentSize:(struct CGSize)fp24 datesVisible:(BOOL)fp32 rowWidth:(float)fp36 includeUnlockActionText:(BOOL)fp40;
+ (id)defaultColorForEventDate;
+ (id)defaultColorForRelevanceDate;
+ (id)defaultColorForSecondaryText;
+ (id)defaultColorForSubtitleText;
+ (id)defaultColorForPrimaryText;
+ (id)defaultFontForEventDate;
+ (id)defaultFontForRelevanceDate;
+ (id)defaultFontForSecondaryText;
+ (id)defaultFontForSubtitleText;
+ (id)defaultFontForPrimaryText;
- (BOOL)resetsScrollOnPluginWillDisable;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)unlockActionContext;
- (float)contentScrollViewWidth;
- (BOOL)drawsSeparators;
- (BOOL)isTopCell;
- (void)layoutSubviews;
- (void)_handleActionButtonPress:(id)fp8;
- (id)_buttonWithLabel:(id)fp8;
- (void)setButtonLabel:(id)fp8 handler:(id)fp12;
- (void)setRelevanceDateLabel:(id)fp8;
- (void)setUnlockActionContext:(id)fp8;
- (void)setIsTopCell:(BOOL)fp8;
- (void)_updateUnlockText:(id)fp8;
- (void)_setSeparatorBackdropOverlayBlendMode:(int)fp8;
- (int)_separatorBackdropOverlayBlendMode;
- (id)_vibrantTextColor;
- (void)setContentScrollViewWidth:(float)fp8;
- (void)setDrawsSeparators:(BOOL)fp8;
- (void)setContentAlpha:(float)fp8;
- (void)scrollToOriginAnimated:(BOOL)fp8;
- (void)resetScrollView;
- (void)_notePluginWillDisable:(id)fp8;
- (void)setResetsScrollOnPluginWillDisable:(BOOL)fp8;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (id)_separatorColor;

@end

