/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSTimer, SBLockScreenBatteryChargingView;

@interface SBLockScreenBatteryChargingViewController : _ABAddressBookCopyLocalizedLabel
{
    SBLockScreenBatteryChargingView *_chargingView;
    NSTimer *_visibilityTimer;
    BOOL _displayDetailedCharge;
    int _chargePercentage;
    id <SBLockScreenBatteryChargingViewControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)_batteryStatusChanged:(id)fp8;
- (void)_visibilityTimerFired:(id)fp8;
- (void)showChargeLevelWithBatteryVisible:(BOOL)fp8;
- (id)chargingView;
- (BOOL)batteryVisible;
- (void)_clearVisibilityTimer;
- (void)prepareForDismissal;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

