/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, SBPasscodeLockDisableAssertion;

@interface SBLockScreenDisableAssertion : _ABAddressBookCopyLocalizedLabel
{
    NSString *_identifier;
    SBPasscodeLockDisableAssertion *_disableLockAssertion;
}

+ (void)initialize;
- (void)dealloc;
- (id)description;
- (id)initWithIdentifier:(id)fp8;

@end

