/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockOverlayViewController.h"

@interface SBLockScreenResetRestoreViewController : SBLockOverlayViewController
{
}

- (void)setResetRestoreText:(id)fp8;
- (void)loadView;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

