/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBLockScreenPasscodeSettings : _ABAddressBookCopyLocalizedLabel
{
    int _scrollBehavior;
    float _fixedHysteresis;
    float _percentOfNextButtonIncluded;
}

+ (id)settingsControllerModule;
- (void)setPercentOfNextButtonIncluded:(float)fp8;
- (float)percentOfNextButtonIncluded;
- (void)setFixedHysteresis:(float)fp8;
- (float)fixedHysteresis;
- (void)setScrollBehavior:(int)fp8;
- (int)scrollBehavior;
- (void)setDefaultValues;

@end

