/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBLockScreenViewDelegate <NSObject>
- (BOOL)wantsToShowStatusBarTime;
- (id)effectiveCustomSlideToUnlockText;
- (BOOL)lockScreenViewPhonePluginIsActive;
- (void)lockScreenView:(id)fp8 didEndScrollingOnPage:(int)fp12;
- (void)lockScreenViewWillEndDraggingWithPercentScrolled:(float)fp8 percentScrolledVelocity:(float)fp12 targetScrollPercentage:(float)fp16;
- (void)lockScreenViewDidScrollWithNewScrollPercentage:(float)fp8 tracking:(BOOL)fp12;
- (void)lockScreenViewDidBeginScrolling:(id)fp8;
- (void)lockScreenView:(id)fp8 didScrollToPage:(int)fp12;
@end

