/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, SBAlertItem, SBLockScreenModalAlertView;

@interface SBLockScreenModalAlertViewController : _ABAddressBookCopyLocalizedLabel
{
    SBLockScreenModalAlertView *_modalAlertView;
    NSMutableArray *_pendingAlertItems;
    NSMutableArray *_pendingSuperModalAlertItems;
    SBAlertItem *_currentAlertItem;
}

- (void)pendOrDeactivateCurrentAlertItem;
- (void)_pendAlertItem:(id)fp8;
- (id)allPendingAlertItems;
- (BOOL)hasSuperModalAlertItems;
- (id)dequeueAllPendingSuperModalAlertItems;
- (id)currentAlertItem;
- (id)dequeueAllPendingAlertItems;
- (void)deactivateAlertItem:(id)fp8;
- (BOOL)activateAlertItem:(id)fp8 pended:(BOOL)fp12;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

