/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockOverlayView.h"

@class UIImageView;

@interface SBLockScreenTemperatureWarningView : SBLockOverlayView
{
    UIImageView *_warningIconView;
}

- (void)layoutSubviews;
- (float)_iconYPosition;
- (float)_subtitleBaseline;
- (float)_titleBaseline;
- (id)_subtitleFont;
- (id)_titleFont;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

