/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockOverlayViewController.h"

@class NSTimer;

@interface SBLockScreenDeviceBlockViewController : SBLockOverlayViewController
{
    NSTimer *_updateTimer;
}

- (void)_scheduleTimerIfNecessaryAndUpdateSubtitle;
- (void)_clearTimer;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (id)slideToUnlockText;
- (void)dealloc;

@end

