/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBFLockScreenDateView, SBFLockScreenSimpleDateFormatter, SBFakeStatusBarView, SBLegibilityView, UILabel, UIView, _UILegibilityLabel, _UILegibilitySettings;

@interface SBLockScreenPreviewView : _ABAddressBookCopyLocalizedLabel
{
    UIView *_wallpaperView;
    SBFLockScreenDateView *_dateView;
    SBLegibilityView *_cameraView;
    UILabel *_slideToUnlockView;
    _UILegibilityLabel *_slideToUnlockLegibilityLabel;
    SBFakeStatusBarView *_statusBar;
    SBFLockScreenSimpleDateFormatter *_dateFormatter;
    _UILegibilitySettings *_legibilitySettings;
}

+ (id)preview;
- (void)_layoutWallpaperView;
- (void)_layoutSlideToUnlockView;
- (void)_layoutDateView;
- (void)_layoutCameraView;
- (void)_layoutStatusBar;
- (void)layoutSubviews;
- (id)_legibilityPrototypeSettings;
- (void)_setupStatusBar;
- (void)_setupCameraView;
- (void)_setupDateView;
- (void)_setupSlideToUnlockView;
- (void)_setupWallpaperView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 legibilitySettings:(id)fp24;

@end

