/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class SBLockScreenNotificationCell;

@interface SBLockScreenNotificationScrollView : _ABAddressBookCopyLocalizedLabel <UIGestureRecognizerDelegate>
{
    SBLockScreenNotificationCell *_associatedCell;
}

+ (float)scrollThresholdForPasscodeScroll;
- (void)setAssociatedCell:(id)fp8;
- (id)associatedCell;

@end

