/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockScreenSlideUpController.h"

@class DeferredPUApplicationCameraViewController, NSDate, NSObject<OS_dispatch_queue>, SBPasscodeLockDisableAssertion, UIImageView, UIView;

@interface SBLockScreenCameraController : SBLockScreenSlideUpController
{
    UIView *_cameraClippingView;
    UIImageView *_cameraDefaultImageView;
    UIImageView *_cameraLandscapeDefaultImageView;
    UIView *_cameraBackgroundView;
    UIView *_cameraContainerView;
    UIView *_cameraFakeStatusBar;
    DeferredPUApplicationCameraViewController *_cameraViewController;
    BOOL _animatingCameraIn;
    BOOL _cancelCameraAnimation;
    BOOL _cameraModeActive;
    BOOL _cameraVisible;
    NSDate *_lastCameraSessionID;
    BOOL _exitedCameraForAlert;
    BOOL _exitedCameraToHomescreen;
    BOOL _restartCameraAfterCall;
    BOOL _disableGracePeriodForCamera;
    SBPasscodeLockDisableAssertion *_disableGracePeriodForCameraAssertion;
    NSObject<OS_dispatch_queue> *_prewarmQueue;
    id _savedWindowDelegate;
    BOOL _prewarming;
    id <SBLockScreenCameraControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)cameraView;
- (void)_didDeactivate;
- (void)_didActivate;
- (BOOL)isCameraVisible;
- (BOOL)isCameraActive;
- (void)abortDynamicAnimationForScreenOff;
- (void)tearDownCameraUIImmediately;
- (void)_disableRotationForCamera;
- (void)_enableRotationForCamera;
- (void)_dismissCameraAnimated:(BOOL)fp8;
- (void)_tearDownCameraPreview;
- (void)_removeCameraPreviewViews;
- (void)_activateCameraAfterCall;
- (void)prepareToReturnToCameraFromCall;
- (BOOL)shouldReturnToCameraAfterCall;
- (void)cancelReturnToCameraAfterCall;
- (void)noteStartingPhoneCallWhileUILocked;
- (void)presentCameraAnimated:(BOOL)fp8;
- (void)activateCamera;
- (void)setDisableGracePeriodForCamera:(BOOL)fp8;
- (void)_hideLockScreenView;
- (void)_activateCameraWithNewSessionID:(BOOL)fp8 afterCall:(BOOL)fp12;
- (void)_createCameraViewControllerWithOldSessionID;
- (void)_createCameraViewControllerWithNewSessionID;
- (void)_createCameraViewControllerWithNewSessionID:(BOOL)fp8 andStartPreview:(BOOL)fp12;
- (void)_setCameraSessionID:(id)fp8;
- (void)finalizeGesture;
- (void)translateSlidingViewByY:(float)fp8;
- (void)_setupCameraSlideDownAnimation;
- (void)cleanupFromGesture;
- (void)_cleanupFromDismissal;
- (void)prepareForSlideUpAnimation;
- (void)_removeLockScreenViewFakeStatusBar;
- (void)_cancelCameraPrewarm;
- (void)_prewarmCamera;
- (BOOL)handleMenuButtonTap;
- (void)deactivate;
- (void)activate;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)setInScreenOffMode:(BOOL)fp8;
- (BOOL)wantsStatusBar;
- (void)setGrabberOnLockScreen:(id)fp8;
- (id)grabberView;
- (void)setLockScreenView:(id)fp8;
- (void)dealloc;
- (id)init;

@end

