/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBLockScreenNotificationListDelegate <NSObject>
- (void)dismissFullscreenBulletinAlertWithItem:(id)fp8;
- (void)modifyFullscreenBulletinAlertWithItem:(id)fp8;
- (void)presentFullscreenBulletinAlertWithItem:(id)fp8;
- (id)lockScreenScrollView;
- (void)notificationListBecomingVisible:(BOOL)fp8;
- (void)attemptToUnlockUIFromNotification;
- (void)bannerEnablementChanged;
@end

