/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockOverlayContext.h"

@interface SBLockScreenPluginOverlayContext : SBLockOverlayContext
{
}

- (BOOL)_pluginNeedsOverlay:(id)fp8;
- (id)initWithPluginName:(id)fp8 pluginController:(id)fp12 lockScreenViewController:(id)fp16;

@end

