/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIColor, _UIBackdropViewSettings;

@interface SBLockOverlayStyleProperties : _ABAddressBookCopyLocalizedLabel
{
    UIColor *_primaryColor;
    UIColor *_secondaryColor;
    UIColor *_tintColor;
    float _tintAlpha;
    float _blurRadius;
    unsigned int _style;
    int _quality;
    _UIBackdropViewSettings *_settings;
}

- (float)blurRadius;
- (id)tintColor;
- (float)tintAlpha;
- (int)graphicsQuality;
- (unsigned int)style;
- (id)_stringForStyle;
- (id)_stringForQuality;
- (id)_settingsForStyle;
- (void)_configure;
- (id)description;
- (void)dealloc;
- (id)initWithStyle:(unsigned int)fp8 quality:(int)fp12;

@end

