/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSTimer, _UILegibilitySettings;

@interface SBLockScreenDateViewController : _ABAddressBookCopyLocalizedLabel
{
    NSTimer *_updateTimer;
    BOOL _disablesUpdates;
    _UILegibilitySettings *_legibilitySettings;
}

- (void)setLegibilitySettings:(id)fp8;
- (id)legibilitySettings;
- (BOOL)disablesUpdates;
- (void)setContentAlpha:(float)fp8 withDateVisible:(BOOL)fp12;
- (void)_startUpdateTimer;
- (void)_stopUpdateTimer;
- (void)_updateView;
- (id)dateViewIfExists;
- (id)dateView;
- (void)_updateFormat;
- (void)_addObservers;
- (void)_backlightChanged;
- (void)willMoveToParentViewController:(id)fp8;
- (void)setView:(id)fp8;
- (void)loadView;
- (void)setDisablesUpdates:(BOOL)fp8;
- (void)setDateHidden:(BOOL)fp8;
- (BOOL)isDateHidden;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

