/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockOverlayViewController.h"

@class SBAwayViewPluginController;

@interface SBLockScreenPluginOverlayViewController : SBLockOverlayViewController
{
    SBAwayViewPluginController *_pluginController;
}

- (id)_newOverlayView;
- (void)loadView;
- (void)dealloc;
- (id)initWithPluginController:(id)fp8;

@end

