/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBLockOverlayViewController;

@interface SBLockOverlayContext : _ABAddressBookCopyLocalizedLabel
{
    SBLockOverlayViewController *_viewController;
    unsigned int _priority;
    id _activationBlock;
    id _deactivationBlock;
}

- (void)setDeactivationBlock:(id)fp(null);
- (id)deactivationBlock;
- (void)setActivationBlock:(id)fp(null);
- (id)activationBlock;
- (unsigned int)priority;
- (id)viewController;
- (void)dealloc;
- (id)initWithOverlayViewController:(id)fp8 priority:(unsigned int)fp12;

@end

