/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBResponderTouchDelegate-Protocol.h"
#import "UIDynamicAnimatorDelegate-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSMutableSet, SBBounceBehavior, SBBounceSettings, SBBouncingItem, SBBouncingSystem, UIDynamicAnimator, UIGestureRecognizer, UIView;

@interface SBLockScreenBounceAnimator : _ABAddressBookCopyLocalizedLabel <UIDynamicAnimatorDelegate, _UISettingsKeyObserver, SBResponderTouchDelegate>
{
    NSMutableSet *_tapExcludedViews;
    BOOL _isAnimating;
    BOOL _bounceEnabled;
    UIView *_view;
    SBBouncingSystem *_system;
    UIDynamicAnimator *_animator;
    SBBouncingItem *_item;
    SBBounceBehavior *_behavior;
    UIGestureRecognizer *_tapRecognizer;
    UIGestureRecognizer *_panRecognizer;
    id _prepareBlock;
    id _translateBlock;
    id _canceledBlock;
    id _completedBlock;
    SBBounceSettings *_settings;
}

- (id)settings;
- (void)setCompletedBlock:(id)fp(null);
- (id)completedBlock;
- (void)setCanceledBlock:(id)fp(null);
- (id)canceledBlock;
- (void)setTranslateBlock:(id)fp(null);
- (id)translateBlock;
- (void)setPrepareBlock:(id)fp(null);
- (id)prepareBlock;
- (void)responder:(id)fp8 touchesCancelled:(id)fp12 withEvent:(id)fp16;
- (void)responder:(id)fp8 touchesEnded:(id)fp12 withEvent:(id)fp16;
- (void)responder:(id)fp8 touchesBegan:(id)fp12 withEvent:(id)fp16;
- (void)dynamicAnimatorDidPause:(id)fp8;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (void)_updateSettings;
- (void)setSettings:(id)fp8;
- (void)_createAnimator;
- (void)_removeAnimator;
- (void)_resetAnimator;
- (void)_beginAnimating;
- (void)_handlePanGesture:(id)fp8;
- (void)_handleTapGesture:(id)fp8;
- (void)_addPanRecognizer;
- (void)_removeTapRecognizer;
- (void)_addTapRecognizer;
- (id)tapExcludedViews;
- (void)removeTapExcludedView:(id)fp8;
- (void)addTapExcludedView:(id)fp8;
- (void)setBounceEnabled:(BOOL)fp8;
- (void)cancelAnimation;
- (BOOL)isAnimating;
- (void)dealloc;
- (id)initWithView:(id)fp8 allowPan:(BOOL)fp12;

@end

