/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLockScreenBulletinCell.h"

@interface SBLockScreenSystemAlertCell : SBLockScreenBulletinCell
{
}

+ (BOOL)wantsUnlockActionText;
+ (float)rowHeightForTitle:(id)fp8 body:(id)fp12 rowWidth:(float)fp16;
- (void)layoutSubviews;

@end

