/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSHashTable, NSMutableSet, SBLockScreenViewControllerBase, SBPasscodeEntryAlertViewController, SBPasscodeLockDisableAssertion;

@interface SBLockScreenManager : _ABAddressBookCopyLocalizedLabel
{
    SBLockScreenViewControllerBase *_lockScreenViewController;
    BOOL _isUILocked;
    BOOL _isWaitingToLockUI;
    BOOL _appRequestedPasscodeEntry;
    BOOL _uiHasBeenLockedOnce;
    SBPasscodeEntryAlertViewController *_passcodeEntryController;
    SBPasscodeLockDisableAssertion *_disablePasscodeLockWhileUIUnlockedAssertion;
    NSMutableSet *_disableLockScreenIfPossibleAssertions;
    NSHashTable *_disableUnlockAssertions;
    BOOL _isInLostMode;
    BOOL _biometricEventStartedWithScreenOff;
    unsigned long long _biometricEventStartTime;
    unsigned int _failedMesaUnlockAttempts;
    BOOL _bioAuthenticatedWhileMenuButtonDown;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNeeded:(BOOL)fp8;
- (BOOL)bioAuthenticatedWhileMenuButtonDown;
- (BOOL)isWaitingToLockUI;
- (BOOL)isUILocked;
- (id)lockScreenViewController;
- (void)_frontmostDisplayChanged:(id)fp8;
- (void)_lockScreenDimmed:(id)fp8;
- (void)_bioAuthenticated:(id)fp8;
- (BOOL)biometricEventMonitorShouldRelockAfterBioUnlock:(id)fp8;
- (void)biometricEventMonitor:(id)fp8 handleBiometricEvent:(unsigned int)fp12;
- (BOOL)handleMenuButtonTap;
- (BOOL)handleKeyHIDEvent:(struct __IOHIDEvent *)fp8;
- (void)activationChanged:(id)fp8;
- (void)enableLostModePlugin;
- (BOOL)isInLostMode;
- (void)exitLostModeIfNecessaryFromRemoteRequest:(BOOL)fp8;
- (void)activateLostModeForRemoteLock:(BOOL)fp8;
- (void)_lockFeaturesForRemoteLock:(BOOL)fp8;
- (void)remoteLock:(BOOL)fp8;
- (void)_resetOrRestoreStateChanged:(id)fp8;
- (void)_deviceBlockedChanged:(id)fp8;
- (void)_deviceLockedChanged:(id)fp8;
- (BOOL)attemptUnlockWithPasscode:(id)fp8;
- (void)startUIUnlockFromSource:(int)fp8 withOptions:(id)fp12;
- (void)_postLockCompletedNotification:(BOOL)fp8;
- (void)_removeDisableUnlockAssertion:(id)fp8;
- (void)_addDisableUnlockAssertion:(id)fp8;
- (void)updateSpringBoardStatusBarForLockScreenTeardown;
- (void)cancelApplicationRequestedDeviceLockEntry;
- (void)applicationRequestedDeviceUnlock;
- (void)removeLockScreenDisableAssertion:(id)fp8;
- (void)addLockScreenDisableAssertion:(id)fp8;
- (void)_handleExternalUIUnlock:(id)fp8;
- (void)_finishUIUnlockFromSource:(int)fp8 withOptions:(id)fp12;
- (void)unlockUIFromSource:(int)fp8 withOptions:(id)fp12;
- (BOOL)_shouldAutoUnlockFromUnlockSource:(int)fp8;
- (void)_sendUILockStateChangedNotification;
- (void)_lockUI;
- (void)_setUILocked:(BOOL)fp8;
- (void)_relockUIForButtonPress:(BOOL)fp8 afterCall:(BOOL)fp12;
- (void)_activateLockScreenAnimated:(BOOL)fp8 automatically:(BOOL)fp12 inScreenOffMode:(BOOL)fp16 dimInAnimation:(BOOL)fp20 dismissNotificationCenter:(BOOL)fp24;
- (void)lockUIFromSource:(int)fp8 withOptions:(id)fp12;
- (BOOL)shouldLockUIAfterEndingCall;
- (BOOL)_shouldLockAfterFaceTimeCall;
- (BOOL)_shouldLockAfterTelephonyCall;
- (BOOL)hasUIEverBeenLocked;
- (id)_newLockScreenController;
- (id)init;

@end

