/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "LSApplicationWorkspaceObserverProtocol-Protocol.h"

@class LSApplicationWorkspace, NSHashTable, NSMutableSet;

@interface SBLSApplicationWorkspaceObserver : _ABAddressBookCopyLocalizedLabel <LSApplicationWorkspaceObserverProtocol>
{
    LSApplicationWorkspace *_appWorkspace;
    NSHashTable *_applicationObservers;
    NSHashTable *_placeholderObservers;
    NSMutableSet *_placeholderProxies;
}

+ (id)sharedInstance;
- (void)setPlaceholderProxies:(id)fp8;
- (id)placeholderProxies;
- (id)workspace;
- (void)applicationInstallsDidPrioritize:(id)fp8;
- (void)applicationInstallsDidCancel:(id)fp8;
- (void)applicationInstallsDidResume:(id)fp8;
- (void)applicationInstallsDidPause:(id)fp8;
- (void)applicationInstallsArePrioritized:(id)fp8 arePaused:(id)fp12;
- (void)networkUsageChanged:(BOOL)fp8;
- (void)applicationInstallsDidUpdateIcon:(id)fp8;
- (void)applicationsDidUninstall:(id)fp8;
- (void)applicationsDidInstall:(id)fp8;
- (void)applicationInstallsDidChange:(id)fp8;
- (void)applicationInstallsDidStart:(id)fp8;
- (void)_removeObserver:(id)fp8 table:(id)fp12;
- (void)_addObserver:(id)fp8 table:(id)fp12;
- (void)removePlaceholderLifecycleObserver:(id)fp8;
- (void)addPlaceholderLifecycleObserver:(id)fp8;
- (void)removeApplicationLifecycleObserver:(id)fp8;
- (void)addApplicationLifecycleObserver:(id)fp8;
- (void)dealloc;
- (id)init;

@end

