/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertWindowViewController.h"

@interface SBMainScreenAlertWindowViewController : SBAlertWindowViewController
{
}

- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)noteAlertWindow:(id)fp8 didDisplayAlert:(id)fp12;
- (BOOL)alertWindow:(id)fp8 canAnimateInAlert:(id)fp12;

@end

