/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBSizeObservingViewDelegate-Protocol.h"
#import "_UISettingsKeyPathObserver-Protocol.h"

@class SBBulletinObserverViewController, SBModeControlManager, SBNotificationCenterSeparatorView, UIScrollView, UISwipeGestureRecognizer, UIView;

@interface SBModeViewController : _ABAddressBookCopyLocalizedLabel <SBSizeObservingViewDelegate, _UISettingsKeyPathObserver>
{
    id <SBBulletinActionHandler> _delegate;
    SBBulletinObserverViewController *_selectedViewController;
    UIScrollView *_contentView;
    UIView *_headerView;
    SBModeControlManager *_modeControl;
    UISwipeGestureRecognizer *_leftSwipeGestureRecognizer;
    UISwipeGestureRecognizer *_rightSwipeGestureRecognizer;
    SBNotificationCenterSeparatorView *_separator;
    struct {
        unsigned int isContentLayoutValid:1;
        unsigned int isSegmentLayoutValid:1;
        unsigned int isRequestHandlingEnabled:1;
        unsigned int shouldLoadAllChildViews:1;
    } _modeViewControllerFlags;
}

+ (float)_minScreenDimension;
+ (id)_buttonTitleFont;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)settings:(id)fp8 changedValueForKeyPath:(id)fp12;
- (void)hostDidDismiss;
- (void)hostWillDismiss;
- (void)hostDidPresent;
- (void)hostWillPresent;
- (void)setWidgetDelegate:(id)fp8;
- (id)widgetDelegate;
- (BOOL)handleActionForBulletin:(id)fp8;
- (struct CGRect)rectForBulletin:(id)fp8;
- (void)setRequestHandlingEnabled:(BOOL)fp8;
- (BOOL)isRequestHandlingEnabled;
- (BOOL)_isRequestHandlingEnabled;
- (void)handleModeChange:(id)fp8;
- (void)setViewControllers:(id)fp8;
- (id)viewControllers;
- (void)setSelectedViewController:(id)fp8;
- (id)selectedViewController;
- (void)setSelectedViewController:(id)fp8 animated:(BOOL)fp12;
- (void)_setSelectedBulletinObserverViewController:(id)fp8 animated:(BOOL)fp12;
- (BOOL)_contentOffset:(struct CGPoint *)fp8 forChildViewController:(id)fp12;
- (void)removeViewController:(id)fp8;
- (void)addViewController:(id)fp8;
- (BOOL)_addBulletinObserverViewController:(id)fp8;
- (void)_setSelectedSegmentIndex:(int)fp8;
- (void)sizeObservingView:(id)fp8 didChangeSize:(struct CGSize)fp12;
- (void)_invalidateSegmentLayout;
- (void)_invalidateContentLayout;
- (void)viewWillAppear:(BOOL)fp8;
- (id)_viewIfLoaded;
- (void)viewWillLayoutSubviews;
- (void)_layoutContentIfNecessary;
- (void)_setContentViewContentOffset:(struct CGPoint)fp8 animated:(BOOL)fp16;
- (void)_layoutSegmentsIfNecessary;
- (void)_layoutHeaderViewIfNecessary;
- (void)_backgroundContrastDidChange:(id)fp8;
- (void)viewDidLoad;
- (void)loadView;
- (void)_loadContentView;
- (id)_newSwipeGestureRecognizerWithDirection:(unsigned int)fp8;
- (void)_loadHeaderView;
- (float)_headerViewHeightForMode:(int)fp8;
- (struct CGRect)_modeControlFrameWithHeaderBounds:(struct CGRect)fp8 forMode:(int)fp24;
- (struct CGSize)_modeControlSizeForMode:(int)fp8;
- (int)_layoutMode;
- (void)dealloc;

@end

