/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconLabelImageParameters.h"

@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters
{
}

- (void)setStyle:(int)fp8;
- (void)setContainsEmoji:(BOOL)fp8;
- (void)setCanEllipsize:(BOOL)fp8;
- (void)setContainsNonLatinLikeCharacters:(BOOL)fp8;
- (void)setFont:(id)fp8;
- (void)setMaxSize:(struct CGSize)fp8;
- (void)setText:(id)fp8;
- (id)copy;

@end

