/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconView.h"

@interface SBNewsstandItemIconView : SBIconView
{
}

+ (struct CGSize)defaultIconSize;
+ (int)_defaultIconFormat;
- (struct CGRect)_frameForUpdatedMarkWithLabelFrame:(struct CGRect)fp8;
- (struct CGRect)_frameForLabel;
- (struct CGRect)_baseFrameForLabel;
- (struct CGRect)_frameForImageView;
- (struct CGRect)_baseFrameForImageView;
- (BOOL)_showsShadow;
- (id)initWithFrame:(struct CGRect)fp8;

@end

