/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUserInstalledApplicationIcon.h"

@class SBNewsstandApplication;

@interface SBNewsstandApplicationIcon : SBUserInstalledApplicationIcon
{
    SBNewsstandApplication *_fakeApp;
}

- (void)setFakeApp:(id)fp8;
- (id)fakeApp;
- (id)getGenericIconImage:(int)fp8;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)isNewsstandApplicationIcon;
- (int)iconFormatForLocation:(int)fp8;
- (void)launchFromLocation:(int)fp8;
- (BOOL)launchEnabled;
- (id)application;
- (BOOL)shouldWarmUp;
- (void)dealloc;
- (id)initWithApplication:(id)fp8;
- (Class)iconImageViewClassForLocation:(int)fp8;
- (Class)iconViewClassForLocation:(int)fp8;

@end

