/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, UIImageView, UIView;

@interface SBNewsstandBackgroundView : _ABAddressBookCopyLocalizedLabel
{
    NSMutableArray *_shelfViews;
    UIImageView *_overlayGradientView;
    UIView *_bottomView;
}

+ (float)shelfHeightForOrientation:(int)fp8;
+ (float)baselineForShelfAtIndex:(unsigned int)fp8 withOrientation:(int)fp12;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

