/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFolderIcon.h"

@interface SBNewsstandIcon : SBFolderIcon
{
}

- (BOOL)hasFolderIconView;
- (BOOL)isNewsstandIcon;
- (id)getUnmaskedIconImage:(int)fp8;
- (id)generateIconImage:(int)fp8;
- (id)_generateImageUsingMask:(BOOL)fp8;
- (id)_newsstandIconImageName;
- (id)folder;
- (void)launchFromLocation:(int)fp8;
- (id)leafIdentifier;
- (id)displayName;

@end

