/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBGradientView.h"

@class SBHighlightView, UIView;

@interface SBNewsstandShelfView : SBGradientView
{
    UIView *_tintView;
    float _tintAlpha;
    SBHighlightView *_highlightView;
    unsigned int _shelfIndex;
}

- (unsigned int)shelfIndex;
- (void)layoutSubviews;
- (void)setShelfIndex:(unsigned int)fp8;
- (float)tintAlpha;
- (void)setTintAlpha:(float)fp8;
- (id)tintColor;
- (void)setTintColor:(id)fp8;
- (void)dealloc;

@end

