/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBNotificationCell.h"

@class SBNotificationCenterSeparatorView;

@interface SBNotificationsBulletinCell : SBNotificationCell
{
    SBNotificationCenterSeparatorView *_separator;
    BOOL _missed;
}

+ (id)defaultColorForRelevanceDate;
+ (struct CGSize)_preferredSizeForRelevanceDateLabel:(id)fp8;
+ (float)iconPaddingLeft;
- (void)setMissed:(BOOL)fp8;
- (BOOL)isMissed;
- (struct CGRect)_separatorFrame;
- (void)setSectionLocation:(int)fp8 animated:(BOOL)fp12;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setShowsSeparator:(BOOL)fp8;
- (BOOL)showsSeparator;
- (void)setEventDateLabel:(id)fp8;
- (void)setRelevanceDateLabel:(id)fp8;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

