/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBBounceSettings;

@interface SBNotificationCenterSettings : _ABAddressBookCopyLocalizedLabel
{
    SBBounceSettings *_bounceSettings;
    float _modeButtonTintLevel;
    float _modeButtonTintAlpha;
    float _modeLabelTintLevel;
    float _modeLabelTintAlpha;
    double _grabberAnimationDuration;
}

+ (id)settingsControllerModule;
- (void)setModeLabelTintAlpha:(float)fp8;
- (float)modeLabelTintAlpha;
- (void)setModeLabelTintLevel:(float)fp8;
- (float)modeLabelTintLevel;
- (void)setModeButtonTintAlpha:(float)fp8;
- (float)modeButtonTintAlpha;
- (void)setModeButtonTintLevel:(float)fp8;
- (float)modeButtonTintLevel;
- (void)setGrabberAnimationDuration:(double)fp8;
- (double)grabberAnimationDuration;
- (void)setBounceSettings:(id)fp8;
- (id)bounceSettings;
- (void)setDefaultValues;

@end

