/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBNotificationsModeViewController.h"

#import "UIGestureRecognizerDelegatePrivate-Protocol.h"

@class SBNotificationCenterTouchEater, SBNotificationsSectionHeaderView;

@interface SBNotificationsAllModeViewController : SBNotificationsModeViewController <UIGestureRecognizerDelegatePrivate>
{
    SBNotificationCenterTouchEater *_clearButtonTouchEater;
    SBNotificationsSectionHeaderView *_headerViewCurrentlyInClearState;
}

- (void)commitReloadOfSections:(id)fp8;
- (id)infoForBulletin:(id)fp8 inSection:(id)fp12;
- (id)infoForBulletinSection:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)_handleEatenTouch:(id)fp8;
- (void)_setHeaderViewCurrentlyInClearState:(id)fp8;
- (id)_headerViewCurrentlyInClearState;
- (struct UIEdgeInsets)bulletinViewControllerContentInsetsForMode:(int)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)_installClearButtonTouchEater;
- (int)widgetIdiomForCategory:(int)fp8;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

