/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBRemoteDataProvider-Protocol.h"

@class BBSectionInfo;

@interface SBNotificationCenterDataProvider : _ABAddressBookCopyLocalizedLabel <BBRemoteDataProvider>
{
    BBSectionInfo *_sectionInfo;
}

+ (id)notificationCenterDataProviderWithSectionInfo:(id)fp8;
- (id)bulletinsWithRequestParameters:(id)fp8 lastCleared:(id)fp12;
- (id)sortDescriptors;
- (id)defaultSectionInfo;
- (id)sectionIdentifier;
- (void)dealloc;
- (id)initWithSectionInfo:(id)fp8;

@end

