/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBBBulletinInfo.h"

@class SBNotificationsSectionInfo, UIColor, UIImage;

@interface SBNotificationsBulletinInfo : SBBBBulletinInfo
{
    SBNotificationsSectionInfo *_sectionInfo;
    float _heightForReusableView;
    struct CGSize _referenceSize;
    UIImage *_icon;
    UIImage *_attachmentImage;
    struct CGSize _attachmentImageSize;
    float _secondaryTextHeight;
    BOOL _suppressingMessageForPrivacy;
    BOOL _isCachedMessageSuppressionValid;
    UIColor *_secondaryTextColor;
}

- (id)secondaryTextColor;
- (void)setSectionInfo:(id)fp8;
- (id)sectionInfo;
- (void)setAttachmentImageSize:(struct CGSize)fp8;
- (struct CGSize)attachmentImageSize;
- (void)setAttachmentImage:(id)fp8;
- (id)attachmentImage;
- (void)setIcon:(id)fp8;
- (id)icon;
- (void)populateReusableView:(id)fp8;
- (float)heightForReusableViewInTableView:(id)fp8;
- (BOOL)_isLayoutValidWithReferenceSize:(struct CGSize)fp8;
- (struct CGSize)_effectiveAttachmentImageSize;
- (id)_attachmentImageToDisplay;
- (id)_eventDateLabelForDisplay;
- (id)_eventDateLabel;
- (void)_configureEventDateLabel:(id)fp8;
- (id)_relevanceDateLabel;
- (void)_configureRelevanceDateLabel:(id)fp8;
- (CDAnonymousStruct8)_relevanceDateLabelDescription;
- (id)_endDate;
- (id)_secondaryTextColor;
- (id)_secondaryTextToDisplay;
- (id)_secondaryText;
- (id)_subtitleTextColor;
- (id)_subtitleTextToDisplay;
- (id)_subtitleText;
- (id)_relevanceDateTextColor;
- (id)_primaryTextColor;
- (BOOL)isSuppressingMessageForPrivacy;
- (id)_primaryText;
- (void)invalidateCachedLayoutData;
- (Class)reusableViewClass;
- (id)identifier;
- (void)dealloc;

@end

