/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPanGestureRecognizer.h"

#import "_UIScreenEdgePanRecognizerDelegate-Protocol.h"

@class _UIScreenEdgePanRecognizer;

@interface SBOffscreenSwipeGestureRecognizer : SBPanGestureRecognizer <_UIScreenEdgePanRecognizerDelegate>
{
    unsigned int m_offscreenEdge;
    BOOL m_shouldUseUIKitHeuristics;
    float m_edgeMargin;
    float m_falseEdge;
    int m_touchesChecked;
    struct CGPoint m_firstTouch;
    float m_edgeCenter;
    float m_allowableDistanceFromEdgeCenter;
    BOOL m_requiresSecondTouchInRange;
    _UIScreenEdgePanRecognizer *m_recognizer;
}

+ (void)reloadDefaults;
- (void)setEdgeCenter:(float)fp8;
- (float)edgeCenter;
- (void)setRequiresSecondTouchInRange:(BOOL)fp8;
- (BOOL)requiresSecondTouchInRange;
- (void)setAllowableDistanceFromEdgeCenter:(float)fp8;
- (float)allowableDistanceFromEdgeCenter;
- (float)falseEdge;
- (void)setEdgeMargin:(float)fp8;
- (float)edgeMargin;
- (void)setShouldUseUIKitHeuristics:(BOOL)fp8;
- (BOOL)shouldUseUIKitHeuristics;
- (void)screenEdgePanRecognizerStateDidChange:(id)fp8;
- (void)updateForBeganOrMovedTouches:(struct __SBGestureContext *)fp8;
- (void)setState:(int)fp8;
- (void)_updateAnimationDistanceAndEdgeCenter;
- (BOOL)secondTouchQualifies:(const CDAnonymousStruct11 *)fp8;
- (struct CGRect)activeScreenBounds;
- (BOOL)firstTouchQualifies:(const CDAnonymousStruct11 *)fp8;
- (BOOL)_firstTouchInRange:(const CDAnonymousStruct11 *)fp8;
- (void)setFalseEdge:(float)fp8;
- (void)dealloc;
- (void)reset;
- (BOOL)isHandlingLongPress;
- (id)settings;
- (void)setSettings:(id)fp8;
- (id)initForOffscreenEdge:(unsigned int)fp8;

@end

