/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSHashTable, NSMutableArray, NSString, SBOperation;

@interface SBOperationQueue : _ABAddressBookCopyLocalizedLabel
{
    NSString *_name;
    NSMutableArray *_operationQueue;
    NSHashTable *_operationLocks;
    SBOperation *_executingOperation;
}

- (void)setExecutingOperation:(id)fp8;
- (id)executingOperation;
- (void)_processNextOperationIfNecessary;
- (void)_executeOrPendOperations:(id)fp8;
- (void)_removeOperationQueueLock:(id)fp8;
- (void)_addOperationQueueLock:(id)fp8;
- (id)description;
- (void)executeOrAppendOperation:(id)fp8;
- (id)acquireLockForReason:(id)fp8;
- (BOOL)isLocked;
- (void)dealloc;
- (id)initWithName:(id)fp8;

@end

