/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableSet;

@interface SBPasscodeLockAssertionTracker : _ABAddressBookCopyLocalizedLabel
{
    struct __MKBAssertion *_mkbAssertion;
    NSMutableSet *_assertions;
}

- (id)description;
- (id)mkbAssertionOptions;
- (BOOL)hasActiveAssertions;
- (void)removeAssertion:(id)fp8;
- (void)addAssertion:(id)fp8;
- (void)dealloc;
- (id)init;

@end

