/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

#import "SBUIPasscodeLockViewDelegate-Protocol.h"

@interface SBPasscodeEntryAlertViewController : SBAlert <SBUIPasscodeLockViewDelegate>
{
    BOOL _attemptingUnlock;
}

- (void)passcodeLockViewCancelButtonPressed:(id)fp8;
- (void)passcodeLockViewPasscodeEnteredViaMesa:(id)fp8;
- (void)passcodeLockViewPasscodeEntered:(id)fp8;
- (void)passcodeLockViewPasscodeDidChange:(id)fp8;
- (void)deactivate;
- (BOOL)hasTranslucentBackground;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;

@end

