/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBVolumePressBandit-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSArray, PTSettingsController, SBRootSettings, UIWindow;

@interface SBPrototypeController : _ABAddressBookCopyLocalizedLabel <SBVolumePressBandit, _UISettingsKeyObserver>
{
    SBRootSettings *_rootSettings;
    UIWindow *_settingsWindow;
    PTSettingsController *_settingsController;
    NSArray *_testRecipeClassNames;
    id <SBTestRecipe> _activeTestRecipe;
    BOOL _showingSettings;
    BOOL _hasPreviousSettings;
}

+ (id)sharedInstance;
+ (void)migrateSettings;
+ (void)reloadDefaults;
- (void)_updatePreventingLockover;
- (void)_configureForDefaults;
- (void)_changeActiveTestRecipeIfNecessary;
- (void)_tearDownSettingsWindow;
- (struct CGRect)_offscreenFrame;
- (void)_hideSettings;
- (void)_showSettings;
- (id)_testRecipeClassNames;
- (BOOL)_restorePreviousSettings;
- (BOOL)_hasPreviousSettings;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)setActiveTestRecipe:(id)fp8;
- (void)showOrHide;
- (BOOL)isPrototypingEnabled;
- (id)activeTestRecipe;
- (BOOL)isShowingSettingsUI;
- (id)rootSettings;
- (void)dealloc;
- (id)init;

@end

