/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "APSConnectionDelegate-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSString;

@interface SBRemoteNotificationServer : _ABAddressBookCopyLocalizedLabel <APSConnectionDelegate>
{
    NSMutableDictionary *_bundleIdentifiersToClients;
    NSMutableDictionary *_environmentsToConnections;
    NSMutableSet *_bundleIdentifiersNeedingToken;
    NSString *_lastNotificationReceivedBundleIdentifier;
    NSMutableDictionary *_appImportanceTracker;
}

+ (id)sharedInstance;
- (id)_allPushRegisteredThirdPartyBundleIDs;
- (void)clearMessageUserInfoForToken:(int)fp8 forBundleIdentifier:(id)fp12;
- (id)getMessageUserInfoForToken:(int)fp8 forBundleIdentifier:(id)fp12;
- (id)getMessageUserInfoForBundleIdentifier:(id)fp8;
- (void)setMessageUserInfo:(id)fp8 forToken:(int)fp12 forBundleIdentifier:(id)fp16;
- (void)setMessageUserInfo:(id)fp8 forBundleIdentifier:(id)fp12;
- (void)postSettingsChangedNotificationForBundleIdentifier:(id)fp8;
- (void)setSettingsTypes:(unsigned int)fp8 forBundleIdentifier:(id)fp12;
- (unsigned int)settingsEnabledTypesForBundleIdentifier:(id)fp8;
- (unsigned int)appEnabledTypesForBundleIdentifier:(id)fp8;
- (void)notePermissionAlertAcceptedTypes:(unsigned int)fp8 forBundleIdentifier:(id)fp12;
- (BOOL)hasRegisteredBundleIdentifiers;
- (void)setSystemwideEnabled:(BOOL)fp8;
- (BOOL)isSystemwideEnabled;
- (unsigned int)getEffectiveEnabledTypesForApplication:(id)fp8;
- (void)unregisterApplication:(id)fp8;
- (void)registerApplication:(id)fp8 forEnvironment:(id)fp12 withTypes:(unsigned int)fp16;
- (id)_allTopicsForApplication:(id)fp8;
- (id)_cloudDatabaseTopicsForApplication:(id)fp8;
- (void)calculateTopics;
- (void)_appDebugStateDidChange:(id)fp8;
- (void)_appStateDidChange:(id)fp8;
- (void)_appImportanceDecreased:(id)fp8;
- (void)_appImportanceIncreased:(id)fp8;
- (void)_moveTopicsForApp:(id)fp8 fromList:(unsigned int)fp12 toList:(unsigned int)fp16;
- (id)allSettingsEnabledTypeValues;
- (id)allAppEnabledTypeValues;
- (id)lastNotificationReceivedBundleIdentifier;
- (void)connection:(id)fp8 didReceiveIncomingMessage:(id)fp12;
- (void)connection:(id)fp8 didReceivePublicToken:(id)fp12;
- (void)connection:(id)fp8 didReceiveToken:(id)fp12 forTopic:(id)fp16 identifier:(id)fp20;
- (void)run;
- (void)dealloc;
- (id)init;

@end

