/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFolderController.h"

@interface SBRootFolderController : SBFolderController
{
}

- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8;
- (BOOL)_listIndexIsVisible:(unsigned int)fp8;
- (void)setDockVerticalStretch:(float)fp8;
- (void)setDockOffscreenFraction:(float)fp8;
- (id)dockListView;
- (BOOL)hasDock;
- (BOOL)isDisplayingIcon:(id)fp8;
- (void)setIdleText:(id)fp8;
- (BOOL)setCurrentPageIndex:(int)fp8 animated:(BOOL)fp12;
- (id)folderControllers;
- (unsigned int)_depth;
- (Class)_contentViewClass;
- (void)dealloc;
- (id)initWithFolder:(id)fp8 orientation:(int)fp12;

@end

