/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSHashTable, NSMapTable;

@interface SBScreenManager : _ABAddressBookCopyLocalizedLabel
{
    NSHashTable *_handlers;
    NSMapTable *_screenIDToHandlerMap;
    NSMapTable *_screenIDToObserversMap;
    NSMapTable *_screenIDToSuppressionReasonsMap;
    NSMapTable *_screenIDToMainWindowMap;
    NSMapTable *_screenIDToScreenMap;
    NSHashTable *_connectedScreenIDs;
}

+ (id)sharedInstance;
- (void)setMainWindow:(id)fp8 forScreen:(id)fp12;
- (void)addConnectionHandler:(id)fp8;
- (BOOL)isScreenSuppressed:(id)fp8;
- (BOOL)isScreenConnected:(id)fp8;
- (id)mainWindowForScreen:(id)fp8;
- (id)screenWithID:(unsigned int)fp8;
- (void)removeSuppressionReason:(id)fp8 forScreen:(id)fp12;
- (void)addSuppressionReason:(id)fp8 forScreen:(id)fp12;
- (void)removeScreenObserver:(id)fp8 forScreen:(id)fp12;
- (void)addScreenObserver:(id)fp8 forScreen:(id)fp12;
- (void)_screenDidDisconnect:(id)fp8;
- (void)_screenDidConnect:(id)fp8;
- (void)_updateHandlerForConnectionToScreen:(id)fp8;
- (void)dealloc;
- (id)init;

@end

