/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBFLockScreenDateView, SBFadeAnimationSettings, SBLockScreenView, UIView, UIWindow;

@interface SBScreenFadeAnimationController : _ABAddressBookCopyLocalizedLabel
{
    UIWindow *_fadeWindow;
    UIView *_overlayView;
    SBFLockScreenDateView *_dateView;
    float _originalDateLeftEdge;
    float _originalDateBottomEdge;
    float _finalTimeAlpha;
    float _finalDateAlpha;
    float _finalStatusBarAlpha;
    SBLockScreenView *_lockScreenView;
    BOOL _preparingToAnimateFadeIn;
    BOOL _animatingForFadeIn;
    BOOL _animatingForFadeOut;
    int _animationToken;
    id _fadeInCompletionBlock;
    id _fadeOutCompletionBlock;
    BOOL _animatingDateTime;
    BOOL _animatingWallpaper;
    BOOL _animatingOverlay;
    BOOL _animatingContent;
    SBFadeAnimationSettings *_settings;
}

+ (id)sharedInstance;
- (void)setLegibilitySettings:(id)fp8;
- (void)setTextColor:(id)fp8;
- (void)hideDate;
- (void)setDateViewAlpha:(float)fp8;
- (void)_runCompletionHandlerForFadeIn:(BOOL)fp8;
- (void)_handleAnimationCompletionIfNecessaryForFadeIn:(BOOL)fp8;
- (void)fadeOutWithCompletion:(id)fp(null);
- (void)_startFadeAnimationsForFadeIn:(BOOL)fp8;
- (void)_cleanupAnimationWhenInterruptingFadeIn:(BOOL)fp8;
- (void)_assistantVisibilityChanged;
- (void)_mediaControlsDidShow;
- (void)_blankScreenStateChanged;
- (void)_startFadeInIfNecessary;
- (void)prepareToFadeInWithTimeAlpha:(float)fp8 dateAlpha:(float)fp12 statusBarAlpha:(float)fp16 lockScreenView:(id)fp20 existingDateView:(id)fp24 completion:(id)fp(null);
- (void)_setRelevantLockScreenViewsHidden:(BOOL)fp8;
- (void)_adjustViewsForCurrentOrientation;
- (void)updateDateFrameHorizontalOffset:(float)fp8 verticalOffset:(float)fp12;
- (BOOL)isFadeOutAnimationInProgress;
- (BOOL)isFadeInAnimationInProgress;
- (void)_createFadeWindowForFadeIn:(BOOL)fp8;
- (double)fadeOutAnimationDuration;
- (double)fadeInAnimationDuration;
- (void)dealloc;
- (id)init;

@end

