/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBScreenObserver <NSObject>
- (void)screenManager:(id)fp8 didReconnectScreen:(id)fp12;
- (void)screenManager:(id)fp8 didDisconnectScreen:(id)fp12;
- (void)screenManager:(id)fp8 didChangeSuppressionOfScreen:(id)fp12;
@end

