/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconZoomSettings.h"

@class SBFAnimationSettings;

@interface SBScaleZoomSettings : SBIconZoomSettings
{
    BOOL _crossfadeWithZoom;
    SBFAnimationSettings *_outerFolderFadeSettings;
    SBFAnimationSettings *_crossfadeSettings;
}

+ (id)settingsControllerModule;
- (void)setCrossfadeSettings:(id)fp8;
- (id)crossfadeSettings;
- (void)setCrossfadeWithZoom:(BOOL)fp8;
- (BOOL)crossfadeWithZoom;
- (void)setOuterFolderFadeSettings:(id)fp8;
- (id)outerFolderFadeSettings;
- (id)effectiveCrossfadeAnimationSettings;
- (void)setDefaultValues;

@end

