/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconZoomAnimator.h"

@class SBIcon, UIView;

@interface SBScaleIconZoomAnimator : SBIconZoomAnimator
{
    struct UIEdgeInsets _iconScootch;
    float _dockStretch;
    struct SBIconCoordinate _dockListCenterCoordinate;
    struct SBIconCoordinate _mainListCenterCoordinate;
    float _naturalVisualAltitude;
    UIView *_scalingView;
    SBIcon *_targetIcon;
    float _zoomScale;
}

- (float)zoomScale;
- (id)targetIcon;
- (void)_calculateIconScootch;
- (struct CGPoint)_scootchForIcon:(id)fp8 inDock:(BOOL)fp12;
- (void)_applyOuterFadeFraction:(float)fp8;
- (void)_applyZoomFraction:(float)fp8;
- (float)_zoomedVisualAltitude;
- (struct CGPoint)_zoomedIconCenter;
- (struct CGRect)_zoomedFrame;
- (void)_animateToFraction:(float)fp8 afterDelay:(double)fp12 withSharedCompletion:(id)fp(null);
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)fp8;
- (void)_prepareAnimation;
- (id)targetIconView;
- (void)dealloc;
- (id)initWithFolderController:(id)fp8 targetIcon:(id)fp12;

@end

