/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBSearchGestureObserver-Protocol.h"

@class SBWallpaperEffectView, UIButton, UITextField, UIView;

@interface SBSearchHeader : _ABAddressBookCopyLocalizedLabel <SBSearchGestureObserver>
{
    SBWallpaperEffectView *_blurView;
    UIView *_container;
    UIButton *_cancelButton;
    UITextField *_searchField;
    id <SBSearchHeaderDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)searchField;
- (void)searchGesture:(id)fp8 changedPercentComplete:(float)fp12;
- (void)_cancelButtonPressed;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

