/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SPDaemonQueryDelegate-Protocol.h"

@class CPLRUDictionary, NSDate, NSObject<OS_dispatch_semaphore>, NSOperation, NSOperationQueue, NSTimer;

@interface SBSearchModel : _ABAddressBookCopyLocalizedLabel <SPDaemonQueryDelegate>
{
    NSTimer *_clearSearchTimer;
    NSDate *_clearSearchDate;
    CPLRUDictionary *_cachedResultImages;
    NSObject<OS_dispatch_semaphore> *_cacheResultLock;
    NSOperationQueue *_prefetchOperationQueue;
    NSOperationQueue *_loadOperationQueue;
    NSOperation *_waitOperation;
    void *_addressBook;
}

+ (id)sharedInstance;
- (id)currentToken;
- (id)operationFetchingImageForResult:(id)fp8 inSection:(id)fp12 withCompletionBlock:(id)fp(null);
- (BOOL)prefetchImageForResult:(id)fp8 inSection:(id)fp12;
- (void)cancelPrefetchingAndStartNewBatch;
- (id)cachedImageForResult:(id)fp8 inSection:(id)fp12;
- (void)fetchImageForResult:(id)fp8 inSection:(id)fp12 withCompletionBlock:(id)fp(null);
- (void)_cacheImage:(id)fp8 forKey:(id)fp12 withCompletionBlock:(id)fp(null);
- (id)_imageForResult:(id)fp8 inSection:(id)fp12 withCompletionBlock:(id)fp(null);
- (id)_uniqueKeyForResult:(id)fp8 withSearchDomain:(unsigned int)fp12;
- (id)_customImageForPath:(id)fp8;
- (void)handleOptionsForNewSections:(id)fp8;
- (void)invalidate;
- (id)launchingURLForResult:(id)fp8 withDisplayIdentifier:(id)fp12 andSection:(id)fp16;
- (void)_updateClearSearchTimerFireDate;
- (void)startClearSearchTimer;
- (void)_clearSearchTimerFired;
- (void)resetClearSearchTimer;
- (void)dealloc;
- (id)init;

@end

