/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBSearchGestureObserver-Protocol.h"
#import "SBSearchHeaderDelegate-Protocol.h"
#import "SPSearchAgentDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class SBSearchHeader, SBSearchResultsBackdropView, UIImage, UILabel, UIPanGestureRecognizer, UITableView, UITapGestureRecognizer, UIView;

@interface SBSearchViewController : _ABAddressBookCopyLocalizedLabel <UITableViewDelegate, UITableViewDataSource, SPSearchAgentDelegate, SBSearchGestureObserver, UISearchBarDelegate, SBSearchHeaderDelegate>
{
    SBSearchHeader *_searchHeader;
    SBSearchResultsBackdropView *_tableBackdrop;
    UITableView *_tableView;
    UILabel *_noResultsLabel;
    UIView *_touchStealingView;
    UITapGestureRecognizer *_tapRecognizer;
    UIPanGestureRecognizer *_panRecognizer;
    void *_addressBook;
    UIImage *_placeHolderImages[15];
    float _lastContentOffsetY;
    BOOL _scrollDown;
    BOOL _hasShownBackgroundSinceLastClear;
    id _fadeOutCompletionBlock;
    BOOL _fadingOut;
    BOOL _visible;
}

+ (id)sharedInstance;
- (BOOL)isVisible;
- (BOOL)isFadingOut;
- (void)cancelButtonPressed;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)_searchFieldReturnPressed;
- (void)_searchFieldEditingChanged;
- (void)searchGesture:(id)fp8 completedShowing:(BOOL)fp12;
- (void)searchGesture:(id)fp8 changedPercentComplete:(float)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (BOOL)tableView:(id)fp8 wantsHeaderForSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didUnhighlightRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didHighlightRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)searchAgentClearedResults:(id)fp8;
- (void)searchAgentUpdatedResults:(id)fp8;
- (void)_resizeTableViewForPreferredContentSizeChange:(id)fp8;
- (void)_keyboardWillChangeFrame:(id)fp8;
- (void)_handlePanRecognizer:(id)fp8;
- (void)_handleTapRecognizer:(id)fp8;
- (void)_handleDismissGesture;
- (void)_fadeOutAndHideKeyboardIfNecessary:(id)fp(null);
- (void)_fadeForLaunchWithDuration:(double)fp8 completion:(id)fp(null);
- (void)_deselectTableViewCell;
- (void)_updateTableContents;
- (void)_startDownloadingAppForStoreIdentifier:(unsigned long long)fp8 bundleIdentifier:(id)fp16;
- (void)_populateCell:(id)fp8 atIndexPath:(id)fp12 inTableView:(id)fp16;
- (BOOL)_shouldDisplayImagesForDomain:(unsigned int)fp8;
- (id)_auxiliaryTitleForABRecordID:(int)fp8;
- (id)_placeHolderImageForDomain:(unsigned int)fp8;
- (BOOL)_hasNoResultsForQuery;
- (BOOL)_hasResults;
- (BOOL)_showingKeyboard;
- (void)_setShowingKeyboard:(BOOL)fp8;
- (void)dismiss;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

