/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBShapeView : _ABAddressBookCopyLocalizedLabel
{
}

+ (Class)layerClass;
- (id)_shapeLayer;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)setFillRule:(int)fp8;
- (void)setFillColor:(id)fp8;
- (void)setPath:(id)fp8;

@end

