/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "_UISettingsKeyObserver-Protocol.h"

@class SBSlideToUnlockTriangleView, UIView;

@interface SBSlideToUnlockFailureRecognizer : _ABAddressBookCopyLocalizedLabel <_UISettingsKeyObserver>
{
    struct CGPoint _startingLocation;
    unsigned int _maxAllowableVerticalOffset;
    float _maxAllowedTopAngle;
    float _minAllowedTopAngle;
    float _effectiveTopAngle;
    float _minAllowedBottomAngle;
    float _maxAllowedBottomAngle;
    float _effectiveBottomAngle;
    BOOL _tracking;
    BOOL _allowMultiTouch;
    BOOL _viewDebugArea;
    UIView *_relativeView;
    UIView *_debugHorizontalView;
    SBSlideToUnlockTriangleView *_debugInclineUpView;
    SBSlideToUnlockTriangleView *_debugInclineDownView;
}

- (void)setRelativeView:(id)fp8;
- (void)setViewDebugArea:(BOOL)fp8;
- (BOOL)viewDebugArea;
- (void)setMinAllowedBottomAngle:(float)fp8;
- (float)minAllowedBottomAngle;
- (void)setMaxAllowedBottomAngle:(float)fp8;
- (float)maxAllowedBottomAngle;
- (void)setMinAllowedTopAngle:(float)fp8;
- (float)minAllowedTopAngle;
- (void)setMaxAllowedTopAngle:(float)fp8;
- (float)maxAllowedTopAngle;
- (void)setMaxAllowableVerticalOffset:(unsigned int)fp8;
- (unsigned int)maxAllowableVerticalOffset;
- (void)setAllowMultiTouch:(BOOL)fp8;
- (BOOL)allowMultiTouch;
- (void)_setDebugViewsVisible:(BOOL)fp8;
- (BOOL)_isLocationOutOfBounds:(struct CGPoint)fp8;
- (BOOL)_isOutOfBounds:(struct CGPoint)fp8 forAngle:(float)fp16;
- (BOOL)_isOutOfBoundsVertically:(struct CGPoint)fp8;
- (float)_computeEffectiveAngleFromMin:(float)fp8 max:(float)fp12;
- (struct CGPoint)_averagePointFromTouches:(id)fp8;
- (int)_activeTouchCountForEvent:(id)fp8;
- (void)_loadFromSettings:(id)fp8;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (BOOL)canBePreventedByGestureRecognizer:(id)fp8;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)reset;
- (float)_effectiveBottomAngle;
- (float)_effectiveTopAngle;
- (id)relativeView;
- (void)dealloc;
- (id)initWithTarget:(id)fp8 action:(SEL)fp12;

@end

