/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBBBulletinInfo.h"

@class UIImage;

@interface SBSnippetBulletinInfo : SBBBBulletinInfo
{
    float _viewHeight;
    struct CGRect _textRect;
    struct CGSize _referenceSize;
    UIImage *_icon;
}

- (void)setIcon:(id)fp8;
- (id)icon;
- (void)populateReusableView:(id)fp8;
- (float)heightForReusableViewInTableView:(id)fp8;
- (BOOL)_isLayoutValidWithReferenceSize:(struct CGSize)fp8;
- (id)_representedBulletin;
- (void)invalidateCachedLayoutData;
- (Class)reusableViewClass;
- (id)identifier;
- (void)dealloc;

@end

