/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, UIScreen;

@interface SBSnapshotImageInfo : _ABAddressBookCopyLocalizedLabel
{
    BOOL _defaultPNG;
    NSString *_path;
    UIScreen *_screen;
    float _scale;
    int _launchingOrientation;
    int _originalOrientation;
}

+ (id)snapshotImageInfoWithPath:(id)fp8 launchingOrientation:(int)fp12 originalOrientation:(int)fp16 forScreen:(id)fp20;
- (void)setDefaultPNG:(BOOL)fp8;
- (BOOL)defaultPNG;
- (void)setOriginalOrientation:(int)fp8;
- (int)originalOrientation;
- (void)setLaunchingOrientation:(int)fp8;
- (int)launchingOrientation;
- (void)setScale:(float)fp8;
- (float)scale;
- (void)setScreen:(id)fp8;
- (id)screen;
- (void)setPath:(id)fp8;
- (id)path;
- (id)description;
- (id)_stringForInterfaceOrientation:(int)fp8;
- (void)dealloc;

@end

