/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBaseSoftwareUpdateAlertItem.h"

@class UIView;

@interface SBSoftwareUpdateVerifyingUpdateAlertItem : SBBaseSoftwareUpdateAlertItem
{
    UIView *_activityAccessoryView;
}

- (BOOL)dismissOnLock;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)shouldShowInLockScreen;
- (BOOL)undimsScreen;
- (BOOL)behavesSuperModally;
- (BOOL)reappearsAfterLock;
- (BOOL)reappearsAfterUnlock;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)dealloc;
- (id)initWithDescriptor:(id)fp8;

@end

