/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class AVController, NSHashTable, NSMutableArray, NSMutableDictionary, NSTimer, SBUISound;

@interface SBSoundController : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_soundsBySystemSoundIDs;
    AVController *_avController;
    SBUISound *_avControllerSound;
    NSTimer *_avControllerMaxDurationTimer;
    id _avControllerObserver;
    NSMutableDictionary *_soundsByToneIdentifiers;
    NSMutableDictionary *_toneAlertsByToneIdentifiers;
    NSHashTable *_observers;
    unsigned int _pendingCallbacks;
    NSMutableArray *_pendedCallbacks;
}

+ (id)sharedInstance;
- (void)_enqueueCallback:(id)fp(null);
- (void)_endPendingCallbacksBlock;
- (void)_beginPendingCallbacksBlock;
- (void)_soundDidFinishPlaying:(id)fp8;
- (void)_soundDidStartPlaying:(id)fp8;
- (void)_ringerStateChanged:(id)fp8;
- (BOOL)_playToneAlert:(id)fp8;
- (BOOL)_playAVItem:(id)fp8 forSound:(id)fp12;
- (BOOL)_playRingtone:(id)fp8;
- (BOOL)_playSystemSound:(id)fp8;
- (void)_stopToneAlertForSound:(id)fp8;
- (void)_killAVController;
- (void)_cleanupSystemSound:(unsigned long)fp8 andKill:(BOOL)fp12;
- (BOOL)handleVolumeButtonDownEvent;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (BOOL)stopAllSounds;
- (BOOL)stopSound:(id)fp8;
- (BOOL)playSound:(id)fp8 environments:(int)fp12 completion:(id)fp(null);
- (BOOL)isPlaying:(id)fp8;
- (BOOL)isPlayingAnySound;
- (void)dealloc;
- (id)init;

@end

