/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconListModelObserver-Protocol.h"
#import "SBLeafIconDataSource-Protocol.h"
#import "SBStarkLauncher-Protocol.h"

@class NSMutableDictionary, NSMutableSet, SBStarkFakeIconOperationController, SBStarkIconListModel;

@interface SBStarkLauncherViewController : _ABAddressBookCopyLocalizedLabel <SBIconListModelObserver, SBStarkLauncher, SBLeafIconDataSource>
{
    NSMutableSet *_displayIdentifiers;
    NSMutableDictionary *_fakeAppsByIdentifier;
    SBStarkIconListModel *_iconList;
    unsigned int _batchCount;
    BOOL _needsReloadAtEndOfBatch;
    SBStarkFakeIconOperationController *_fakeIconOperationController;
    id <SBStarkAutoHideControlBarDelegate> _autoHideDelegate;
}

+ (float)desiredHeightForBounds:(struct CGRect)fp8;
- (void)setFakeIconOperationController:(id)fp8;
- (id)fakeIconOperationController;
- (void)setAutoHideDelegate:(id)fp8;
- (id)autoHideDelegate;
- (id)iconList;
- (BOOL)iconIsRecentlyUpdated:(id)fp8;
- (BOOL)icon:(id)fp8 launchFromLocation:(int)fp12;
- (BOOL)iconAllowsLaunch:(id)fp8;
- (BOOL)iconCompleteUninstall:(id)fp8;
- (BOOL)iconAllowsUninstall:(id)fp8;
- (id)iconFormattedAccessoryString:(id)fp8;
- (id)iconBadgeNumberOrString:(id)fp8;
- (int)iconAccessoryType:(id)fp8;
- (BOOL)iconProgressIsPaused:(id)fp8;
- (float)iconProgressPercent:(id)fp8;
- (int)iconProgressState:(id)fp8;
- (BOOL)iconAppearsInNewsstand:(id)fp8;
- (BOOL)iconCanEllipsizeLabel:(id)fp8;
- (id)icon:(id)fp8 defaultImageWithFormat:(int)fp12;
- (id)icon:(id)fp8 imageWithFormat:(int)fp12;
- (unsigned int)iconPriority:(id)fp8;
- (id)iconDisplayName:(id)fp8;
- (void)iconList:(id)fp8 didRemoveIcon:(id)fp12;
- (void)iconList:(id)fp8 didReplaceIcon:(id)fp12 withIcon:(id)fp16;
- (void)iconList:(id)fp8 didAddIcon:(id)fp12;
- (void)_noteIconModelChanged:(id)fp8;
- (void)_noteIconModelActionOnIcon:(id)fp8;
- (void)_noteInstalledApplicationsDidChange:(id)fp8;
- (void)_decrementBatch;
- (void)_incrementBatch;
- (void)_doAsBatchedUpdate:(id)fp(null);
- (id)_sortedListOfDisplayIDs;
- (BOOL)_isStarkAware:(id)fp8;
- (void)_reloadIconList;
- (void)_removeAppForDisplayIdentifier:(id)fp8;
- (void)_addIconIfPossible:(id)fp8 withDisplayIdentifier:(id)fp12;
- (void)relayoutIcons;
- (id)suffixFakeIcons;
- (id)prefixFakeIcons;
- (int)iconLocation;
- (BOOL)obscuresControlBar;
- (BOOL)hidesAutomatically;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

