/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkBannerItem.h"

@class BBBulletin, SBUISound;

@interface SBStarkBulletinBannerItem : SBStarkBannerItem
{
    BBBulletin *_bulletin;
    SBUISound *_sound;
}

- (id)subActionWithIndex:(SEL)fp4;
- (id)subActionLabels;
- (id)sound;
- (id)action;
- (BOOL)matchesContext:(id)fp8;
- (int)actionType;
- (id)categoryImage;
- (id)subTitle;
- (id)title;
- (void)updateBulletinToInstance:(id)fp8;
- (void)dealloc;
- (id)initWithBulletin:(id)fp8;

@end

