/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBStarkBackgroundProvider : _ABAddressBookCopyLocalizedLabel
{
    NSString *_serviceName;
    NSString *_viewControllerClassName;
    unsigned int _priority;
}

- (unsigned int)priority;
- (id)viewControllerClassName;
- (id)serviceName;
- (id)description;
- (void)dealloc;
- (id)initWithServiceName:(id)fp8 viewControllerClassName:(id)fp12 priority:(unsigned int)fp16;
- (id)initWithServiceName:(id)fp8 options:(id)fp12;

@end

