/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAlertManagerDelegate-Protocol.h"
#import "SBAlertManagerObserver-Protocol.h"
#import "UIStatusBarStyleDelegate-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class AVExternalDevice, NSTimer, SBAlertManager, SBCarDisplaySettings, SBStarkDefaultHostingWindow, SBStarkFakeIconOperationController, SBStarkHomeController, SBStarkLockOutViewController, SBStarkLockOutWindow, SBStarkNotificationWindow, SBStarkScreenFocusController, SBStarkSiriWindow, UIScreen, _UIBackdropView;

@interface SBStarkScreenController : _ABAddressBookCopyLocalizedLabel <SBAlertManagerDelegate, SBAlertManagerObserver, UIStatusBarStyleDelegate, _UISettingsKeyObserver>
{
    UIScreen *_screen;
    SBCarDisplaySettings *_settings;
    id <SBStarkScreenControllerDelegate> _delegate;
    id <SBDisplayProtocol> _topDisplay;
    int _lockOutMode;
    NSTimer *_lockOutModeUpdateTimer;
    SBStarkLockOutViewController *_lockOutViewController;
    SBStarkLockOutWindow *_lockOutWindow;
    SBStarkDefaultHostingWindow *_defaultHostingWindow;
    SBStarkHomeController *_homeController;
    SBStarkNotificationWindow *_notificationWindow;
    SBStarkSiriWindow *_siriWindow;
    _UIBackdropView *_siriBackdropView;
    BOOL _showingSiri;
    SBAlertManager *_alertManager;
    id _starkScreenBorrowingToken;
    SBStarkScreenFocusController *_focusController;
    SBStarkFakeIconOperationController *_fakeIconOperationController;
    AVExternalDevice *_externalDevice;
}

- (id)alertManager;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)screen;
- (void)settings:(id)fp8 changedValueForKey:(id)fp12;
- (void)statusBar:(id)fp8 didTriggerButtonType:(int)fp12 withAction:(int)fp16;
- (void)statusBar:(id)fp8 didAnimateFromHeight:(float)fp12 toHeight:(float)fp16 animation:(int)fp20;
- (void)statusBar:(id)fp8 willAnimateFromHeight:(float)fp12 toHeight:(float)fp16 duration:(double)fp20 animation:(int)fp28;
- (int)statusBar:(id)fp8 styleForRequestedStyle:(int)fp12 overrides:(int)fp16;
- (BOOL)allowNavigationOverrideStyle;
- (BOOL)allowInCallOverrideStyle;
- (void)alertManagerDidChangeTopAlert:(id)fp8;
- (void)alertManager:(id)fp8 willTearDownAlertWindow:(id)fp12;
- (void)alertManager:(id)fp8 didDeactivateAlert:(id)fp12 top:(BOOL)fp16;
- (void)alertManager:(id)fp8 willActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (BOOL)alertManager:(id)fp8 shouldDeactivateDismissedAlert:(id)fp12;
- (id)alertManager:(id)fp8 newAlertWindowForLockAlerts:(BOOL)fp12;
- (void)_showNowPlaying;
- (void)_createFakeIconOperationController;
- (void)_updateLockOutModeAfterDelay;
- (void)_updateLockOutMode;
- (void)_startInitialAppLaunchTimer;
- (void)_cancelInitialAppLaunchTimer;
- (void)_launchInitialAppIfNecessary;
- (BOOL)_shouldLaunchMapsAtConnect;
- (void)_takeScreenRequested:(id)fp8;
- (void)_setShowingSiri:(BOOL)fp8;
- (void)_dismissSiriWithDuration:(double)fp8 animations:(id)fp(null) completion:(void)fp16;
- (void)dismissSiriWithFade:(double)fp8 completion:(id)fp(null);
- (void)dismissSiri:(BOOL)fp8 completion:(id)fp(null);
- (void)presentSiri:(BOOL)fp8 viewController:(id)fp12;
- (id)focusWindow;
- (id)animationWindow;
- (id)mainWindow;
- (void)updateStatusBarStateForDisplay:(id)fp8 withAnimationFactory:(id)fp12;
- (void)handleLongBackPress;
- (void)handleUnhandledBack;
- (void)handleUncompletedAppLaunch;
- (void)setTopDisplay:(id)fp8 withAnimationFactory:(id)fp12;
- (void)setTopDisplay:(id)fp8;
- (id)topDisplay;
- (int)state;
- (void)invalidate;
- (void)_tearDownAndInvalidate:(BOOL)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithScreen:(id)fp8;

@end

