/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBStarkAutoHideControlBarDelegate-Protocol.h"
#import "UIStatusBarStyleDelegate-Protocol.h"

@class NSMutableSet, SBStarkFakeIconOperationController, SBStarkScreenFocusController, UIStatusBar, UIViewController<SBStarkLauncher>;

@interface SBStarkControlBarViewController : _ABAddressBookCopyLocalizedLabel <UIStatusBarStyleDelegate, SBStarkAutoHideControlBarDelegate>
{
    id <SBStarkControlBarDelegate> _delegate;
    double _autoHideDelay;
    NSMutableSet *_launcherHideReasons;
    UIViewController<SBStarkLauncher> *_launcherViewController;
    UIStatusBar *_statusBarView;
    id <UIStatusBarStyleDelegate> _statusBarStyleDelegate;
    NSMutableSet *_statusBarHideReasons;
    int _requestedStyle;
    SBStarkScreenFocusController *_focusController;
    SBStarkFakeIconOperationController *_fakeIconOperationController;
}

- (id)fakeIconOperationController;
- (void)setFocusController:(id)fp8;
- (id)focusController;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)resetStarkControlBarAutoHideTimer;
- (void)statusBar:(id)fp8 didTriggerButtonType:(int)fp12 withAction:(int)fp16;
- (void)statusBar:(id)fp8 didAnimateFromHeight:(float)fp12 toHeight:(float)fp16 animation:(int)fp20;
- (void)statusBar:(id)fp8 willAnimateFromHeight:(float)fp12 toHeight:(float)fp16 duration:(double)fp20 animation:(int)fp28;
- (int)statusBar:(id)fp8 styleForRequestedStyle:(int)fp12 overrides:(int)fp16;
- (BOOL)_isStatusBarHidden;
- (void)_autoHideTriggered;
- (void)_resetAutoHideTimer;
- (struct CGRect)_launcherViewFrameForVisibility:(BOOL)fp8;
- (void)_setLauncherHidden:(BOOL)fp8 forReason:(id)fp12 withAnimationFactory:(id)fp16 fallbackToDefaultAnimationFactory:(BOOL)fp20;
- (BOOL)_isLauncherHidden;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)setFakeIconOperationController:(id)fp8;
- (void)updateStatusBarWithRequestedStyle:(int)fp8 animationFactory:(id)fp12;
- (void)setStatusBarHidden:(BOOL)fp8 forReason:(id)fp12 withAnimationFactory:(id)fp16;
- (void)setStatusBarStyleDelegate:(id)fp8;
- (id)statusBarStyleDelegate;
- (void)setLauncherHidden:(BOOL)fp8 forReason:(id)fp12 withAnimationFactory:(id)fp16;
- (void)setLauncherHidden:(BOOL)fp8 forReason:(id)fp12 animated:(BOOL)fp16;
- (void)setAutoHideDelay:(double)fp8;
- (double)autoHideDelay;
- (struct CGPoint)highestVisiblePoint;
- (void)dealloc;
- (id)initWithInterfaceType:(int)fp8;

@end

