/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, UIWindow;

@interface SBStarkScreenFocusAssertion : _ABAddressBookCopyLocalizedLabel
{
    NSString *_name;
    int _type;
    float _priority;
    UIWindow *_window;
}

- (id)window;
- (float)priority;
- (int)type;
- (id)name;
- (id)description;
- (void)dealloc;
- (id)initWithName:(id)fp8 type:(int)fp12 priority:(float)fp16 window:(id)fp20;

@end

