/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBStarkBackgroundProvidersViewController;

@interface SBStarkBackgroundViewController : _ABAddressBookCopyLocalizedLabel
{
    SBStarkBackgroundProvidersViewController *_providerViewController;
    struct UIEdgeInsets _providerInsets;
    BOOL _providerHidden;
    struct CGPoint _highestOccludedPoint;
}

- (struct CGRect)_providerViewPortFrame;
- (struct CGRect)_providerViewFrame;
- (struct CGRect)_visibleFrame;
- (struct CGRect)_viewFrame;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)setProviderHidden:(BOOL)fp8 withAnimationFactory:(id)fp12 completionState:(id)fp16;
- (void)switchToState:(id)fp8 withAnimationName:(id)fp12;
- (void)setHighestOccludedPoint:(struct CGPoint)fp8;
- (struct CGPoint)highestOccludedPoint;
- (void)setProviderInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)providerInsets;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

