/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerDelegate-Protocol.h"

@class SBAlert, SBUIAnimationController;

@interface SBStarkAlertToAppWorkspaceTransaction : SBStarkToAppWorkspaceTransaction <SBUIAnimationControllerDelegate>
{
    SBAlert *_alert;
    SBUIAnimationController *_animation;
    BOOL _animatedAppActivation;
    BOOL _animatingAlertSuspension;
    BOOL _deactivateAfterNextLaunch;
    BOOL _activatingLauncher;
    BOOL _fromAssistant;
}

- (id)alert;
- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (void)_handleFailure;
- (void)_deactivateAlertIfNecessary;
- (void)_alertAnimationComplete:(id)fp8;
- (void)_transactionComplete;
- (void)_endAnimation;
- (BOOL)selfStarkAlertDidDeactivate:(id)fp8;
- (BOOL)selfStarkAlertWillDeactivate:(id)fp8;
- (BOOL)selfApplicationExited:(id)fp8;
- (BOOL)selfApplicationLaunchDidFail:(id)fp8;
- (BOOL)selfApplicationDidFinishLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfApplicationWillBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfApplicationActivated:(id)fp8;
- (int)_setupMilestonesFrom:(id)fp8 to:(id)fp12;
- (id)_newAnimationControllerFrom:(id)fp8 to:(id)fp12;
- (BOOL)_hasAnimation;
- (void)_beginAnimation;
- (void)_commit;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16 alert:(id)fp20 toApplication:(id)fp24;

@end

