/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBStarkBackgroundProvidersViewControllerDelegate <NSObject>
- (void)starkBackgroundProvidersViewControllerWillAnimateInInitially:(id)fp8;
- (void)starkBackgroundProvidersViewController:(id)fp8 didStartWithAnimation:(BOOL)fp12;
- (void)starkBackgroundProvidersViewController:(id)fp8 willStartWithAnimation:(BOOL)fp12;
@end

