/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerDelegate-Protocol.h"

@class BKSApplicationActivationAssertion, SBApplication, SBUIAnimationController;

@interface SBStarkAppToAppWorkspaceTransaction : SBStarkToAppWorkspaceTransaction <SBUIAnimationControllerDelegate>
{
    SBApplication *_fromApp;
    SBUIAnimationController *_animationController;
    BKSApplicationActivationAssertion *_suspendingAppAssertion;
    BOOL _animatedActivation;
    BOOL _animatedDeactivation;
}

- (id)fromApp;
- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (id)_newAnimationFromLauncherToApp;
- (id)_newAnimationFromAppToLauncher;
- (id)_newAnimationFromAppToApp;
- (void)_doCommit;
- (id)_animation;
- (void)_handleAppDidNotChange;
- (id)_setupAnimationFrom:(id)fp8 to:(id)fp12;
- (void)_transactionComplete;
- (void)_interruptWithReason:(int)fp8;
- (BOOL)_canBeInterrupted;
- (void)_endAnimation;
- (BOOL)selfStarkAlertDidDeactivate:(id)fp8;
- (BOOL)selfAlertDidDeactivate:(id)fp8;
- (BOOL)selfApplicationExited:(id)fp8;
- (BOOL)selfApplicationLaunchDidFail:(id)fp8;
- (BOOL)selfApplicationActivated:(id)fp8;
- (BOOL)selfApplicationDidFinishLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfApplicationWillBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (void)_commit;
- (void)_beginAnimation;
- (int)_setupMilestonesFrom:(id)fp8 to:(id)fp12;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16 from:(id)fp20 to:(id)fp24;

@end

