/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary;

@interface SBStarkFakeIconOperationController : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_launchOperationForDisplayIDMap;
}

- (void)addLaunchOperation:(id)fp(null) withDisplayID:(void)fp8;
- (BOOL)performOperationForFakeIconWithDisplayID:(id)fp8;
- (void)dealloc;
- (id)init;

@end

