/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkAppToAppWorkspaceTransaction.h"

@interface SBStarkAppExitedWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction
{
}

- (id)_setupAnimationFrom:(id)fp8 to:(id)fp12;
- (int)_setupMilestonesFrom:(id)fp8 to:(id)fp12;
- (id)initWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16 exitedApp:(id)fp20;

@end

