/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBWindow.h"

#import "SBStarkNotificationViewControllerDelegate-Protocol.h"

@class SBStarkScreenFocusController;

@interface SBStarkNotificationWindow : SBWindow <SBStarkNotificationViewControllerDelegate>
{
    id _starkScreenBorrowingToken;
    SBStarkScreenFocusController *_focusController;
}

- (void)setFocusController:(id)fp8;
- (id)focusController;
- (void)notificationViewController:(id)fp8 stateDidChangeFrom:(int)fp12;
- (void)setRootViewController:(id)fp8;
- (void)dealloc;
- (id)initWithScreen:(id)fp8 jailBehavior:(int)fp12;

@end

