/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIStarkHomeScreenBackgroundHostInterface-Protocol.h"
#import "SBUIStarkHomeScreenBackgroundProviderInterface-Protocol.h"

@class SBStarkBackgroundProvider;

@interface SBStarkBackgroundProviderRemoteViewController : _ABAddressBookCopyLocalizedLabel <SBUIStarkHomeScreenBackgroundHostInterface, SBUIStarkHomeScreenBackgroundProviderInterface>
{
    SBStarkBackgroundProvider *_provider;
    id <SBStarkBackgroundProviderRemoteViewControllerDelegate> _delegate;
}

+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setProvider:(id)fp8;
- (id)provider;
- (void)switchToState:(id)fp8 withAnimationName:(id)fp12;
- (void)setViewportFrame:(struct CGRect)fp8;
- (void)viewServiceDidTerminateWithError:(id)fp8;
- (void)dealloc;

@end

