/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkBannerItem.h"

@class NSString, SBAlertItem, SBUISound;

@interface SBStarkAlertItemBannerItem : SBStarkBannerItem
{
    SBAlertItem *_alertItem;
    NSString *_title;
    NSString *_message;
    SBUISound *_sound;
}

- (id)subActionWithIndex:(SEL)fp4;
- (id)subActionLabels;
- (id)sound;
- (id)action;
- (BOOL)isSticky;
- (unsigned int)priority;
- (BOOL)matchesContext:(id)fp8;
- (void)reloadDisplayProperties;
- (int)actionType;
- (id)categoryImage;
- (id)category;
- (id)title;
- (void)dealloc;
- (id)initWithAlertItem:(id)fp8;

@end

