/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSArray, NSMutableArray, UIImageView;

@interface SBStarkLockOutView : _ABAddressBookCopyLocalizedLabel
{
    NSMutableArray *_titleLabels;
    float _titleAscender;
    float _titleDescender;
    UIImageView *_imageView;
    struct CGSize _imageSize;
    NSMutableArray *_messageLabels;
    float _messageAscender;
    float _messageDescender;
    NSArray *_baselineSeparations;
    float _verticalOffset;
}

- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 titleLines:(id)fp24 image:(id)fp28 messageLines:(id)fp32 baselineSeparations:(id)fp36 verticalOffset:(float)fp40;

@end

