/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBWorkspaceTransaction.h"

#import "SBAlertManagerObserver-Protocol.h"

@class SBAlertManager, SBStarkScreenController;

@interface SBStarkWorkspaceTransaction : SBWorkspaceTransaction <SBAlertManagerObserver>
{
    SBStarkScreenController *_starkScreenController;
    SBAlertManager *_starkScreenAlertManager;
    SBAlertManager *_mainScreenAlertManager;
}

- (void)alertManager:(id)fp8 didDeactivateAlert:(id)fp12 top:(BOOL)fp16;
- (void)alertManager:(id)fp8 willDeactivateAlert:(id)fp12 top:(BOOL)fp16;
- (void)alertManager:(id)fp8 didActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 willActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (BOOL)selfStarkAlertDidDeactivate:(id)fp8;
- (BOOL)selfStarkAlertWillDeactivate:(id)fp8;
- (BOOL)selfStarkAlertDidActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfStarkAlertWillActivate:(id)fp8 overAlerts:(id)fp12;
- (id)starkScreenAlertManager;
- (id)starkScreenController;
- (id)mainScreenAlertManager;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16;

@end

