/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBStarkLauncher <NSObject>
+ (float)desiredHeightForBounds:(struct CGRect)fp8;
- (void)setAutoHideDelegate:(id)fp8;
- (id)autoHideDelegate;
- (void)setFakeIconOperationController:(id)fp8;
- (id)fakeIconOperationController;
- (BOOL)obscuresControlBar;
- (BOOL)hidesAutomatically;
- (id)iconList;
- (void)setHeight:(float)fp8;
- (float)height;
@end

