/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkLauncherViewController.h"

#import "SBStarkIconCellDelegate-Protocol.h"
#import "SBStarkLauncherLayoutDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class SBStarkLauncherLayout, UICollectionView;

@interface SBStarkTouchLauncherViewController : SBStarkLauncherViewController <UICollectionViewDataSource, UICollectionViewDelegate, SBStarkIconCellDelegate, SBStarkLauncherLayoutDelegate>
{
    id <SBStarkTouchLauncherObserver> _observer;
    SBStarkLauncherLayout *_layout;
    UICollectionView *_iconCollectionView;
}

+ (float)desiredHeightForBounds:(struct CGRect)fp8;
- (void)setObserver:(id)fp8;
- (id)observer;
- (void)starkLauncherLayoutDidChangeScrollButtonInsets:(id)fp8;
- (BOOL)starkIconCellDisplaysBadges:(id)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (BOOL)collectionView:(id)fp8 shouldShowMenuForItemAtIndexPath:(id)fp12;
- (void)collectionView:(id)fp8 didDeselectItemAtIndexPath:(id)fp12;
- (void)collectionView:(id)fp8 didSelectItemAtIndexPath:(id)fp12;
- (void)collectionView:(id)fp8 didHighlightItemAtIndexPath:(id)fp12;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (int)numberOfSectionsInCollectionView:(id)fp8;
- (void)loadView;
- (void)relayoutIcons;
- (float)height;
- (void)setHeight:(float)fp8;
- (void)scrollRight;
- (BOOL)canScrollRight;
- (void)scrollLeft;
- (BOOL)canScrollLeft;
- (struct UIEdgeInsets)scrollButtonInsets;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithInterfaceType:(int)fp8;

@end

