/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkAppToAppWorkspaceTransaction.h"

@class SBAlert;

@interface SBStarkImpersonatedAppToAppWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction
{
    SBAlert *_deactivatingAlert;
    BOOL _animatedAppActivation;
}

- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (void)_deactivateAlertIfPossible;
- (void)_handleFailureToLaunch;
- (BOOL)selfStarkAlertDidDeactivate:(id)fp8;
- (BOOL)selfStarkAlertWillDeactivate:(id)fp8;
- (BOOL)selfApplicationExited:(id)fp8;
- (BOOL)selfApplicationLaunchDidFail:(id)fp8;
- (id)_newAnimationFromLauncherToApp;
- (id)_newAnimationFromAppToLauncher;
- (id)_newAnimationFromAppToApp;
- (void)_transactionComplete;
- (int)_setupMilestonesFrom:(id)fp8 to:(id)fp12;
- (void)_doCommit;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16 from:(id)fp20 to:(id)fp24;

@end

