/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBCollectionViewCell.h"

@class SBIcon, SBStarkIconImageView, UIView<SBIconAccessoryView>;

@interface SBStarkIconCell : SBCollectionViewCell
{
    SBIcon *_icon;
    SBStarkIconImageView *_iconImageView;
    UIView<SBIconAccessoryView> *_accessoryView;
    BOOL _disableFrameChangeOnHighlight;
    float _initialHeight;
    BOOL _temporarilyEnableHighlightDimming;
}

- (void)setTemporarilyEnableHighlightDimming:(BOOL)fp8;
- (BOOL)temporarilyEnableHighlightDimming;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)iconImageDidUpdate:(id)fp8;
- (struct CGRect)_accessoryFrameInBounds:(struct CGRect)fp8;
- (id)description;
- (void)layoutSubviews;
- (void)applyLayoutAttributes:(id)fp8;
- (void)prepareForReuse;
- (void)_didSetHighlighted:(BOOL)fp8;
- (void)setIcon:(id)fp8;
- (id)icon;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

