/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBWindow.h"

@interface SBStarkControlBarWindow : SBWindow
{
}

- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setRootViewController:(id)fp8;
- (id)rootViewController;

@end

