/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBStarkLauncher-Protocol.h"
#import "SBStarkTouchLauncherObserver-Protocol.h"

@class SBStarkTouchLauncherViewController, UIButton;

@interface SBStarkLowTouchLauncherViewController : _ABAddressBookCopyLocalizedLabel <SBStarkTouchLauncherObserver, SBStarkLauncher>
{
    SBStarkTouchLauncherViewController *_touchLauncherViewController;
    UIButton *_leftScrollButton;
    UIButton *_rightScrollButton;
}

+ (float)desiredHeightForBounds:(struct CGRect)fp8;
- (void)touchLauncherDidScroll:(id)fp8;
- (void)touchLauncherDidChangeScrollButtonInsets:(id)fp8;
- (void)setAutoHideDelegate:(id)fp8;
- (id)autoHideDelegate;
- (id)fakeIconOperationController;
- (void)setFakeIconOperationController:(id)fp8;
- (BOOL)obscuresControlBar;
- (BOOL)hidesAutomatically;
- (id)iconList;
- (float)height;
- (void)setHeight:(float)fp8;
- (void)_scrollRight;
- (void)_scrollLeft;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

