/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBStarkAppToAppWorkspaceTransactionFactory : _ABAddressBookCopyLocalizedLabel
{
}

+ (id)newTransactionWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16 from:(id)fp20 to:(id)fp24;

@end

