/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIBannerSource-Protocol.h"
#import "SBUIBannerTargetManagerObserver-Protocol.h"

@class NSMutableArray;

@interface SBStarkBannerSource : _ABAddressBookCopyLocalizedLabel <SBUIBannerSource, SBUIBannerTargetManagerObserver>
{
    id <SBUIBannerTarget> _allowedTarget;
    id <SBUIBannerTarget> _target;
    NSMutableArray *_enqueuedItems;
}

- (void)bannerTargetManager:(id)fp8 didRemoveTarget:(id)fp12;
- (void)bannerTargetManager:(id)fp8 didAddTarget:(id)fp12;
- (id)newBannerViewForContext:(id)fp8;
- (id)dequeueNextBannerItemForTarget:(id)fp8;
- (id)peekNextBannerItemForTarget:(id)fp8;
- (unsigned int)enumerateAllItemsMatchingContext:(id)fp8 withBlock:(id)fp(null);
- (void)removeEnqueuedItemsAtIndexes:(id)fp8;
- (void)dismissCurrentItemFromTarget;
- (void)enqueueItem:(id)fp8;
- (id)indexesOfEnqueuedItemsMatchingContext:(id)fp8;
- (id)currentItemFromTarget;
- (void)dealloc;
- (id)init;
- (id)initWithAllowedTarget:(id)fp8;

@end

