/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkWorkspaceTransaction.h"

@class SBApplication;

@interface SBStarkToAppWorkspaceTransaction : SBStarkWorkspaceTransaction
{
    SBApplication *_toApp;
    BOOL _fromAssistant;
}

- (id)toApp;
- (void)_transactionComplete;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16 to:(id)fp20;

@end

