/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBStatusBarStateAggregatorPosting <NSObject>
- (void)statusBarStateAggregatorDidFinishPost:(id)fp8 withData:(const CDAnonymousStruct10 *)fp12 actions:(int)fp16;
- (void)statusBarStateAggregator:(id)fp8 didUpdateNonItemData:(const CDAnonymousStruct10 *)fp12;
- (void)statusBarStateAggregator:(id)fp8 didVisitItem:(int)fp12 withUpdates:(BOOL)fp16 toData:(const CDAnonymousStruct10 *)fp20;
- (void)statusBarStateAggregatorDidStartPost:(id)fp8;
@end

