/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBCollectionViewCellDelegate-Protocol.h"
#import "SBStarkBannerTargetObserver-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, SBStarkAlertItemBannerSource, SBStarkBannerCell, SBStarkBannerTarget, SBStarkBulletinBannerSource, SBStarkNotificationLayout, SBUIBannerContext, UICollectionView, UITapGestureRecognizer;

@interface SBStarkNotificationViewController : _ABAddressBookCopyLocalizedLabel <UICollectionViewDataSource, UICollectionViewDelegate, SBCollectionViewCellDelegate, SBStarkBannerTargetObserver, UIGestureRecognizerDelegate>
{
    id <SBStarkNotificationViewControllerDelegate> _delegate;
    BOOL _touchCapable;
    UITapGestureRecognizer *_backGestureRecognizer;
    UITapGestureRecognizer *_selectGestureRecognizer;
    SBStarkBannerTarget *_bannerTarget;
    SBStarkAlertItemBannerSource *_alertItemBannerSource;
    SBStarkBulletinBannerSource *_bulletinBannerSource;
    SBUIBannerContext *_currentContext;
    NSArray *_currentSubActionLabels;
    SBStarkBannerCell *_currentCell;
    int _state;
    SBStarkNotificationLayout *_notificationsLayout;
    UICollectionView *_notificationsView;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)starkBannerTarget:(id)fp8 didChangeContextWithDismissReason:(int)fp12;
- (void)_performSelectGesture:(id)fp8;
- (void)_performBackGesture:(id)fp8;
- (void)collectionView:(id)fp8 didEndDisplayingCell:(id)fp12 forItemAtIndexPath:(id)fp16;
- (void)collectionView:(id)fp8 didSelectItemAtIndexPath:(id)fp12;
- (BOOL)collectionView:(id)fp8 shouldDeselectItemAtIndexPath:(id)fp12;
- (BOOL)collectionView:(id)fp8 shouldSelectItemAtIndexPath:(id)fp12;
- (BOOL)collectionView:(id)fp8 shouldHighlightItemAtIndexPath:(id)fp12;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (int)numberOfSectionsInCollectionView:(id)fp8;
- (void)setSuspendedForAssistant:(BOOL)fp8;
- (BOOL)isSuspendedForAssistant;
- (void)setSuspended:(BOOL)fp8;
- (BOOL)isSuspended;
- (void)_setState:(int)fp8;
- (int)state;
- (void)loadView;
- (void)dealloc;
- (id)initWithInterfaceType:(int)fp8;

@end

