/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkAlertToAppWorkspaceTransaction.h"

@class SBAlert, SBApplication, SBUIAnimationController;

@interface SBStarkAlertToImpersonatedAppWorkspaceTransaction : SBStarkAlertToAppWorkspaceTransaction
{
    SBAlert *_fromAlert;
    SBAlert *_toAlert;
    SBApplication *_toApplication;
    SBUIAnimationController *_animation;
}

- (void)_activateAlert;
- (BOOL)selfStarkAlertDidActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfStarkAlertWillActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfStarkAlertDidDeactivate:(id)fp8;
- (int)_setupMilestonesFrom:(id)fp8 to:(id)fp12;
- (id)_newAnimationControllerFrom:(id)fp8 to:(id)fp12;
- (void)_beginAnimation;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 mainScreenAlertManager:(id)fp12 starkScreenController:(id)fp16 alert:(id)fp20 toApplication:(id)fp24;

@end

