/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSArray, UIImage, UIImageView, UIView;

@interface SBStarkIconImageView : _ABAddressBookCopyLocalizedLabel
{
    UIImageView *_imageView;
    UIImage *_image;
    float _brightness;
    unsigned int _outerStripes;
    unsigned int _innerStripes;
    BOOL _needsStripeUpdating;
    NSArray *_outerStripesViews;
    NSArray *_innerStripesViews;
    UIView *_brightnessView;
}

- (id)_viewsForEdges:(unsigned int)fp8 ofWidth:(float)fp12 inFrame:(struct CGRect)fp16 withBGColor:(id)fp32 outRect:(struct CGRect *)fp36;
- (void)_updateStripesIfNeeded;
- (void)layoutSubviews;
- (unsigned int)innerStripes;
- (void)setInnerStripes:(unsigned int)fp8;
- (unsigned int)outerStripes;
- (void)setOuterStripes:(unsigned int)fp8;
- (float)brightness;
- (void)setBrightness:(float)fp8;
- (id)image;
- (void)setImage:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

