/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSHashTable, NSMutableSet;

@interface SBStarkBannerItem : _ABAddressBookCopyLocalizedLabel
{
    NSHashTable *_observers;
    NSMutableSet *_displayReasons;
}

- (BOOL)isStarkBannerItem;
- (BOOL)matchesContext:(id)fp8;
- (void)reloadDisplayProperties;
- (id)subActionLabels;
- (int)actionType;
- (id)categoryImage;
- (id)subTitle;
- (id)title;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)dealloc;
- (id)init;

@end

