/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBCollectionViewCellDelegate-Protocol.h"

@protocol SBStarkIconCellDelegate <SBCollectionViewCellDelegate>
- (BOOL)starkIconCellDisplaysBadges:(id)fp8;
@end

