/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkBannerSource.h"

#import "SBAlertItemsControllerObserver-Protocol.h"

@interface SBStarkAlertItemBannerSource : SBStarkBannerSource <SBAlertItemsControllerObserver>
{
}

- (void)alertItemsController:(id)fp8 didDeactivateAlertItem:(id)fp12 forReason:(int)fp16;
- (void)alertItemsController:(id)fp8 didActivateAlertItem:(id)fp12;
- (void)dealloc;
- (id)initWithAllowedTarget:(id)fp8;

@end

