/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBStarkBannerSource.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBVolumePressBandit-Protocol.h"

@class BBObserver, NSSet;

@interface SBStarkBulletinBannerSource : SBStarkBannerSource <BBObserverDelegate, SBVolumePressBandit>
{
    BBObserver *_bbObserver;
    NSSet *_whitelistedSectionIDs;
}

- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)_reloadVolumePressBanditPreference;
- (void)observer:(id)fp8 noteServerReceivedResponseForBulletin:(id)fp12;
- (void)observer:(id)fp8 removeBulletin:(id)fp12;
- (void)observer:(id)fp8 modifyBulletin:(id)fp12;
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (void)_showTestBanner:(id)fp8;
- (BOOL)_shouldShowBulletin:(id)fp8;
- (void)dealloc;
- (id)initWithAllowedTarget:(id)fp8;

@end

