/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBStarkBackgroundProvidersViewControllerDelegate-Protocol.h"
#import "SBStarkControlBarDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class SBStarkBackgroundViewController, SBStarkBackgroundWindow, SBStarkControlBarViewController, SBStarkControlBarWindow, SBStarkFakeIconOperationController, SBStarkScreenFocusController, UITapGestureRecognizer;

@interface SBStarkHomeController : _ABAddressBookCopyLocalizedLabel <SBStarkBackgroundProvidersViewControllerDelegate, SBStarkControlBarDelegate, UIGestureRecognizerDelegate>
{
    SBStarkBackgroundViewController *_backgroundViewController;
    SBStarkBackgroundWindow *_backgroundWindow;
    SBStarkControlBarViewController *_controlBarViewController;
    SBStarkControlBarWindow *_controlBarWindow;
    BOOL _minimized;
    UITapGestureRecognizer *_backGestureRecognizer;
    BOOL _showingNowPlaying;
    BOOL _backgroundHidden;
    SBStarkScreenFocusController *_focusController;
    SBStarkFakeIconOperationController *_fakeIconOperationController;
}

- (id)fakeIconOperationController;
- (id)focusController;
- (void)_performBackGesture:(id)fp8;
- (void)starkControlBarDidAdjustHighestVisiblePoint:(id)fp8;
- (void)starkControlBarDidTriggerAutoHideAction:(id)fp8;
- (void)starkBackgroundProvidersViewControllerWillAnimateInInitially:(id)fp8;
- (void)starkBackgroundProvidersViewController:(id)fp8 didStartWithAnimation:(BOOL)fp12;
- (void)starkBackgroundProvidersViewController:(id)fp8 willStartWithAnimation:(BOOL)fp12;
- (void)_setMinimized:(BOOL)fp8 force:(BOOL)fp12 withAnimationFactory:(id)fp16 fallbackToDefaultAnimationFactory:(BOOL)fp20;
- (BOOL)isShowingClock;
- (void)switchBackgroundProviderToNowPlaying;
- (void)setFakeIconOperationController:(id)fp8;
- (void)setFocusController:(id)fp8;
- (void)beginRevealWithAnimation:(BOOL)fp8;
- (void)updateAutoHideDelay;
- (void)updateStatusBarWithRequestedStyle:(int)fp8 animationFactory:(id)fp12;
- (void)setStatusBarHidden:(BOOL)fp8 forReason:(id)fp12 withAnimationFactory:(id)fp16;
- (void)setStatusBarStyleDelegate:(id)fp8;
- (id)statusBarStyleDelegate;
- (void)handleHomeButtonAction;
- (void)setMinimized:(BOOL)fp8 force:(BOOL)fp12 withAnimationFactory:(id)fp16;
- (void)setMinimized:(BOOL)fp8 force:(BOOL)fp12 animated:(BOOL)fp16;
- (void)setLauncherHidden:(BOOL)fp8 forReason:(id)fp12 withAnimationFactory:(id)fp16;
- (void)setBackgroundHidden:(BOOL)fp8 withAnimationFactory:(id)fp12;
- (void)dealloc;
- (id)init;
- (id)initWithScreen:(id)fp8;

@end

