/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView;

@interface SBStarkLockOutAnimation : _ABAddressBookCopyLocalizedLabel
{
    int _type;
    UIView *_snapshotView;
    int _statusBarStyle;
    BOOL _statusBarHidden;
}

- (void)setStatusBarHidden:(BOOL)fp8;
- (BOOL)statusBarHidden;
- (void)setStatusBarStyle:(int)fp8;
- (int)statusBarStyle;
- (void)setSnapshotView:(id)fp8;
- (id)snapshotView;
- (void)setType:(int)fp8;
- (int)type;
- (id)description;
- (void)dealloc;

@end

