/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIBannerTarget-Protocol.h"

@class NSHashTable, NSMutableArray, SBUIBannerContext, SBUISound;

@interface SBStarkBannerTarget : _ABAddressBookCopyLocalizedLabel <SBUIBannerTarget>
{
    id <SBStarkBannerTargetObserver> _observer;
    NSHashTable *_sources;
    BOOL _invalidated;
    NSMutableArray *_pendedContexts;
    SBUIBannerContext *_currentContext;
    SBUISound *_currentSound;
    int _displayAssertions;
    BOOL _suspended;
    BOOL _suspendedForAssistant;
}

- (id)currentContext;
- (void)setObserver:(id)fp8;
- (id)observer;
- (void)dismissCurrentBannerContextForSource:(id)fp8;
- (id)currentBannerContextForSource:(id)fp8;
- (void)signalSource:(id)fp8;
- (void)unregisterSource:(id)fp8;
- (void)registerSource:(id)fp8;
- (int)bannerTargetIdiom;
- (void)_killIntervalElapsed:(id)fp8;
- (void)_dismissIntervalElapsed:(id)fp8;
- (void)_replaceIntervalElapsed:(id)fp8;
- (void)_dismissContext:(id)fp8 withOptions:(int)fp12 dismissReason:(int)fp16;
- (void)_dequeueWithOptions:(int)fp8 dismissReason:(int)fp12;
- (BOOL)_canDequeueWithOptions:(int)fp8;
- (BOOL)_canDismissWithOptions:(int)fp8;
- (void)invalidate;
- (void)noteContextCanceled:(id)fp8;
- (void)noteContext:(id)fp8 subActionSelected:(unsigned int)fp12;
- (void)noteContextSelected:(id)fp8;
- (void)setSuspendedForAssistant:(BOOL)fp8;
- (BOOL)isSuspendedForAssistant;
- (void)setSuspended:(BOOL)fp8;
- (BOOL)isSuspended;
- (void)setPausedForUserInteraction:(BOOL)fp8;
- (BOOL)isPausedForUserInteraction;
- (void)dealloc;
- (id)init;

@end

