/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, NSTimer, SBApplication<SBSystemLocalNotificationAlertDelegate>, SBUISound, UILocalNotification;

@interface SBSystemLocalNotificationAlert : _ABAddressBookCopyLocalizedLabel
{
    SBApplication<SBSystemLocalNotificationAlertDelegate> *_app;
    UILocalNotification *_localNotification;
    NSString *_bodyText;
    NSString *_actionLabel;
    NSString *_customLockLabel;
    unsigned int _launchButtonIndex;
    unsigned int _snoozeButtonIndex;
    SBUISound *_sound;
    NSTimer *_autoMuteTimer;
}

+ (void)snoozeAlertsAndDismiss:(BOOL)fp8;
+ (void)dismissAlertsPlayingAnAVItem;
+ (BOOL)isAnyAlertPlayingAnAVItem;
+ (BOOL)_isAlertPlayingAnAVItem:(id)fp8;
+ (id)pathForSoundName:(id)fp8 inApp:(id)fp12;
+ (id)localizedStringFromKey:(id)fp8 defaultValue:(id)fp12 inBundle:(id)fp16 arguments:(id)fp20;
+ (id)alertMatchingLocalNotification:(id)fp8;
+ (id)alerts;
- (id)bodyText;
- (id)localNotification;
- (id)application;
- (BOOL)isSystemLocalNotificationAlert;
- (void)dismiss:(int)fp8;
- (void)willDeactivateForReason:(int)fp8;
- (void)willActivate;
- (void)_autoMuteTimerFired;
- (void)_playPresentationSound;
- (id)sound;
- (void)performUnlockAction;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (int)alertPriority;
- (id)alertItemNotificationSender;
- (int)alertItemNotificationType;
- (int)unlockSource;
- (BOOL)isCriticalAlert;
- (BOOL)shouldShowInEmergencyCall;
- (id)lockLabel;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (Class)alertSheetClass;
- (void)dealloc;
- (id)initWithLocalNotification:(id)fp8 forApplication:(id)fp12;
- (BOOL)isSnoozable;

@end

