/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBRemoteDataProvider-Protocol.h"

@class BBDataProviderConnection, BBDataProviderProxy;

@interface SBTestDataProvider : _ABAddressBookCopyLocalizedLabel <BBRemoteDataProvider>
{
    BBDataProviderConnection *_connection;
    BBDataProviderProxy *_proxy;
}

+ (id)sharedInstance;
- (void)noteSectionInfoDidChange:(id)fp8;
- (float)attachmentAspectRatioForRecordID:(id)fp8;
- (id)attachmentPNGDataForRecordID:(id)fp8 sizeConstraints:(id)fp12;
- (void)receiveMessageWithName:(id)fp8 userInfo:(id)fp12;
- (void)dataProviderDidLoad;
- (id)sectionParameters;
- (id)clearedInfoForBulletins:(id)fp8 lastClearedInfo:(id)fp12;
- (id)sortDescriptors;
- (id)bulletinsFilteredBy:(unsigned int)fp8 count:(unsigned int)fp12 lastCleared:(id)fp16;
- (id)sectionDisplayName;
- (id)defaultSectionInfo;
- (id)sectionIdentifier;
- (void)publish;
- (id)init;

@end

