/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class CALayer, UIColor, UIImage;

@interface SBTintedImageProvider : _ABAddressBookCopyLocalizedLabel
{
    UIImage *_tintedImage;
    CALayer *_tintedLayer;
    BOOL _wantsTintedLayer;
    UIImage *_originalImage;
    UIColor *_tintColor;
}

- (BOOL)wantsTintedLayer;
- (id)tintColor;
- (id)originalImage;
- (void)_createOrUpdateTintedImageOrLayer;
- (void)setTintColor:(id)fp8;
- (void)setOriginalImage:(id)fp8;
- (void)setWantsTintedLayer:(BOOL)fp8;
- (id)tintedLayer;
- (id)tintedImage;
- (void)dealloc;

@end

