/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBBSectionInfo.h"

@interface SBTomorrowSectionInfo : SBBBSectionInfo
{
}

- (void)populateReusableView:(id)fp8;
- (float)heightForReusableViewInTableView:(id)fp8;
- (Class)reusableViewClass;
- (id)identifier;

@end

