/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView, UILabel;

@interface SBTodayBulletinCell : _ABAddressBookCopyLocalizedLabel
{
    UILabel *_label;
    UIImageView *_iconImageView;
}

+ (id)defaultTextAttributes;
+ (id)defaultFontColor;
+ (id)defaultFont;
- (void)layoutSubviews;
- (void)setIcon:(id)fp8;
- (void)setLabelText:(id)fp8;
- (id)labelText;
- (void)setTextRect:(struct CGRect)fp8;
- (struct CGRect)textRect;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

