/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBulletinObserverViewController.h"

@class NSArray, NSMutableDictionary, SBBBSectionInfo;

@interface SBTodayViewController : SBBulletinObserverViewController
{
    NSMutableDictionary *_sectionIDsToOrderedBulletins;
    NSArray *_todaySnippetBulletinOrder;
    NSArray *_tomorrowSnippetBulletinOrder;
    SBBBSectionInfo *_todaySectionInfo;
    SBBBSectionInfo *_tomorrowSectionInfo;
}

- (int)bulletinViewController:(id)fp8 insertionAnimationForBulletin:(id)fp12 inSection:(id)fp16;
- (void)widget:(id)fp8 didUpdatePreferredSize:(struct CGSize)fp12;
- (void)commitReplacementWithBulletin:(id)fp8 ofBulletin:(id)fp12 inSection:(id)fp16;
- (void)commitRemovalOfBulletin:(id)fp8 fromSection:(id)fp12;
- (void)commitInsertionOfBulletin:(id)fp8 beforeBulletin:(id)fp12 inSection:(id)fp16 forFeed:(unsigned int)fp20;
- (void)_sortBulletinsForSectionWithIdentifier:(id)fp8 referencingOrder:(id)fp12;
- (id)_bulletinOrderStringForBulletinInfo:(id)fp8;
- (id)_tomorrowSnippetBulletinOrder;
- (id)_todaySnippetBulletinOrder;
- (void)commitReloadOfSections:(id)fp8;
- (void)commitRemovalOfSection:(id)fp8;
- (void)commitInsertionOfSection:(id)fp8 beforeSection:(id)fp12;
- (id)todayTableHeaderView;
- (id)infoForWidgetSection:(id)fp8;
- (id)infoForBulletin:(id)fp8 inSection:(id)fp12;
- (id)infoForBulletinSection:(id)fp8;
- (int)widgetIdiomForCategory:(int)fp8;
- (struct UIEdgeInsets)bulletinViewControllerContentInsetsForMode:(int)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)updateTableHeader;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

