/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBLockScreenViewControllerBase, SBWindow, UIView<SBWindowContextAppearance>;

@interface SBUIAnimationPhoneToLockScreenBase : SBUIMainScreenAnimationController
{
    SBWindow *_transitionWindow;
    SBLockScreenViewControllerBase *_lockScreenViewController;
    UIView<SBWindowContextAppearance> *_contextHostView;
    BOOL _needsScreenDim;
}

- (void)_setContextHostView:(id)fp8;
- (id)_contextHostView;
- (void)_noteAnimationDidFinish;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)fp8;
- (BOOL)_shouldHideContextHostViewStatusBar;
- (id)_getTransitionWindow;
- (id)_lockScreenViewController;
- (void)dealloc;
- (id)initWithLockScreenController:(id)fp8 deactivatingApp:(id)fp12;

@end

