/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAlert, SBWindow, UIView<SBWindowContextAppearance>;

@interface SBUIAnimationAlertToPhoneBase : SBUIMainScreenAnimationController
{
    SBWindow *_transitionWindow;
    SBAlert *_deactivatingAlert;
    UIView<SBWindowContextAppearance> *_viewToAnimate;
    BOOL _reallyFinishedAnimating;
}

- (void)_setViewToAnimate:(id)fp8;
- (id)_viewToAnimate;
- (void)_maybeReportAnimationFinished;
- (BOOL)_isApplicationLaunchFinished;
- (void)_noteAnimationDidFinish;
- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)_setHidden:(BOOL)fp8;
- (id)_getTransitionWindow;
- (void)_reallyFinishedAnimating;
- (BOOL)_shouldAnimateWallpaper;
- (id)_deactivatingAlert;
- (void)dealloc;
- (id)initWithAlert:(id)fp8 activatingApp:(id)fp12;

@end

