/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationZoomDownApp.h"

@interface SBUIAnimationZoomDownAppToPhone : SBUIAnimationZoomDownApp
{
    BOOL _usingSuperZoomImplementation;
    BOOL _fromPhoneAppToFaceTimeAppDuringCall;
}

- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)animateZoomWithCompletion:(id)fp(null);
- (BOOL)_shouldZoomUsingSuperImplementation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)dealloc;
- (void)_cleanupPhonesContextHostView;
- (id)appStatusBarTransitionInfoWithStartEffectivelyHidden:(BOOL)fp8 endStyleRequest:(id)fp12 endOrientation:(int)fp16;

@end

