/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationZoomDownAppToHome.h"

@class SBLockScreenViewController, SBLockToAppStatusBarAnimator;

@interface SBUIAnimationZoomDownLockScreenCameraToHome : SBUIAnimationZoomDownAppToHome
{
    SBLockScreenViewController *_lockScreenViewController;
    SBLockToAppStatusBarAnimator *_statusBarAnimator;
}

- (void)_prepareAnimation;
- (void)animateZoomWithCompletion:(id)fp(null);
- (void)animateFakeStatusBarWithParameters:(id)fp8;
- (BOOL)_shouldTakeActivationAssertionForDeactivatingApp;
- (BOOL)_shouldUpdateStatusBarOnContentRestore;
- (void)dealloc;
- (id)initWithLockScreenViewController:(id)fp8;

@end

