/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationZoomUpApp.h"

@class SBAlert, SBAlertManager;

@interface SBUIAnimationZoomUpAppFromAlert : SBUIAnimationZoomUpApp
{
    SBAlertManager *_alertManager;
    SBAlert *_alert;
}

- (void)cleanupZoom;
- (void)animateZoomWithCompletion:(id)fp(null);
- (void)prepareZoom;
- (double)animationDelay;
- (double)animationDuration;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingAlert:(id)fp12 alertManager:(id)fp16;

@end

