/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIStarkScreenAnimationController.h"

@class SBAlert, UIView;

@interface SBUIStarkAnimationZoomDownApp : SBUIStarkScreenAnimationController
{
    SBAlert *_alertImpersonator;
    UIView *_viewToAnimate;
}

- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (double)animationDelay;
- (double)animationStartTime;
- (double)animationDuration;
- (void)_prepareAnimation;
- (id)appContext;
- (BOOL)prefersLayerHostSnapshot;
- (void)dealloc;
- (id)initWithDeactivatingApp:(id)fp8 withAlertImpersonator:(id)fp12 starkScreenController:(id)fp16;
- (id)initWithDeactivatingApp:(id)fp8 starkScreenController:(id)fp12;

@end

