/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol SBUIStarkHomeScreenBackgroundProviderInterface
- (void)switchToState:(id)fp8 withAnimationName:(id)fp12;
- (void)setViewportFrame:(struct CGRect)fp8;
@end

