/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBUIAnimationWindow, UIView;

@interface SBUIAnimationDosidoTransitionController : SBUIMainScreenAnimationController
{
    SBUIAnimationWindow *_transitionWindow;
    UIView *_transformContainerParent;
    UIView *_transformContainer;
    UIView *_fromAppContextHostView;
    UIView *_fromView;
    UIView *_toView;
    int _fromOrientation;
    BOOL _fromNC;
    BOOL _fromCC;
    BOOL _fromAssistant;
    BOOL _requiresHostView;
}

- (void)_rotateViewIfNecessary:(id)fp8 inverted:(BOOL)fp12;
- (void)_kickOffAnimation;
- (void)_setFromView:(id)fp8;
- (void)captureFlagsForActivatingDisplay:(id)fp8;
- (void)hideRealFromView;
- (void)setToView:(id)fp8;
- (int)orientationAtLaunch;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)fp8;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12;
- (id)_getTransitionWindow;

@end

