/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationZoomDownAppToHome.h"

@class SBIconAnimator, SBLockScreenViewController, SBLockToAppStatusBarAnimator;

@interface SBUIAnimationZoomDownLockScreenToHome : SBUIAnimationZoomDownAppToHome
{
    SBLockScreenViewController *_lockScreenViewController;
    SBLockToAppStatusBarAnimator *_statusBarAnimator;
    SBIconAnimator *_iconAnimator;
}

- (BOOL)_shouldTakeActivationAssertionForDeactivatingApp;
- (void)animateZoomWithCompletion:(id)fp(null);
- (void)cleanupZoom;
- (void)prepareZoom;
- (void)_prepareAnimation;
- (void)dealloc;
- (id)initWithLockScreenViewController:(id)fp8;

@end

