/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationController.h"

@class SBStarkScreenController;

@interface SBUIStarkScreenAnimationController : SBUIAnimationController
{
    SBStarkScreenController *_starkScreenController;
}

- (id)starkScreenController;
- (id)_getTransitionWindow;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12 starkScreenController:(id)fp16;

@end

