/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationDosidoTransitionController.h"

@class SBLockScreenViewControllerBase;

@interface SBUIAnimationLockScreenCameraToApp : SBUIAnimationDosidoTransitionController
{
    SBLockScreenViewControllerBase *_lockscreenVC;
}

- (void)_cleanupAnimation;
- (void)hideRealFromView;
- (void)_prepareAnimation;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingLockscreen:(id)fp12;

@end

