/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAppStatusBarTransitionInfo, UIView;

@interface SBUIAnimationZoomDownApp : SBUIMainScreenAnimationController
{
    UIView *_viewToAnimate;
    SBAppStatusBarTransitionInfo *_appStatusBarTransitionInfo;
}

- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)animateFakeStatusBarWithParameters:(id)fp8;
- (void)cleanupZoom;
- (void)animateZoomWithCompletion:(id)fp(null);
- (void)prepareZoom;
- (double)animationDelay;
- (double)animationDuration;
- (id)appContext;
- (BOOL)prefersLayerHostSnapshot;
- (id)appStatusBarTransitionInfoWithStartEffectivelyHidden:(BOOL)fp8 endStyleRequest:(id)fp12 endOrientation:(int)fp16;
- (void)dealloc;
- (id)initWithDeactivatingApp:(id)fp8;

@end

