/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationController.h"

@interface SBUIMainScreenAnimationController : SBUIAnimationController
{
    BOOL _needsToClearBulletinWindowOrientation;
}

- (void)_noteAnimationDidCommit:(BOOL)fp8 withDuration:(double)fp12 afterDelay:(double)fp20;
- (void)_cleanupAnimation;
- (void)_removeWallpaperAnimationPriorityWithFactory:(id)fp8;
- (void)beginAnimation;
- (void)_dismissBannerAnimated:(BOOL)fp8;
- (BOOL)_shouldDismissBanner;
- (void)__startAnimation;
- (void)_clearBulletinWindowOverrideOrientationIfNecessary;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12;
- (id)_getTransitionWindow;

@end

