/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertAdapter.h"

@interface SBUIFullscreenAlertAdapter : SBAlertAdapter
{
    BOOL _animatingDeactivation;
    BOOL _animatingActivation;
}

+ (id)_adapterForController:(id)fp8;
+ (void)alertAdapterDisplayDidDisappear:(id)fp8;
+ (void)deactivateAlertForController:(id)fp8 animated:(BOOL)fp12 animateOldDisplayInWithStyle:(int)fp16 isSlidingDisplay:(BOOL)fp20;
+ (void)activateAlertForController:(id)fp8 animated:(BOOL)fp12 animateCurrentDisplayOut:(BOOL)fp16 withDelay:(BOOL)fp20 isSlidingDisplay:(BOOL)fp24;
- (id)effectiveViewController;
- (void)setDisplay:(id)fp8;
- (void)deactivate;
- (void)activate;
- (void)setDisplaySetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)handleAutoLock;
- (BOOL)handleHeadsetButtonPressed:(BOOL)fp8;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)handleMenuButtonTap;
- (void)displayDidDisappear;
- (void)_updateForTransparentDismiss:(id)fp8;
- (void)_pluginViewDidAnimatedIn:(id)fp8;
- (void)animateViewIn;
- (void)prepareViewToAnimateIn;
- (BOOL)isCurrentlyAnimatingActivation;
- (void)setViewShouldAnimateIn:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)_pluginViewAnimatedOut:(id)fp8;
- (void)animateViewOut;
- (void)prepareViewToAnimateOut;
- (BOOL)currentlyAnimatingDeactivation;
- (BOOL)viewIsReadyToBeRemoved;
- (BOOL)_shouldDismissSwitcherOnActivation;
- (id)display;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (BOOL)allowsStackingOfAlert:(id)fp8;
- (BOOL)hasTranslucentBackground;
- (BOOL)allowsEventOnlySuspension;
- (void)dealloc;
- (id)initWithAlertController:(id)fp8;

@end

