/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIPluginControllerHost-Protocol.h"

@class SBUIPluginController;

@interface SBUIPluginHost : _ABAddressBookCopyLocalizedLabel <SBUIPluginControllerHost>
{
    SBUIPluginController *_plugin;
    BOOL _expectsFaceContact;
    BOOL _isPluginRunning;
}

- (void)setPluginController:(id)fp8;
- (id)pluginController;
- (void)uiPlugin:(id)fp8 forceUpdateToInterfaceOrientation:(int)fp12 animated:(BOOL)fp16;
- (void)uiPluginUserEventOccurred:(id)fp8;
- (BOOL)uiPlugin:(id)fp8 openURL:(id)fp12;
- (BOOL)uiPlugin:(id)fp8 launchApplicationWithBundleID:(id)fp12 openURL:(id)fp16;
- (void)uiPlugin:(id)fp8 setExpectsFaceContact:(BOOL)fp12;
- (void)_updateFaceContactForVisibilityChange:(BOOL)fp8;
- (BOOL)uiPluginExpectsFaceContact:(id)fp8;
- (void)uiPlugin:(id)fp8 isNowRunning:(BOOL)fp12;
- (void)_updateExpectsFaceContactWithChangedValue:(BOOL)fp8;
- (BOOL)uiPluginWantsActivation:(id)fp8 forEvent:(int)fp12 completion:(id)fp(null);
- (BOOL)uiPluginAttemptDeviceUnlock:(id)fp8 withPassword:(id)fp12 lockViewOwner:(id)fp16;
- (void)uiPluginWantsDismissal:(id)fp8 withAnimation:(BOOL)fp12;
- (BOOL)pluginSuppressesNotifications;
- (BOOL)pluginWantsScreenDimInterval:(double *)fp8;
- (BOOL)pluginWantsInterfaceOrientation:(int *)fp8;
- (BOOL)pluginHandledWiredMicButtonTap;
- (BOOL)pluginHandledMenuButtonTap;
- (BOOL)pluginHandledMenuButtonDownEvent;
- (BOOL)pluginHandledPasscodeUnlockWithCompletion:(id)fp(null);
- (void)dismissPluginForEvent:(int)fp8;
- (void)_dismissUIPlugin:(id)fp8 animated:(BOOL)fp12;
- (void)cancelPendingPluginActivationEvent:(int)fp8;
- (void)preparePluginForActivationEvent:(int)fp8 afterInterval:(double)fp12;
- (BOOL)pluginWantsActivationEvent:(int)fp8 interval:(double *)fp12;
- (BOOL)activatePluginForEvent:(int)fp8 context:(void *)fp12;
- (BOOL)activatePluginForEvent:(int)fp8;
- (BOOL)expectsFaceContact;
- (BOOL)isPluginRunning;
- (BOOL)isPluginVisible;
- (void)_notePluginVisibilityDidChange;
- (void)_restoreOrientation;
- (void)_remoteLocked:(id)fp8;
- (void)_deviceBlocked:(id)fp8;
- (void)_uiLocked:(id)fp8;
- (void)_noteDeviceLockedOrBlocked;
- (void)_pluginWillUnload:(id)fp8;
- (void)_pluginDidLoad:(id)fp8;
- (void)_removeObserversForPlugin:(id)fp8;
- (BOOL)pluginSupportedAndEnabled;
- (void)dealloc;
- (id)init;

@end

