/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBUIBannerTargetManagerObserver <NSObject>
- (void)bannerTargetManager:(id)fp8 didRemoveTarget:(id)fp12;
- (void)bannerTargetManager:(id)fp8 didAddTarget:(id)fp12;
@end

