/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAppSliderController, SBAppSwitcherPageView, UIView;

@interface SBUISwitcherDismissAnimationController : SBUIMainScreenAnimationController
{
    SBAppSliderController *_sliderController;
    UIView *_appContextHostView;
    SBAppSwitcherPageView *_animatingPageView;
    BOOL _finishedSwitcherAnimation;
    BOOL _finishedCrossfadingToHostView;
}

- (void)_reportAnimationFinishedIfNecessary;
- (void)_noteCrossfadeDidFinish;
- (void)_noteSwitcherAnimationFinished;
- (void)_crossfadeApp;
- (void)_applicationDependencyStateChanged;
- (id)_animationProgressDependency;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12;

@end

