/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationController.h"

#import "SBUIAnimationControllerDelegate-Protocol.h"

@class NSMutableArray;

@interface SBUIAnimationControllerGroup : SBUIAnimationController <SBUIAnimationControllerDelegate>
{
    NSMutableArray *_animations;
    BOOL _finished;
}

- (id)animations;
- (id)description;
- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (void)_forEachAnimation:(id)fp(null);
- (void)_startAnimation;
- (BOOL)_willAnimate;
- (BOOL)waitingToStart;
- (void)endAnimation;
- (void)beginAnimation;
- (void)addAnimation:(id)fp8;
- (void)dealloc;
- (id)initWithAnimations:(id)fp8;
- (id)init;

@end

