/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIStarkScreenAnimationController.h"

@class SBAlert, UIView;

@interface SBUIStarkAnimationZoomUpApp : SBUIStarkScreenAnimationController
{
    SBAlert *_alertImpersonator;
    UIView *_viewToAnimate;
    UIView *_contextHostView;
    BOOL _requiresHostView;
    BOOL _activateBeforeHosting;
}

- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 withAlertImpersonator:(id)fp12 starkScreenController:(id)fp16;
- (id)initWithActivatingApp:(id)fp8 starkScreenController:(id)fp12;

@end

