/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAlertManager, SBUIFullscreenAlertAdapter;

@interface SBUIAnimationFadeHomeToPluginAlert : SBUIMainScreenAnimationController
{
    SBAlertManager *_alertManager;
    SBUIFullscreenAlertAdapter *_alert;
    BOOL _alertIsTransparent;
    BOOL _alertViewIsAnimatingItself;
    BOOL _finishedPrimaryFadeAnimation;
}

- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_alertViewFinishedAnimatingItself;
- (void)_fadeAnimationFinished;
- (void)_evaluateTotalAnimationCompletion;
- (void)_animationFinished;
- (void)_prepareAnimation;
- (double)animationDuration;
- (void)dealloc;
- (id)initWithAlertManager:(id)fp8 alert:(id)fp12;

@end

