/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationZoomUpApp.h"

#import "SBIconAnimatorDelegate-Protocol.h"

@class SBIconAnimator;

@interface SBUIAnimationZoomUpAppFromHome : SBUIAnimationZoomUpApp <SBIconAnimatorDelegate>
{
    SBIconAnimator *_iconAnimator;
}

- (void)iconAnimatorWasInvalidated:(id)fp8;
- (void)cleanupZoom;
- (void)animateZoomWithCompletion:(id)fp(null);
- (void)prepareZoom;
- (void)dealloc;

@end

