/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBUnlockActionContextFactory : _ABAddressBookCopyLocalizedLabel
{
}

+ (id)sharedInstance;
- (id)unlockActionContextForWidgetRequest:(id)fp(null);
- (id)unlockActionContextForSnoozedAlarmItem:(id)fp8;
- (id)unlockActionContextForCardItem:(id)fp8;
- (id)unlockActionContextForAlertItem:(id)fp8;
- (id)unlockActionContextForBulletin:(id)fp8 withOrigin:(int)fp12 pluginActionsAllowed:(BOOL)fp16;

@end

