/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBUnlockActionContext : _ABAddressBookCopyLocalizedLabel
{
    NSString *_lockLabel;
    NSString *_shortLockLabel;
    id _unlockAction;
    NSString *_identifier;
    float _fontSize;
    BOOL _requiresUnlock;
    BOOL _deactivateAwayController;
    BOOL _canBypassPinLock;
}

- (void)setCanBypassPinLock:(BOOL)fp8;
- (BOOL)canBypassPinLock;
- (void)setDeactivateAwayController:(BOOL)fp8;
- (BOOL)deactivateAwayController;
- (void)setRequiresUnlock:(BOOL)fp8;
- (BOOL)requiresUnlock;
- (void)setIdentifier:(id)fp8;
- (id)identifier;
- (void)setUnlockAction:(id)fp(null);
- (id)unlockAction;
- (void)setShortLockLabel:(id)fp8;
- (void)setLockLabel:(id)fp8;
- (BOOL)hasCustomUnlockLabel;
- (id)shortLockLabel;
- (id)lockLabel;
- (void)dealloc;
- (id)initWithLockLabel:(id)fp8 shortLockLabel:(id)fp12 unlockAction:(id)fp(null) identifier:(void)fp16;

@end

