/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertView.h"

#import "UITextFieldDelegate-Protocol.h"

@class TPButton, UIActivityIndicatorView, UITextField, UITextView, UITransitionView, UIView;

@interface SBUSSDAlertDisplay : SBAlertView <UITextFieldDelegate>
{
    TPButton *_dismissButton;
    TPButton *_replyButton;
    UIView *_notifyView;
    UIView *_replyView;
    UITransitionView *_transitionView;
    UITextView *_charsRemainingView;
    UIActivityIndicatorView *_progressIndicator;
    UITextField *_responseField;
    UITextView *_textView;
    UITextView *_responseMessageView;
    BOOL _allowsResponse;
}

- (void)_cancelClicked;
- (void)_okayClicked;
- (void)_replyClicked;
- (void)_textChanged:(id)fp8;
- (void)_updateCharsRemaining;
- (BOOL)textField:(id)fp8 shouldInsertText:(id)fp12 replacingRange:(struct _NSRange)fp16;
- (void)setAllowsResponse:(BOOL)fp8;
- (BOOL)allowsResponse;
- (void)alertStringAvailable:(id)fp8;
- (void)_setupResponseBar;
- (void)layoutSubviews;
- (void)alertDisplayBecameVisible;
- (void)alertDisplayWillBecomeVisible;
- (void)displayString:(id)fp8;
- (id)_responseMessageView;
- (id)_textView;
- (id)_charsRemainingView;
- (void)dealloc;
- (id)_replyView;
- (id)_notifyView;
- (id)initWithFrame:(struct CGRect)fp8;

@end

