/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView;

@interface SBViewSnapshotProvider : _ABAddressBookCopyLocalizedLabel
{
    UIView *_view;
    id _completionBlock;
}

- (void)setCompletionBlock:(id)fp(null);
- (id)completionBlock;
- (void)snapshotAsynchronously:(BOOL)fp8 withImageBlock:(id)fp(null);
- (void)snapshotWithImageBlock:(id)fp(null);
- (id)snapshot;
- (void)dealloc;
- (id)initWithView:(id)fp8;

@end

