/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBFWallpaperViewInternalObserver-Protocol.h"
#import "SBFWallpaperViewLegibilityObserver-Protocol.h"
#import "SBUIActiveOrientationObserver-Protocol.h"
#import "UIWindowDelegate-Protocol.h"

@class NSHashTable, NSMutableSet, SBFWallpaperView, SBWallpaperEffectView, SBWallpaperPreviewSnapshotCache, UIView, UIWindow;

@interface SBWallpaperController : _ABAddressBookCopyLocalizedLabel <SBFWallpaperViewLegibilityObserver, SBFWallpaperViewInternalObserver, SBUIActiveOrientationObserver, UIWindowDelegate>
{
    UIWindow *_wallpaperWindow;
    UIView *_wallpaperContainerView;
    int _orientation;
    SBFWallpaperView *_lockscreenWallpaperView;
    SBFWallpaperView *_homescreenWallpaperView;
    SBFWallpaperView *_sharedWallpaperView;
    NSHashTable *_lockscreenObservers;
    NSHashTable *_homescreenObservers;
    CDAnonymousStruct2 _lockscreenPriorityInfo[3];
    CDAnonymousStruct2 _homescreenPriorityInfo[6];
    CDAnonymousStruct7 _lockscreenStyleTransitionState;
    CDAnonymousStruct7 _homescreenStyleTransitionState;
    SBWallpaperEffectView *_lockscreenEffectView;
    SBWallpaperEffectView *_homescreenEffectView;
    NSMutableSet *_suspendColorSamplingReasons;
    NSMutableSet *_suspendWallpaperAnimationReasons;
    NSMutableSet *_requireWallpaperReasons;
    NSMutableSet *_hideHomescreenWallpaperReasons;
    NSMutableSet *_hideLockscreenWallpaperReasons;
    int _displayedVariant;
    float _lockscreenOnlyWallpaperAlpha;
    NSHashTable *_lockscreenBlurViews;
    NSHashTable *_homescreenBlurViews;
    int _disallowRasterizationBlockCount;
    NSMutableSet *_disallowRasterizationReasonsHomeVariant;
    NSMutableSet *_disallowRasterizationReasonsLockVariant;
    struct CGColor *_homescreenLightForegroundBlurColor;
    struct CGRect _homescreenLightForegroundBlurColorRect;
    BOOL _isSuspendingMotionEffectsForBlur;
    SBWallpaperPreviewSnapshotCache *_previewCache;
    int _activeOrientationSource;
    BOOL _coalescingGeometryChanges;
    int _locationsWithCoalescedGeometryChanges;
    float _homescreenWallpaperScale;
    float _lockscreenWallpaperScale;
}

+ (id)sharedInstance;
- (float)lockscreenWallpaperScale;
- (float)homescreenWallpaperScale;
- (void)wallpaperViewDidChangeWantsRasterization:(id)fp8;
- (void)wallpaperView:(id)fp8 didChangeZoomFactor:(float)fp12;
- (void)wallpaperViewDidInvalidateGeometry:(id)fp8;
- (void)wallpaperViewDidInvalidateBlurs:(id)fp8;
- (void)wallpaperView:(id)fp8 legibilitySettingsDidChange:(id)fp12;
- (void)activeInterfaceOrientationDidChangeToOrientation:(int)fp8 willAnimateWithDuration:(double)fp12 fromOrientation:(int)fp20;
- (void)activeInterfaceOrientationWillChangeToOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)orientationSource:(int)fp8 didRotateFromInterfaceOrientation:(int)fp12;
- (void)orientationSource:(int)fp8 willAnimateRotationToInterfaceOrientation:(int)fp12 duration:(double)fp16;
- (void)orientationSource:(int)fp8 willRotateToInterfaceOrientation:(int)fp12 duration:(double)fp16;
- (BOOL)_isAcceptingOrientationChangesFromSource:(int)fp8;
- (void)setActiveOrientationSource:(int)fp8 andUpdateToOrientation:(int)fp12;
- (void)_updateRasterizationState;
- (void)_endDisallowRasterizationBlock;
- (void)_beginDisallowRasterizationBlock;
- (id)_getImageInRect:(struct CGRect)fp8 withZoomFactor:(float)fp24 forVariant:(int)fp28 style:(inout int *)fp32;
- (id)_newFakeBlurViewForVariant:(int)fp8;
- (void)_clearHomescreenLightForegroundBlurColor;
- (void)_createHomescreenLightForegroundBlurColorIfNecessary;
- (void)_updateBlurGeneration;
- (id)_sourceForFakeBlurView:(id)fp8;
- (void)_unregisterFakeBlurView:(id)fp8;
- (void)_registerFakeBlurView:(id)fp8;
- (void)_suspendOrResumeWallpaperAnimation;
- (void)_suspendOrResumeColorSampling;
- (id)_blurViewsForVariant:(int)fp8;
- (id)_observersForVariant:(int)fp8;
- (id)_wallpaperViewForVariant:(int)fp8;
- (id)_blurImageObservableForBlurView:(id)fp8 sourceView:(id)fp12;
- (void)_updateBlurImagesForVariant:(int)fp8;
- (void)_reconfigureBlurViewsForVariant:(int)fp8;
- (void)_handleWallpaperGeometryChangedForVariant:(int)fp8;
- (void)_handleWallpaperLegibilitySettingsChanged:(id)fp8 forVariant:(int)fp12;
- (void)_handleWallpaperChangedForVariant:(int)fp8;
- (BOOL)_updateEffectViewForVariant:(int)fp8 withFactory:(id)fp12;
- (void)_updateMotionEffectsForState:(CDAnonymousStruct7)fp8;
- (BOOL)_shouldSuspendMotionEffectsForState:(CDAnonymousStruct7)fp8;
- (void)_endSuspendingMotionEffectsForBlurIfNeeded;
- (void)_beginSuspendingMotionEffectsForBlurIfNeeded;
- (void)_updateScreenBlanked;
- (void)_accessibilityEnhanceBackgroundContrastChanged:(id)fp8;
- (void)_motionEffectsChanged;
- (id)_newWallpaperEffectViewForVariant:(int)fp8 transitionState:(CDAnonymousStruct7)fp12;
- (void)_clearWallpaperEffectView:(id *)fp8;
- (void)_clearWallpaperView:(id *)fp8;
- (id)_newWallpaperViewForProcedural:(id)fp8 orImage:(id)fp12;
- (void)_updateSeparateWallpaper;
- (void)_updateSharedWallpaper;
- (void)_updateWallpaperForLocations:(int)fp8 withCompletion:(id)fp(null);
- (BOOL)variantsShareWallpaper;
- (void)_updateWallpaperHidden;
- (void)_setWallpaperHidden:(BOOL)fp8 variant:(int)fp12 reason:(id)fp16;
- (BOOL)_setDisallowRasterization:(BOOL)fp8 withReason:(id)fp12 reasons:(id)fp16;
- (BOOL)_isRasterizationDisallowedForCurrentVariant;
- (void)setDisallowsRasterization:(BOOL)fp8 forVariant:(int)fp12 withReason:(id)fp16;
- (id)previewCache;
- (struct CGSize)homescreenLightForegroundBlurColorPhaseForRect:(struct CGRect)fp8;
- (struct CGColor *)homescreenLightForegroundBlurColor;
- (id)averageColorInRect:(struct CGRect)fp8 forVariant:(int)fp24 withSmudgeRadius:(float)fp28;
- (id)averageColorInRect:(struct CGRect)fp8 forVariant:(int)fp24;
- (id)averageColorForVariant:(int)fp8;
- (id)legibilitySettingsForVariant:(int)fp8;
- (void)resumeWallpaperAnimationForReason:(id)fp8;
- (void)suspendWallpaperAnimationForReason:(id)fp8;
- (void)resumeColorSamplingForReason:(id)fp8;
- (void)suspendColorSamplingForReason:(id)fp8;
- (void)removeObserver:(id)fp8 forVariant:(int)fp12;
- (void)addObserver:(id)fp8 forVariant:(int)fp12;
- (void)endRequiringWithReason:(id)fp8;
- (void)beginRequiringWithReason:(id)fp8;
- (void)removeHomescreenStyleForGuidedAccessPriorityWithAnimationFactory:(id)fp8;
- (void)setHomescreenStyleForGuidedAccessPriorityWithAnimationFactory:(id)fp8;
- (BOOL)removeLockscreenStyleForPriority:(int)fp8 withAnimationFactory:(id)fp12;
- (BOOL)removeHomescreenStyleForPriority:(int)fp8 withAnimationFactory:(id)fp12;
- (BOOL)setLockscreenStyleTransitionState:(CDAnonymousStruct7)fp8 forPriority:(int)fp20 withAnimationFactory:(id)fp24;
- (BOOL)setHomescreenStyleTransitionState:(CDAnonymousStruct7)fp8 forPriority:(int)fp20 withAnimationFactory:(id)fp24;
- (BOOL)setLockscreenStyle:(int)fp8 forPriority:(int)fp12 withAnimationFactory:(id)fp16;
- (BOOL)setHomescreenStyle:(int)fp8 forPriority:(int)fp12 withAnimationFactory:(id)fp16;
- (CDAnonymousStruct7)currentHomescreenStyleTransitionState;
- (void)setLockscreenOnlyWallpaperAlpha:(float)fp8;
- (void)setLockscreenWallpaperScale:(float)fp8;
- (void)setHomescreenWallpaperScale:(float)fp8;
- (float)windowLevel;
- (void)setWindowLevel:(float)fp8;
- (void)setLockscreenWallpaperContentsRect:(struct CGRect)fp8;
- (void)setVariant:(int)fp8 withOutAnimationFactory:(id)fp12 inAnimationFactory:(id)fp16 completion:(id)fp(null);
- (void)setVariant:(int)fp8;
- (int)variant;
- (void)dealloc;
- (id)initWithOrientation:(int)fp8 variant:(int)fp12;

@end

