/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconIndexNodeObserver-Protocol.h"

@class SBFMappedImageCache;

@interface SBWallpaperPreviewSnapshotCache : _ABAddressBookCopyLocalizedLabel <SBIconIndexNodeObserver>
{
    SBFMappedImageCache *_imageCache;
    int _invalidatedLocations;
}

- (id)_lockScreenSnapshotProvider;
- (id)_homeScreenSnapshotProvider;
- (void)_backlightFadeFinished;
- (void)node:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)node:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
- (void)regenerateSnapshotsForLocations:(int)fp8 withCompletion:(id)fp(null);
- (id)homeScreenSnapshot;
- (id)lockScreenSnapshot;
- (void)invalidateSnapshotsForLocations:(int)fp8;
- (void)dealloc;
- (id)initWithImageCache:(id)fp8;

@end

