/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBFLegibilitySettingsProvider-Protocol.h"
#import "SBWallpaperObserver-Protocol.h"

@interface SBWallpaperLegibilitySettingsProvider : _ABAddressBookCopyLocalizedLabel <SBWallpaperObserver, SBFLegibilitySettingsProvider>
{
    id <SBFLegibilitySettingsProviderDelegate> _delegate;
    int _variant;
}

- (id)delegate;
- (void)wallpaperLegibilitySettingsDidChange:(id)fp8 forVariant:(int)fp12;
- (void)wallpaperDidChangeForVariant:(int)fp8;
- (id)legibilitySettings;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (id)initWithVariant:(int)fp8;

@end

