/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBWallpaperObserver-Protocol.h"
#import "_SBFakeBlurObserver-Protocol.h"

@class UIColor, UIImage, UIImageView, UIView, UIView<_SBFakeBlur>;

@interface SBWallpaperEffectView : _ABAddressBookCopyLocalizedLabel <_SBFakeBlurObserver, SBWallpaperObserver>
{
    int _variant;
    UIColor *_wallpaperAverageColor;
    int _startStyle;
    int _endStyle;
    float _transitionFraction;
    UIView<_SBFakeBlur> *_blurView;
    UIView *_grayscaleTintView;
    UIView *_colorTintView;
    UIView<_SBFakeBlur> *_transitionBlurView;
    UIView *_transitionGrayscaleTintView;
    UIView *_transitionColorTintView;
    UIImageView *_maskImageView;
    UIView *_blurMaskingContainer;
    UIView *_tintMaskingContainer;
    UIImage *_maskImage;
    BOOL _shouldMaskBlur;
    BOOL _shouldMaskTint;
    BOOL _accessibilityIncreaseContrastEnabled;
}

+ (id)imageInRect:(struct CGRect)fp8 forVariant:(int)fp24 withStyle:(int)fp28 zoomFactor:(float)fp32 mask:(id)fp36 masksBlur:(BOOL)fp40 masksTint:(BOOL)fp44;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)_accessibilityEnhanceBackgroundContrastChanged:(id)fp8;
- (void)_clearView:(id *)fp8;
- (void)_configureGrayscaleTintView:(id *)fp8 colorTintView:(id *)fp12 forStyle:(int)fp16;
- (void)_configureViews;
- (void)_configureForCurrentBlurStyle;
- (void)_configureFromScratch;
- (void)_setTransitionFraction:(float)fp8;
- (void)_updateWallpaperAverageColor:(id)fp8;
- (void)wallpaperDidChangeForVariant:(int)fp8;
- (void)wallpaperLegibilitySettingsDidChange:(id)fp8 forVariant:(int)fp12;
- (void)fakeBlurView:(id)fp8 didChangeStyle:(int)fp12;
- (void)layoutSubviews;
- (void)setMaskImage:(id)fp8 masksBlur:(BOOL)fp12 masksTint:(BOOL)fp16;
- (BOOL)currentTransitionStateIsOpaque;
- (void)setTransitionState:(CDAnonymousStruct7)fp8;
- (BOOL)prepareToAnimateToTransitionState:(inout CDAnonymousStruct7 *)fp8;
- (void)setStyle:(int)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithWallpaperVariant:(int)fp8;

@end

