/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplication.h"

@class UIWebClip;

@interface SBWebApplication : SBApplication
{
    UIWebClip *_webClip;
    BOOL _isLastWebApplication;
}

+ (id)displayIdentifierForWebClipIdentifier:(id)fp8;
+ (id)displayIdentifierForWebClip:(id)fp8;
- (void)setWebClip:(id)fp8;
- (id)webClip;
- (BOOL)iconAllowsUninstall:(id)fp8;
- (id)icon:(id)fp8 imageWithFormat:(int)fp12;
- (BOOL)windowContextHostManager:(id)fp8 shouldEnableContextHostingForRequester:(id)fp12 priority:(int)fp16;
- (id)windowContextHostManager:(id)fp8 overrideRequester:(id)fp12;
- (void)_removeContextHostManager:(id)fp8;
- (void)_removeContextHostManagerWithoutLooping:(id)fp8;
- (void)_addContextHostManager:(id)fp8;
- (void)_addContextHostManagerWithoutLooping:(id)fp8;
- (void)willActivateOtherWebApplication:(id)fp8;
- (void)_setActivationState:(int)fp8;
- (void)didExitWithInfo:(id)fp8 type:(int)fp12;
- (void)setRunning:(BOOL)fp8;
- (void)setProcessInfo:(id)fp8;
- (id)_defaultImageInfoForScreen:(id)fp8 launchingOrientation:(int)fp12;
- (BOOL)isSnapshotPresentForLaunchingInterfaceOrientation:(int)fp8;
- (id)_customStartupImageForScreen:(id)fp8 launchingOrientation:(int)fp12;
- (BOOL)isWebApplication;
- (id)activationSettings;
- (id)_urlForLaunch;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)fp8 webClip:(id)fp12 path:(id)fp16 bundle:(id)fp20 infoDictionary:(id)fp24 isSystemApplication:(BOOL)fp28 signerIdentity:(id)fp32 provisioningProfileValidated:(BOOL)fp36 entitlements:(id)fp40;

@end

