/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBWindowContextManagerObserver-Protocol.h"

@class NSMutableArray, NSMutableOrderedSet, NSMutableSet, SBWindowContextHostManager, SBWindowContextManager, UIScreen;

@interface SBWindowContextHostView : _ABAddressBookCopyLocalizedLabel <SBWindowContextManagerObserver>
{
    UIScreen *_screen;
    SBWindowContextHostManager *_hostManager;
    SBWindowContextManager *_contextManager;
    NSMutableSet *_hiddenContexts;
    NSMutableOrderedSet *_contexts;
    NSMutableArray *_layerHosts;
}

- (id)screen;
- (void)setHostManager:(id)fp8;
- (id)hostManager;
- (void)windowContextManager:(id)fp8 didRepositionContext:(id)fp12 from:(unsigned int)fp16 to:(unsigned int)fp20 forScreen:(id)fp24;
- (id)description;
- (id)window;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (BOOL)hasContent;
- (BOOL)isHosting;
- (void)setHiddenContexts:(id)fp8;
- (id)hiddenContexts;
- (void)setContextManager:(id)fp8;
- (id)contextManager;
- (void)_adjustLayerFrameAndTransform:(id)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithScreen:(id)fp8 jailBehavior:(int)fp12;

@end

