/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMapTable;

@interface SBWindowManager : _ABAddressBookCopyLocalizedLabel
{
    NSMapTable *_windowStateMap;
    NSMapTable *_hidingContextMap;
    struct SBWindowLevelRange_struct _hideRange;
}

+ (void)start;
+ (id)sharedInstance;
- (id)dumpKnownWindows;
- (id)dumpHidingState;
- (void)_releaseWindow:(id)fp8;
- (BOOL)_isHidingWindowLevel:(float)fp8;
- (void)_captureWindow:(id)fp8;
- (void)_takeNoteOfWindow:(id)fp8 onScreen:(id)fp12;
- (void)_adjustWindowsForActiveHideRange;
- (void)_recomputeHideRangeAndAdjustWindows;
- (BOOL)_isHidingWindows;
- (void)stopHidingWindowsForContext:(id)fp8;
- (void)startHidingWindowsExclusivelyFromLevel:(float)fp8 toLevel:(float)fp12 forContext:(id)fp16 reason:(id)fp20;
- (void)setAlpha:(float)fp8 forWindow:(id)fp12;
- (id)init;

@end

