/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary, NSString, SBOrderedRequesters, SBWindowContextHostView, SBWindowContextManager, UIColor, UIScreen;

@interface SBWindowContextHostManager : _ABAddressBookCopyLocalizedLabel
{
    SBWindowContextManager *_contextManager;
    UIScreen *_screen;
    NSString *_identifier;
    UIColor *_defaultBackgroundColorWhileHosting;
    UIColor *_defaultBackgroundColorWhileNotHosting;
    SBWindowContextHostView *_hostView;
    BOOL _suspended;
    SBOrderedRequesters *_hostRequesters;
    NSMutableDictionary *_hostRequesterInfo;
    int _jailBehavior;
    id <SBWindowContextHostManagerDelegate> _delegate;
    struct {
        unsigned int delegateOverrideRequester:1;
        unsigned int delegateShouldEnableContextHostingForRequester:1;
    } _flags;
}

- (void)setIdentifier:(id)fp8;
- (id)identifier;
- (id)screen;
- (void)_notePropertiesSetOnRealContextHostViewWhichIReallyNeedToChangeAndIKnowWhatImDoingISwear:(id)fp8 originalProperties:(id)fp12 forRequester:(id)fp16;
- (id)_realContextHostViewWhichIReallyNeedToAccessAndIKnowWhatImDoingISwear;
- (void)_hostOnDefaultWindowForRequester:(id)fp8 priority:(int)fp12 hide:(BOOL)fp16;
- (id)_overrideRequesterIfNecessary:(id)fp8;
- (void)_removeRequesterInfo:(id)fp8;
- (void)_applyRequesterInfo:(id)fp8;
- (id)_infoForRequester:(id)fp8;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8 excludeContext:(unsigned int)fp24 outTransform:(struct CGAffineTransform *)fp28;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8 outTransform:(struct CGAffineTransform *)fp24;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8;
- (void)setContextId:(unsigned int)fp8 hidden:(BOOL)fp12 forRequester:(id)fp16;
- (void)hideHostViewOnDefaultWindowForRequester:(id)fp8 priority:(int)fp12;
- (void)hideHostViewOnDefaultWindowForRequester:(id)fp8;
- (void)unhideHostViewOnDefaultWindowForRequester:(id)fp8;
- (void)orderRequesterFront:(id)fp8;
- (void)disableHostingForRequester:(id)fp8;
- (void)resumeContextHosting;
- (void)suspendContextHosting;
- (void)enableHostingForRequester:(id)fp8 priority:(int)fp12;
- (void)enableHostingForRequester:(id)fp8 orderFront:(BOOL)fp12;
- (id)hostViewForRequester:(id)fp8 enableAndOrderFront:(BOOL)fp12;
- (id)hostViewForRequester:(id)fp8;
- (id)description;
- (unsigned int)contextCount;
- (id)defaultBackgroundColorWhileNotHosting;
- (void)setDefaultBackgroundColorWhileNotHosting:(id)fp8;
- (id)defaultBackgroundColorWhileHosting;
- (void)setDefaultBackgroundColorWhileHosting:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)dealloc;
- (id)initWithContextManager:(id)fp8 screen:(id)fp12 jailBehavior:(int)fp16;
- (id)initWithContextManager:(id)fp8 screen:(id)fp12;

@end

