/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIScreen;

@interface SBWindowContext : _ABAddressBookCopyLocalizedLabel
{
    unsigned int _identifier;
    float _level;
    UIScreen *_screen;
    BOOL _orderOutPending;
}

+ (id)contextWithIdentifier:(unsigned int)fp8 level:(float)fp12 screen:(id)fp16;
- (void)setOrderOutPending:(BOOL)fp8;
- (BOOL)isOrderOutPending;
- (id)screen;
- (float)level;
- (unsigned int)identifier;
- (id)description;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (void)dealloc;
- (id)initWithIdentifier:(unsigned int)fp8 level:(float)fp12 screen:(id)fp16;

@end

