/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBWindowHideState : _ABAddressBookCopyLocalizedLabel
{
    BOOL _hidden;
    float _desiredAlpha;
}

- (void)setDesiredAlpha:(float)fp8;
- (float)desiredAlpha;
- (void)setHidden:(BOOL)fp8;
- (BOOL)isHidden;
- (id)description;

@end

