/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBWindowHideRequest : _ABAddressBookCopyLocalizedLabel
{
    NSString *_reason;
    struct SBWindowLevelRange_struct _windowLevelRange;
}

+ (id)hideRequestWithWindowLevelRange:(struct SBWindowLevelRange_struct)fp8 reason:(id)fp16;
- (void)setReason:(id)fp8;
- (id)reason;
- (void)setWindowLevelRange:(struct SBWindowLevelRange_struct)fp8;
- (struct SBWindowLevelRange_struct)windowLevelRange;
- (id)description;

@end

