/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBWindowContextManagerObserver <NSObject>
- (void)windowContextManager:(id)fp8 didRepositionContext:(id)fp12 from:(unsigned int)fp16 to:(unsigned int)fp20 forScreen:(id)fp24;
@end

