/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBWindowContextAppearance-Protocol.h"

@class SBWindowContextHostManager, UIColor;

@interface SBWindowContextHostWrapperView : _ABAddressBookCopyLocalizedLabel <SBWindowContextAppearance>
{
    SBWindowContextHostManager *_manager;
    UIColor *_backgroundColorWhileNotHosting;
    UIColor *_backgroundColorWhileHosting;
}

- (id)description;
- (id)window;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)_didRemoveSubview:(id)fp8;
- (void)didAddSubview:(id)fp8;
- (void)setBackgroundColorWhileNotHosting:(id)fp8;
- (id)backgroundColorWhileNotHosting;
- (void)setBackgroundColorWhileHosting:(id)fp8;
- (id)backgroundColorWhileHosting;
- (void)clearManager;
- (void)updateBackgroundColor;
- (void)_toggleBackgroundColorIfNecessary;
- (id)_backgroundColorWhileNotHosting;
- (id)_backgroundColorWhileHosting;
- (void)_hostingStatusChanged;
- (BOOL)_isReallyHosting;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 manager:(id)fp24;

@end

