/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBWindow : _ABAddressBookCopyLocalizedLabel
{
    int _jailBehavior;
}

+ (struct CGRect)_actualBoundsForScreen:(id)fp8 withJailBehavior:(int)fp12;
+ (struct UIEdgeInsets)_jailInsetsForScreen:(id)fp8;
- (BOOL)_isClippedByScreenJail;
- (BOOL)_isConstrainedByScreenJail;
- (void)setAlpha:(float)fp8;
- (void)setScreen:(id)fp8;
- (struct UIEdgeInsets)jailInsets;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithScreen:(id)fp8 jailBehavior:(int)fp12;
- (void)setAlphaAndObeyBecauseIAmTheWindowManager:(float)fp8;

@end

