/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFileLogger.h"

@interface SBWorkspaceLogger : SBFileLogger
{
}

+ (void)handleSignal;
+ (BOOL)saveRecentLogsToTemporaryPath:(id *)fp8;
+ (id)recentLogs;
+ (BOOL)isWorkspaceLoggingEnabled;
+ (int)workspaceLoggingType;
- (void)willBeginLoggingToPath:(id)fp8;
- (id)fileFormat:(id)fp8 withArguments:(void *)fp12;
- (BOOL)includeConsole;
- (void)reloadFromDefaults;
- (id)name;
- (BOOL)isEnabled;

@end

