/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BKSWorkspaceDelegate-Protocol.h"
#import "SBAlertManagerDelegate-Protocol.h"
#import "SBAlertManagerObserver-Protocol.h"
#import "SBStarkScreenControllerDelegate-Protocol.h"
#import "SBStarkScreenManagerDelegate-Protocol.h"
#import "SBWorkspaceTransactionGroupDelegate-Protocol.h"

@class BKSWorkspace, NSMutableArray, NSObject<OS_dispatch_source>, NSTimer, SBAlertManager, SBScreenTimeTrackingController, SBWorkspaceEventQueueLockAssertion, SBWorkspaceTransaction;

@interface SBWorkspace : _ABAddressBookCopyLocalizedLabel <BKSWorkspaceDelegate, SBAlertManagerDelegate, SBAlertManagerObserver, SBWorkspaceTransactionGroupDelegate, SBStarkScreenManagerDelegate, SBStarkScreenControllerDelegate>
{
    BKSWorkspace *_bksWorkspace;
    SBAlertManager *_alertManager;
    BOOL _alertManagerIsDeactivatingAlert;
    SBScreenTimeTrackingController *_screenTimeTrackingController;
    SBWorkspaceTransaction *_currentTransaction;
    SBWorkspaceEventQueueLockAssertion *_eventQueueLock;
    NSObject<OS_dispatch_source> *_transactionWatchdog;
    NSTimer *_relaunchTimer;
    NSMutableArray *_applicationsToRelaunch;
}

- (id)alertManager;
- (id)bksWorkspace;
- (id)currentTransaction;
- (void)starkScreenController:(id)fp8 didChangeStateFromState:(int)fp12;
- (void)starkScreenManagerDidChangeActiveController:(id)fp8;
- (void)starkScreenManagerWillChangeActiveController:(id)fp8;
- (void)transactionGroup:(id)fp8 childTransactionDidFinish:(id)fp12 success:(BOOL)fp16;
- (void)transactionDidFinish:(id)fp8 success:(BOOL)fp12;
- (void)alertManager:(id)fp8 didRemoveAlert:(id)fp12 fromWindow:(id)fp16;
- (void)alertManager:(id)fp8 didTearDownAlertWindow:(id)fp12;
- (void)alertManager:(id)fp8 willTearDownAlertWindow:(id)fp12;
- (void)alertManager:(id)fp8 topAlert:(id)fp12 requestsWallpaperStyleChangeWithAnimationFactory:(id)fp16;
- (void)alertManagerDidChangeTopAlert:(id)fp8;
- (void)alertManager:(id)fp8 didDeactivateAlert:(id)fp12 top:(BOOL)fp16;
- (void)alertManager:(id)fp8 willDeactivateAlert:(id)fp12 top:(BOOL)fp16;
- (void)alertManager:(id)fp8 didActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 willActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (id)alertManager:(id)fp8 newAlertWindowForLockAlerts:(BOOL)fp12;
- (BOOL)alertManager:(id)fp8 shouldDeactivateDismissedAlert:(id)fp12;
- (void)_updateStatusBarTimeItemEnabled;
- (void)workspace:(id)fp8 applicationDebugStateChanged:(id)fp12 newState:(BOOL)fp16;
- (void)workspace:(id)fp8 handleStatusBarReturnActionFromApplication:(id)fp12 statusBarStyle:(id)fp16;
- (void)workspace:(id)fp8 applicationFinishedBackgroundContentFetching:(id)fp12 withInfo:(id)fp16;
- (void)workspace:(id)fp8 applicationSuspensionSettingsUpdated:(id)fp12 withSettings:(id)fp16;
- (void)workspace:(id)fp8 applicationSuspended:(id)fp12 withSettings:(id)fp16;
- (void)workspace:(id)fp8 applicationExited:(id)fp12 withInfo:(id)fp16;
- (void)workspace:(id)fp8 applicationDidFailToLaunch:(id)fp12;
- (void)workspace:(id)fp8 applicationActivated:(id)fp12;
- (void)workspace:(id)fp8 applicationDidFinishLaunching:(id)fp12 withInfo:(id)fp16;
- (void)workspace:(id)fp8 applicationDidStartLaunching:(id)fp12;
- (void)workspace:(id)fp8 handleOpenURLRequest:(id)fp12 application:(id)fp16 withOptions:(id)fp20 origin:(id)fp24 withResult:(id)fp(null);
- (void)workspace:(id)fp8 handleOpenApplicationRequest:(id)fp12 withOptions:(id)fp16 origin:(id)fp20 withResult:(id)fp(null);
- (int)workspace:(id)fp8 canOpenApplication:(id)fp12;
- (void)workspaceDidResume:(id)fp8;
- (void)workspaceWillResume:(id)fp8;
- (void)workspaceDidSuspend:(id)fp8;
- (void)workspaceWillSuspend:(id)fp8;
- (void)workspace:(id)fp8 applicationDidBecomeReceiver:(id)fp12 fromApplication:(id)fp16;
- (id)workspace:(id)fp8 applicationWillBecomeReceiver:(id)fp12 fromApplication:(id)fp16;
- (void)updateInterruptedByCallSettingsFrom:(id)fp8 to:(id)fp12;
- (BOOL)_applicationExited:(id)fp8 withInfo:(id)fp12;
- (BOOL)_handleSetupExited:(id)fp8;
- (void)_invalidateRelaunchTimer;
- (void)_memoryPressureRelieved:(id)fp8;
- (void)_memoryPressureWarn:(id)fp8;
- (void)_launchNextPendedAutoLaunchApp;
- (void)_scheduleRelaunchTimerIfNecessary;
- (void)_handleBuddyLaunchFinished;
- (id)_applicationForBundleIdentifier:(id)fp8 frontmost:(BOOL)fp12;
- (void)_noteCurrentTransactionFailed:(const char *)fp8;
- (id)_selectTransactionForAppActivationToApp:(id)fp8 activationHandler:(id)fp(null) canDeactivateAlerts:(void)fp12;
- (id)_selectTransactionForAppActivationToApp:(id)fp8 activationHandler:(id)fp(null);
- (id)_selectTransactionForAppExited:(id)fp8;
- (id)_selectTransactionForAppRelaunch:(id)fp8;
- (id)_selectTransactionForAppActivationUnderMainScreenLock:(id)fp8;
- (id)_selectTransactionForReturningToTheLockScreenFromApp:(id)fp8 forceToBuddy:(BOOL)fp12 withActivationHandler:(id)fp(null);
- (id)_selectTransactionForReturningToTheLockScreenWithActivationHandler:(id)fp(null);
- (void)setCurrentTransaction:(id)fp8;
- (id)debugDescription;
- (void)dealloc;
- (id)init;

@end

