/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface SBWorkStore : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_workItemsPerKey;
    NSMutableArray *_keysWithWork;
    NSMutableArray *_observers;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    unsigned int _maxWorkPerKey;
    NSMutableDictionary *_workExpirationPeriods;
    double _defaultWorkExpirationPeriod;
}

- (void)setDefaultWorkExpirationPeriod:(double)fp8;
- (double)defaultWorkExpirationPeriod;
- (unsigned int)maxWorkPerKey;
- (id)observers;
- (id)keysWithWork;
- (id)workItemsPerKey;
- (id)description;
- (void)_notifyObserversWorkDidChange;
- (void)_queue_expireWorkForKey:(id)fp8;
- (void)setWorkExpirationPeriod:(double)fp8 forKey:(id)fp16;
- (void)purgeWorkForKey:(id)fp8;
- (id)dequeueWorkForKey:(id)fp8;
- (void)addWorkItem:(id)fp8 forKey:(id)fp12;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)dealloc;
- (id)initWithMaximumNumberOfWorkItemsPerKey:(unsigned int)fp8;

@end

