/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView;

@interface SBZoomableCrossfadeView : _ABAddressBookCopyLocalizedLabel
{
    UIView *_startView;
    UIView *_endView;
    BOOL _translucent;
    BOOL _crossfaded;
}

+ (id)crossfadeViewWithStartView:(id)fp8 endView:(id)fp12 translucent:(BOOL)fp16;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)crossfadeWithCompletion:(id)fp(null);
- (id)animationFactory;
- (void)layoutSubviews;
- (void)dealloc;
- (id)_initWithStartView:(id)fp8 endView:(id)fp12 translucent:(BOOL)fp16;

@end

